create extension if not exists pgcrypto;

create schema if not exists private;

do $$
begin
  create type public.transaction_type_value as enum ('INBOUND', 'OUTBOUND', 'ADJUSTMENT');
exception
  when duplicate_object then null;
end $$;

create table if not exists public.app_users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique,
  full_name text,
  role text not null default 'manager',
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.models (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default timezone('utc', now()),
  unique (id, user_id),
  unique (user_id, name)
);

create table if not exists public.sizes (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  model_id bigint not null,
  name text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  unique (model_id, id, user_id),
  unique (user_id, model_id, name),
  foreign key (model_id, user_id) references public.models (id, user_id) on delete cascade
);

create table if not exists public.colors (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  model_id bigint not null,
  name text not null,
  rgb_code text not null,
  text_white boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  unique (model_id, id, user_id),
  unique (user_id, model_id, name),
  foreign key (model_id, user_id) references public.models (id, user_id) on delete cascade
);

create table if not exists public.warehouses (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default timezone('utc', now()),
  unique (user_id, name)
);

create table if not exists public.inventory (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  model_id bigint not null,
  size_id bigint not null,
  color_id bigint not null,
  warehouse_id bigint not null references public.warehouses (id) on delete cascade,
  quantity integer not null default 0 check (quantity >= 0),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (user_id, model_id, size_id, color_id, warehouse_id),
  foreign key (model_id, user_id) references public.models (id, user_id) on delete cascade,
  foreign key (model_id, size_id, user_id) references public.sizes (model_id, id, user_id) on delete cascade,
  foreign key (model_id, color_id, user_id) references public.colors (model_id, id, user_id) on delete cascade
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  date date not null,
  model_id bigint not null,
  size_id bigint not null,
  color_id bigint not null,
  type public.transaction_type_value not null,
  quantity integer not null check (quantity > 0),
  warehouse_id bigint not null references public.warehouses (id) on delete cascade,
  source_channel text,
  reference_type text,
  reference_id bigint,
  memo text,
  created_at timestamptz not null default timezone('utc', now()),
  foreign key (model_id, user_id) references public.models (id, user_id) on delete cascade,
  foreign key (model_id, size_id, user_id) references public.sizes (model_id, id, user_id) on delete cascade,
  foreign key (model_id, color_id, user_id) references public.colors (model_id, id, user_id) on delete cascade
);

create table if not exists public.shipping_provider_credentials (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  provider text not null check (provider in ('naver', 'coupang')),
  encrypted_payload text not null,
  iv text not null,
  auth_tag text not null,
  key_version smallint not null default 1,
  masked_summary jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (user_id, provider)
);

create table if not exists public.factories (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null,
  contact_name text,
  phone text,
  email text,
  notes text,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (user_id, name),
  unique (id, user_id)
);

create table if not exists public.factory_arrivals (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  factory_id bigint not null,
  reference_code text,
  expected_date date not null,
  status text not null check (status in ('예정', '부분입고', '입고완료', '취소')),
  source_channel text not null check (source_channel in ('manual', 'csv')),
  memo text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (id, user_id),
  foreign key (factory_id, user_id) references public.factories (id, user_id) on delete cascade
);

create table if not exists public.factory_arrival_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  factory_arrival_id bigint not null,
  model_id bigint not null,
  size_id bigint not null,
  color_id bigint not null,
  ordered_quantity integer not null check (ordered_quantity > 0),
  received_quantity integer not null default 0 check (received_quantity >= 0),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  foreign key (factory_arrival_id, user_id) references public.factory_arrivals (id, user_id) on delete cascade,
  foreign key (model_id, user_id) references public.models (id, user_id) on delete cascade,
  foreign key (model_id, size_id, user_id) references public.sizes (model_id, id, user_id) on delete cascade,
  foreign key (model_id, color_id, user_id) references public.colors (model_id, id, user_id) on delete cascade
);

create index if not exists models_user_id_created_at_idx on public.models (user_id, created_at desc);
create index if not exists sizes_model_id_user_id_idx on public.sizes (model_id, user_id);
create index if not exists sizes_user_id_sort_order_model_id_name_idx on public.sizes (user_id, sort_order, model_id, name);
create index if not exists colors_model_id_user_id_idx on public.colors (model_id, user_id);
create index if not exists colors_user_id_sort_order_model_id_name_idx on public.colors (user_id, sort_order, model_id, name);
create index if not exists warehouses_user_id_created_at_idx on public.warehouses (user_id, created_at desc);
create unique index if not exists warehouses_id_user_id_uidx on public.warehouses (id, user_id);
create index if not exists inventory_model_id_user_id_idx on public.inventory (model_id, user_id);
create index if not exists inventory_model_id_size_id_user_id_idx on public.inventory (model_id, size_id, user_id);
create index if not exists inventory_model_id_color_id_user_id_idx on public.inventory (model_id, color_id, user_id);
create index if not exists transactions_model_id_user_id_idx on public.transactions (model_id, user_id);
create index if not exists transactions_model_id_size_id_user_id_idx on public.transactions (model_id, size_id, user_id);
create index if not exists transactions_model_id_color_id_user_id_idx on public.transactions (model_id, color_id, user_id);
create index if not exists transactions_user_date_created_at_idx on public.transactions (user_id, date desc, created_at desc);
create index if not exists transactions_reference_type_reference_id_idx on public.transactions (user_id, reference_type, reference_id);
create index if not exists factories_user_id_created_at_idx on public.factories (user_id, created_at desc);
create index if not exists factory_arrivals_user_expected_date_idx on public.factory_arrivals (user_id, expected_date asc, created_at desc);
create index if not exists factory_arrivals_factory_id_user_id_idx on public.factory_arrivals (factory_id, user_id);
create index if not exists factory_arrival_items_arrival_id_user_id_idx on public.factory_arrival_items (factory_arrival_id, user_id);
create index if not exists factory_arrival_items_model_id_user_id_idx on public.factory_arrival_items (model_id, user_id);

-- Channel commerce operations. Kept in sync with supabase/migrations/20260714154633_channel_commerce_operations.sql.
create table if not exists public.product_variants (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  model_id bigint not null,
  size_id bigint not null,
  color_id bigint not null,
  seller_sku text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (id, user_id), unique (user_id, seller_sku), unique (user_id, model_id, size_id, color_id),
  foreign key (model_id, user_id) references public.models (id, user_id) on delete cascade,
  foreign key (model_id, size_id, user_id) references public.sizes (model_id, id, user_id) on delete cascade,
  foreign key (model_id, color_id, user_id) references public.colors (model_id, id, user_id) on delete cascade
);
create table if not exists public.channel_product_refs (
  id bigint generated by default as identity primary key, user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  channel text not null check (channel in ('naver', 'coupang')), external_product_id text not null, external_variant_id text not null, variant_id bigint,
  product_name text, option_name text, seller_sku text, listing_status text not null default 'active', channel_attributes jsonb not null default '{}'::jsonb,
  channel_reported integer, last_synced_at timestamptz, last_sync_error text, sync_target_quantity integer, sync_status text not null default 'idle' check (sync_status in ('idle', 'required', 'failed', 'succeeded')), verification_status text not null default 'unverified' check (verification_status in ('verified', 'unverified')), created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now()),
  unique (id, user_id), unique (user_id, channel, external_product_id, external_variant_id), foreign key (variant_id, user_id) references public.product_variants (id, user_id) on delete set null (variant_id)
);
create table if not exists public.channel_orders (
  id bigint generated by default as identity primary key, user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  channel text not null check (channel in ('naver', 'coupang')), external_order_id text not null, order_status text not null, ordered_at timestamptz, customer_name text, shipping_address text, raw_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now()), unique (id, user_id), unique (user_id, channel, external_order_id)
);
create table if not exists public.channel_order_lines (
  id bigint generated by default as identity primary key, user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  channel_order_id bigint not null, channel text not null check (channel in ('naver', 'coupang')), external_line_id text not null, channel_product_ref_id bigint, variant_id bigint, quantity integer not null check (quantity > 0), line_status text not null, raw_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now()), unique (id, user_id), unique (user_id, channel, external_line_id),
  foreign key (channel_order_id, user_id) references public.channel_orders (id, user_id) on delete cascade, foreign key (channel_product_ref_id, user_id) references public.channel_product_refs (id, user_id) on delete set null (channel_product_ref_id), foreign key (variant_id, user_id) references public.product_variants (id, user_id) on delete set null (variant_id)
);
create table if not exists public.inventory_reservations (
  id bigint generated by default as identity primary key, user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  channel_order_line_id bigint not null, product_variant_id bigint not null, warehouse_id bigint not null, quantity integer not null check (quantity > 0), status text not null default 'active' check (status in ('active', 'released', 'cancelled')), created_at timestamptz not null default timezone('utc', now()), released_at timestamptz,
  unique (id, user_id), foreign key (channel_order_line_id, user_id) references public.channel_order_lines (id, user_id) on delete cascade, foreign key (product_variant_id, user_id) references public.product_variants (id, user_id) on delete cascade, foreign key (warehouse_id, user_id) references public.warehouses (id, user_id) on delete cascade
);
create table if not exists public.inventory_sync_outbox (
  id bigint generated by default as identity primary key, user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  channel_product_ref_id bigint not null, target_quantity integer not null check (target_quantity >= 0), status text not null check (status in ('required', 'failed', 'succeeded')), attempts integer not null default 0 check (attempts >= 0), last_error text, requested_at timestamptz not null default timezone('utc', now()), completed_at timestamptz, created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now()),
  unique (id, user_id), unique (user_id, channel_product_ref_id), foreign key (channel_product_ref_id, user_id) references public.channel_product_refs (id, user_id) on delete cascade
);
create table if not exists public.tracking_import_templates (
  id bigint generated by default as identity primary key, user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  channel text check (channel in ('naver', 'coupang')), name text not null, column_mapping jsonb not null default '{}'::jsonb, created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now()), unique (id, user_id), unique (user_id, channel, name)
);
create table if not exists public.tracking_import_batches (
  id bigint generated by default as identity primary key, user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  tracking_import_template_id bigint, source_filename text not null, status text not null default 'pending', row_count integer not null default 0 check (row_count >= 0), result_summary jsonb not null default '{}'::jsonb, error text, created_at timestamptz not null default timezone('utc', now()), completed_at timestamptz,
  unique (id, user_id), foreign key (tracking_import_template_id, user_id) references public.tracking_import_templates (id, user_id) on delete set null (tracking_import_template_id)
);
create table if not exists public.order_fulfillments (
  id bigint generated by default as identity primary key, user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  channel_order_line_id bigint not null, inventory_reservation_id bigint not null, tracking_import_batch_id bigint, idempotency_key text not null, external_status text not null default 'pending', local_status text not null default 'pending' check (local_status in ('pending', 'fulfilled', 'failed')), tracking_number text, carrier_code text, external_reference text, error text, fulfilled_at timestamptz, created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now()),
  unique (id, user_id), unique (user_id, idempotency_key), foreign key (channel_order_line_id, user_id) references public.channel_order_lines (id, user_id) on delete cascade, foreign key (inventory_reservation_id, user_id) references public.inventory_reservations (id, user_id) on delete cascade, foreign key (tracking_import_batch_id, user_id) references public.tracking_import_batches (id, user_id) on delete set null (tracking_import_batch_id)
);
create index if not exists product_variants_user_id_idx on public.product_variants (user_id);
create index if not exists channel_product_refs_user_id_idx on public.channel_product_refs (user_id);
create index if not exists channel_orders_user_id_idx on public.channel_orders (user_id);
create index if not exists channel_order_lines_user_id_idx on public.channel_order_lines (user_id);
create index if not exists inventory_reservations_user_id_idx on public.inventory_reservations (user_id);
create index if not exists inventory_sync_outbox_user_id_idx on public.inventory_sync_outbox (user_id);
create index if not exists order_fulfillments_user_id_idx on public.order_fulfillments (user_id);
create index if not exists tracking_import_templates_user_id_idx on public.tracking_import_templates (user_id);
create index if not exists tracking_import_batches_user_id_idx on public.tracking_import_batches (user_id);

alter table public.product_variants enable row level security;
alter table public.channel_product_refs enable row level security;
alter table public.channel_orders enable row level security;
alter table public.channel_order_lines enable row level security;
alter table public.inventory_reservations enable row level security;
alter table public.inventory_sync_outbox enable row level security;
alter table public.order_fulfillments enable row level security;
alter table public.tracking_import_templates enable row level security;
alter table public.tracking_import_batches enable row level security;
drop policy if exists "Users manage own product_variants" on public.product_variants;
create policy "Users manage own product_variants" on public.product_variants for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "Users manage own channel_product_refs" on public.channel_product_refs;
create policy "Users manage own channel_product_refs" on public.channel_product_refs for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "Users manage own channel_orders" on public.channel_orders;
create policy "Users manage own channel_orders" on public.channel_orders for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "Users manage own channel_order_lines" on public.channel_order_lines;
create policy "Users manage own channel_order_lines" on public.channel_order_lines for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "Users manage own inventory_reservations" on public.inventory_reservations;
create policy "Users manage own inventory_reservations" on public.inventory_reservations for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "Users manage own inventory_sync_outbox" on public.inventory_sync_outbox;
create policy "Users manage own inventory_sync_outbox" on public.inventory_sync_outbox for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "Users manage own order_fulfillments" on public.order_fulfillments;
create policy "Users manage own order_fulfillments" on public.order_fulfillments for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "Users manage own tracking_import_templates" on public.tracking_import_templates;
create policy "Users manage own tracking_import_templates" on public.tracking_import_templates for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "Users manage own tracking_import_batches" on public.tracking_import_batches;
create policy "Users manage own tracking_import_batches" on public.tracking_import_batches for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

create or replace function public.finalize_order_fulfillment(p_fulfillment_id bigint)
returns boolean
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_fulfillment public.order_fulfillments%rowtype;
  v_reservation public.inventory_reservations%rowtype;
  v_variant public.product_variants%rowtype;
  v_inventory_quantity integer;
begin
  if v_user_id is null then raise exception 'Authentication is required.'; end if;
  select * into v_fulfillment from public.order_fulfillments where id = p_fulfillment_id and user_id = v_user_id for update;
  if not found then raise exception 'Order fulfillment not found.'; end if;
  if v_fulfillment.local_status = 'fulfilled' then return true; end if;
  if v_fulfillment.external_status <> 'success' then raise exception 'External fulfillment has not succeeded.'; end if;
  select * into v_reservation from public.inventory_reservations where id = v_fulfillment.inventory_reservation_id and user_id = v_user_id for update;
  if not found or v_reservation.status <> 'active' then raise exception 'Active inventory reservation not found.'; end if;
  select * into v_variant from public.product_variants where id = v_reservation.product_variant_id and user_id = v_user_id;
  if not found then raise exception 'Product variant not found.'; end if;
  select quantity into v_inventory_quantity from public.inventory where user_id = v_user_id and model_id = v_variant.model_id and size_id = v_variant.size_id and color_id = v_variant.color_id and warehouse_id = v_reservation.warehouse_id for update;
  if not found or v_inventory_quantity < v_reservation.quantity then raise exception 'Insufficient on-hand inventory.'; end if;
  update public.inventory set quantity = quantity - v_reservation.quantity, updated_at = timezone('utc', now()) where user_id = v_user_id and model_id = v_variant.model_id and size_id = v_variant.size_id and color_id = v_variant.color_id and warehouse_id = v_reservation.warehouse_id;
  update public.inventory_reservations set status = 'released', released_at = timezone('utc', now()) where id = v_reservation.id and user_id = v_user_id;
  insert into public.transactions (user_id, date, model_id, size_id, color_id, type, quantity, warehouse_id, source_channel, reference_type, reference_id, memo)
  values (v_user_id, current_date, v_variant.model_id, v_variant.size_id, v_variant.color_id, 'OUTBOUND', v_reservation.quantity, v_reservation.warehouse_id, 'channel-fulfillment', 'order_fulfillment', v_fulfillment.id, coalesce(v_fulfillment.tracking_number, '채널 주문 출고'));
  update public.order_fulfillments set local_status = 'fulfilled', fulfilled_at = timezone('utc', now()), updated_at = timezone('utc', now()), error = null where id = v_fulfillment.id and user_id = v_user_id;
  return true;
end;
$$;
revoke execute on function public.finalize_order_fulfillment(bigint) from public, anon;
grant execute on function public.finalize_order_fulfillment(bigint) to authenticated;

alter table public.app_users enable row level security;
alter table public.models enable row level security;
alter table public.sizes enable row level security;
alter table public.colors enable row level security;
alter table public.warehouses enable row level security;
alter table public.inventory enable row level security;
alter table public.transactions enable row level security;
alter table public.shipping_provider_credentials enable row level security;
alter table public.factories enable row level security;
alter table public.factory_arrivals enable row level security;
alter table public.factory_arrival_items enable row level security;

drop policy if exists "Users can read their own profile" on public.app_users;
create policy "Users can read their own profile"
on public.app_users
for select
to authenticated
using ((select auth.uid()) = id);

drop policy if exists "Users manage own models" on public.models;
create policy "Users manage own models"
on public.models
for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users manage own sizes" on public.sizes;
create policy "Users manage own sizes"
on public.sizes
for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users manage own colors" on public.colors;
create policy "Users manage own colors"
on public.colors
for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users manage own warehouses" on public.warehouses;
create policy "Users manage own warehouses"
on public.warehouses
for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users manage own inventory" on public.inventory;
create policy "Users manage own inventory"
on public.inventory
for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users manage own transactions" on public.transactions;
create policy "Users manage own transactions"
on public.transactions
for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users manage own shipping credentials" on public.shipping_provider_credentials;
create policy "Users manage own shipping credentials"
on public.shipping_provider_credentials
for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users manage own factories" on public.factories;
create policy "Users manage own factories"
on public.factories
for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users manage own factory arrivals" on public.factory_arrivals;
create policy "Users manage own factory arrivals"
on public.factory_arrivals
for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users manage own factory arrival items" on public.factory_arrival_items;
create policy "Users manage own factory arrival items"
on public.factory_arrival_items
for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.app_users (id, email, full_name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name')
  )
  on conflict (id) do update
    set email = excluded.email,
        full_name = coalesce(excluded.full_name, public.app_users.full_name);
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure private.handle_new_user();

create or replace function public.bulk_apply_inventory_transactions(p_items jsonb)
returns void
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  item jsonb;
  v_model_id bigint;
  v_size_id bigint;
  v_color_id bigint;
  v_quantity integer;
  v_date date;
  v_type public.transaction_type_value;
  v_warehouse_id bigint;
  v_inventory_quantity integer;
begin
  if v_user_id is null then
    raise exception 'Authentication is required.';
  end if;

  if jsonb_typeof(p_items) is distinct from 'array' then
    raise exception 'p_items must be a JSON array.';
  end if;

  for item in select * from jsonb_array_elements(p_items)
  loop
    v_model_id := (item ->> 'model_id')::bigint;
    v_size_id := (item ->> 'size_id')::bigint;
    v_color_id := (item ->> 'color_id')::bigint;
    v_quantity := (item ->> 'quantity')::integer;
    v_type := (item ->> 'type')::public.transaction_type_value;
    v_warehouse_id := (item ->> 'warehouse_id')::bigint;

    if (item ->> 'date') ~ '^\d{2}\.\d{2}\.\d{2}$' then
      v_date := to_date(item ->> 'date', 'YY.MM.DD');
    else
      v_date := (item ->> 'date')::date;
    end if;

    if v_quantity is null or v_quantity <= 0 then
      raise exception 'quantity must be greater than zero.';
    end if;

    insert into public.transactions (
      user_id, date, model_id, size_id, color_id, type, quantity, warehouse_id
    )
    values (
      v_user_id, v_date, v_model_id, v_size_id, v_color_id, v_type, v_quantity, v_warehouse_id
    );

    if v_type = 'INBOUND' then
      insert into public.inventory (
        user_id, model_id, size_id, color_id, warehouse_id, quantity
      )
      values (
        v_user_id, v_model_id, v_size_id, v_color_id, v_warehouse_id, v_quantity
      )
      on conflict (user_id, model_id, size_id, color_id, warehouse_id)
      do update
        set quantity = public.inventory.quantity + excluded.quantity,
            updated_at = timezone('utc', now());
    elsif v_type = 'OUTBOUND' then
      select quantity
      into v_inventory_quantity
      from public.inventory
      where user_id = v_user_id
        and model_id = v_model_id
        and size_id = v_size_id
        and color_id = v_color_id
        and warehouse_id = v_warehouse_id
      for update;

      if not found then
        raise exception 'Inventory not found for outbound transaction.';
      end if;

      if v_inventory_quantity < v_quantity then
        raise exception 'Insufficient inventory for outbound transaction.';
      end if;

      update public.inventory
      set quantity = quantity - v_quantity,
          updated_at = timezone('utc', now())
      where user_id = v_user_id
        and model_id = v_model_id
        and size_id = v_size_id
        and color_id = v_color_id
        and warehouse_id = v_warehouse_id;
    else
      insert into public.inventory (
        user_id, model_id, size_id, color_id, warehouse_id, quantity
      )
      values (
        v_user_id, v_model_id, v_size_id, v_color_id, v_warehouse_id, v_quantity
      )
      on conflict (user_id, model_id, size_id, color_id, warehouse_id)
      do update
        set quantity = excluded.quantity,
            updated_at = timezone('utc', now());
    end if;
  end loop;
end;
$$;

create or replace function public.apply_inventory_adjustment(
  p_inventory_id bigint,
  p_new_quantity integer
)
returns void
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_inventory public.inventory%rowtype;
begin
  if v_user_id is null then
    raise exception 'Authentication is required.';
  end if;

  if p_new_quantity < 0 then
    raise exception 'Quantity cannot be negative.';
  end if;

  select *
  into v_inventory
  from public.inventory
  where id = p_inventory_id
    and user_id = v_user_id
  for update;

  if not found then
    raise exception 'Inventory not found.';
  end if;

  update public.inventory
  set quantity = p_new_quantity,
      updated_at = timezone('utc', now())
  where id = p_inventory_id
    and user_id = v_user_id;

  insert into public.transactions (
    user_id, date, model_id, size_id, color_id, type, quantity, warehouse_id
  )
  values (
    v_user_id,
    current_date,
    v_inventory.model_id,
    v_inventory.size_id,
    v_inventory.color_id,
    'ADJUSTMENT',
    p_new_quantity,
    v_inventory.warehouse_id
  );
end;
$$;

-- Manual warehouse operations deliberately use a separate RPC from order
-- fulfillment. This keeps order reservation/release boundaries intact while
-- recording a reasoned warehouse ledger entry and the latest channel target.
alter table public.transactions drop constraint if exists transactions_quantity_check;
alter table public.transactions add constraint transactions_quantity_check
  check (quantity > 0 or type = 'ADJUSTMENT');

create or replace function public.apply_manual_inventory_operations(p_items jsonb)
returns void
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  item jsonb;
  v_kind text;
  v_model_id bigint;
  v_size_id bigint;
  v_color_id bigint;
  v_warehouse_id bigint;
  v_quantity integer;
  v_date date;
  v_reason text;
  v_inventory public.inventory%rowtype;
  v_delta integer;
  v_variant_id bigint;
  v_on_hand integer;
  v_committed integer;
  v_target integer;
  v_ref record;
  v_requested_at timestamptz := timezone('utc', now());
  v_sync_error text := '동기화 필요: 현재 provider는 재고 수량 쓰기를 지원하지 않습니다.';
begin
  if v_user_id is null then
    raise exception 'Authentication is required.';
  end if;
  if jsonb_typeof(p_items) is distinct from 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'p_items must be a non-empty JSON array.';
  end if;

  for item in select * from jsonb_array_elements(p_items)
  loop
    v_kind := item ->> 'kind';
    v_model_id := (item ->> 'model_id')::bigint;
    v_size_id := (item ->> 'size_id')::bigint;
    v_color_id := (item ->> 'color_id')::bigint;
    v_warehouse_id := (item ->> 'warehouse_id')::bigint;
    v_quantity := (item ->> 'quantity')::integer;
    v_reason := btrim(coalesce(item ->> 'reason', ''));
    v_date := (item ->> 'date')::date;

    if v_kind not in ('inbound', 'manual-outbound', 'count-adjustment') then
      raise exception 'Unsupported manual inventory operation.';
    end if;
    if v_reason = '' then
      raise exception 'A reason is required.';
    end if;
    if v_date is null then
      raise exception 'A date is required.';
    end if;
    if v_quantity is null or v_quantity < 0 or (v_kind <> 'count-adjustment' and v_quantity = 0) then
      raise exception 'Quantity is invalid.';
    end if;

    if not exists (select 1 from public.warehouses where id = v_warehouse_id and user_id = v_user_id) then
      raise exception 'Warehouse not found.';
    end if;

    select * into v_inventory
    from public.inventory
    where user_id = v_user_id and model_id = v_model_id and size_id = v_size_id
      and color_id = v_color_id and warehouse_id = v_warehouse_id
    for update;

    if not found and v_kind <> 'inbound' then
      raise exception 'Inventory not found.';
    end if;

    if v_kind = 'inbound' then
      insert into public.inventory (user_id, model_id, size_id, color_id, warehouse_id, quantity)
      values (v_user_id, v_model_id, v_size_id, v_color_id, v_warehouse_id, v_quantity)
      on conflict (user_id, model_id, size_id, color_id, warehouse_id)
      do update set quantity = public.inventory.quantity + excluded.quantity, updated_at = v_requested_at;
      insert into public.transactions (user_id, date, model_id, size_id, color_id, type, quantity, warehouse_id, source_channel, reference_type, memo)
      values (v_user_id, v_date, v_model_id, v_size_id, v_color_id, 'INBOUND', v_quantity, v_warehouse_id, 'manual', 'quick_inbound', v_reason);
    elsif v_kind = 'manual-outbound' then
      if v_inventory.quantity < v_quantity then
        raise exception 'Insufficient on-hand inventory.';
      end if;
      v_delta := -v_quantity;
      update public.inventory set quantity = quantity - v_quantity, updated_at = v_requested_at where id = v_inventory.id;
      insert into public.transactions (user_id, date, model_id, size_id, color_id, type, quantity, warehouse_id, source_channel, reference_type, memo)
      values (v_user_id, v_date, v_model_id, v_size_id, v_color_id, 'OUTBOUND', v_quantity, v_warehouse_id, 'manual', 'manual_outbound', v_reason);
    else
      v_delta := v_quantity - v_inventory.quantity;
      update public.inventory set quantity = v_quantity, updated_at = v_requested_at where id = v_inventory.id;
      insert into public.transactions (user_id, date, model_id, size_id, color_id, type, quantity, warehouse_id, source_channel, reference_type, memo)
      values (v_user_id, v_date, v_model_id, v_size_id, v_color_id, 'ADJUSTMENT', v_delta, v_warehouse_id, 'manual', 'stock_count_adjustment', v_reason);
    end if;

    select id into v_variant_id from public.product_variants
    where user_id = v_user_id and model_id = v_model_id and size_id = v_size_id and color_id = v_color_id;

    if found then
      select coalesce(sum(quantity), 0) into v_on_hand from public.inventory
      where user_id = v_user_id and model_id = v_model_id and size_id = v_size_id and color_id = v_color_id;
      select coalesce(sum(quantity), 0) into v_committed from public.inventory_reservations
      where user_id = v_user_id and product_variant_id = v_variant_id and status = 'active';
      v_target := greatest(0, v_on_hand - v_committed);

      for v_ref in select id from public.channel_product_refs where user_id = v_user_id and variant_id = v_variant_id
      loop
        update public.channel_product_refs set sync_target_quantity = v_target, sync_status = 'required', last_sync_error = v_sync_error, updated_at = v_requested_at
        where id = v_ref.id and user_id = v_user_id;
        insert into public.inventory_sync_outbox (user_id, channel_product_ref_id, target_quantity, status, last_error, requested_at, updated_at)
        values (v_user_id, v_ref.id, v_target, 'required', v_sync_error, v_requested_at, v_requested_at)
        on conflict (user_id, channel_product_ref_id) do update set target_quantity = excluded.target_quantity, status = 'required', last_error = excluded.last_error, requested_at = excluded.requested_at, updated_at = excluded.updated_at;
      end loop;
    end if;
  end loop;
end;
$$;

-- A transfer is intentionally one RPC: PostgreSQL rolls all source, destination,
-- ledger, and outbox writes back together if any invariant fails.
create or replace function public.transfer_inventory_between_warehouses(p_transfer jsonb)
returns void
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_model_id bigint := (p_transfer ->> 'model_id')::bigint;
  v_size_id bigint := (p_transfer ->> 'size_id')::bigint;
  v_color_id bigint := (p_transfer ->> 'color_id')::bigint;
  v_from_warehouse_id bigint := (p_transfer ->> 'from_warehouse_id')::bigint;
  v_to_warehouse_id bigint := (p_transfer ->> 'to_warehouse_id')::bigint;
  v_quantity integer := (p_transfer ->> 'quantity')::integer;
  v_date date := (p_transfer ->> 'date')::date;
  v_reason text := btrim(coalesce(p_transfer ->> 'reason', ''));
  v_source public.inventory%rowtype;
  v_variant_id bigint;
  v_on_hand integer;
  v_committed integer;
  v_target integer;
  v_ref record;
  v_now timestamptz := timezone('utc', now());
  v_sync_error text := '동기화 필요: 현재 provider는 재고 수량 쓰기를 지원하지 않습니다.';
  v_memo text;
begin
  if v_user_id is null then raise exception 'Authentication is required.'; end if;
  if p_transfer is null or jsonb_typeof(p_transfer) <> 'object' then raise exception 'p_transfer must be an object.'; end if;
  if v_model_id is null or v_size_id is null or v_color_id is null or v_from_warehouse_id is null or v_to_warehouse_id is null then raise exception 'Product option and warehouses are required.'; end if;
  if v_from_warehouse_id = v_to_warehouse_id then raise exception 'Source and destination warehouses must differ.'; end if;
  if v_quantity is null or v_quantity <= 0 then raise exception 'Quantity must be greater than zero.'; end if;
  if v_date is null or v_reason = '' then raise exception 'Date and reason are required.'; end if;
  if not exists (select 1 from public.warehouses where id = v_from_warehouse_id and user_id = v_user_id)
    or not exists (select 1 from public.warehouses where id = v_to_warehouse_id and user_id = v_user_id) then raise exception 'Warehouse not found.'; end if;

  select * into v_source from public.inventory where user_id = v_user_id and model_id = v_model_id and size_id = v_size_id and color_id = v_color_id and warehouse_id = v_from_warehouse_id for update;
  if not found or v_source.quantity < v_quantity then raise exception 'Insufficient on-hand inventory.'; end if;

  update public.inventory set quantity = quantity - v_quantity, updated_at = v_now where id = v_source.id;
  insert into public.inventory (user_id, model_id, size_id, color_id, warehouse_id, quantity)
  values (v_user_id, v_model_id, v_size_id, v_color_id, v_to_warehouse_id, v_quantity)
  on conflict (user_id, model_id, size_id, color_id, warehouse_id) do update set quantity = public.inventory.quantity + excluded.quantity, updated_at = v_now;

  v_memo := format('창고 이동: %s → %s / %s', v_from_warehouse_id, v_to_warehouse_id, v_reason);
  insert into public.transactions (user_id, date, model_id, size_id, color_id, type, quantity, warehouse_id, source_channel, reference_type, memo)
  values
    (v_user_id, v_date, v_model_id, v_size_id, v_color_id, 'OUTBOUND', v_quantity, v_from_warehouse_id, 'manual', 'warehouse_transfer_outbound', v_memo),
    (v_user_id, v_date, v_model_id, v_size_id, v_color_id, 'INBOUND', v_quantity, v_to_warehouse_id, 'manual', 'warehouse_transfer_inbound', v_memo);

  select id into v_variant_id from public.product_variants where user_id = v_user_id and model_id = v_model_id and size_id = v_size_id and color_id = v_color_id;
  if found then
    select coalesce(sum(quantity), 0) into v_on_hand from public.inventory where user_id = v_user_id and model_id = v_model_id and size_id = v_size_id and color_id = v_color_id;
    select coalesce(sum(quantity), 0) into v_committed from public.inventory_reservations where user_id = v_user_id and product_variant_id = v_variant_id and status = 'active';
    v_target := greatest(0, v_on_hand - v_committed);
    for v_ref in select id from public.channel_product_refs where user_id = v_user_id and variant_id = v_variant_id loop
      update public.channel_product_refs set sync_target_quantity = v_target, sync_status = 'required', last_sync_error = v_sync_error, updated_at = v_now where id = v_ref.id and user_id = v_user_id;
      insert into public.inventory_sync_outbox (user_id, channel_product_ref_id, target_quantity, status, last_error, requested_at, updated_at)
      values (v_user_id, v_ref.id, v_target, 'required', v_sync_error, v_now, v_now)
      on conflict (user_id, channel_product_ref_id) do update set target_quantity = excluded.target_quantity, status = 'required', last_error = excluded.last_error, requested_at = excluded.requested_at, updated_at = excluded.updated_at;
    end loop;
  end if;
end;
$$;

create or replace function public.revert_inventory_transaction(
  p_transaction_id bigint,
  p_memo text default null
)
returns bigint
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_transaction public.transactions%rowtype;
  v_previous public.transactions%rowtype;
  v_new_type public.transaction_type_value;
  v_new_quantity integer;
  v_current_quantity integer;
  v_running_quantity integer := 0;
  v_new_transaction_id bigint;
  v_normalized_memo text := nullif(btrim(p_memo), '');
begin
  if v_user_id is null then
    raise exception 'Authentication is required.';
  end if;

  select *
  into v_transaction
  from public.transactions
  where id = p_transaction_id
    and user_id = v_user_id
  for update;

  if not found then
    raise exception 'Transaction not found.';
  end if;

  if v_transaction.type not in ('INBOUND', 'OUTBOUND', 'ADJUSTMENT') then
    raise exception 'Unsupported transaction type.';
  end if;

  if v_transaction.source_channel = 'csv' then
    raise exception 'CSV 반영 이력은 되돌릴 수 없습니다.';
  end if;

  if v_transaction.source_channel = 'factory-arrival' then
    raise exception '예정입고 반영 이력은 되돌릴 수 없습니다.';
  end if;

  if v_transaction.reference_type is not null or v_transaction.reference_id is not null then
    raise exception '이미 시스템 참조가 있는 행은 되돌릴 수 없습니다.';
  end if;

  if v_transaction.source_channel is not null and v_transaction.source_channel <> 'manual' then
    raise exception '수동 등록 이력만 되돌릴 수 있습니다.';
  end if;

  if exists (
    select 1
    from public.transactions newer
    where newer.user_id = v_user_id
      and newer.model_id = v_transaction.model_id
      and newer.size_id = v_transaction.size_id
      and newer.color_id = v_transaction.color_id
      and newer.warehouse_id = v_transaction.warehouse_id
      and (
        newer.date > v_transaction.date
        or (newer.date = v_transaction.date and newer.created_at > v_transaction.created_at)
        or (
          newer.date = v_transaction.date
          and newer.created_at = v_transaction.created_at
          and newer.id > v_transaction.id
        )
      )
  ) then
    raise exception '후속 이력 있음';
  end if;

  if v_transaction.type = 'INBOUND' then
    v_new_type := 'OUTBOUND';
    v_new_quantity := v_transaction.quantity;

    select quantity
    into v_current_quantity
    from public.inventory
    where user_id = v_user_id
      and model_id = v_transaction.model_id
      and size_id = v_transaction.size_id
      and color_id = v_transaction.color_id
      and warehouse_id = v_transaction.warehouse_id
    for update;

    if not found then
      raise exception 'Inventory not found for inbound revert.';
    end if;

    if v_current_quantity < v_new_quantity then
      raise exception 'Insufficient inventory to revert inbound transaction.';
    end if;

    update public.inventory
    set quantity = quantity - v_new_quantity,
        updated_at = timezone('utc', now())
    where user_id = v_user_id
      and model_id = v_transaction.model_id
      and size_id = v_transaction.size_id
      and color_id = v_transaction.color_id
      and warehouse_id = v_transaction.warehouse_id;
  elsif v_transaction.type = 'OUTBOUND' then
    v_new_type := 'INBOUND';
    v_new_quantity := v_transaction.quantity;

    insert into public.inventory (
      user_id, model_id, size_id, color_id, warehouse_id, quantity
    )
    values (
      v_user_id,
      v_transaction.model_id,
      v_transaction.size_id,
      v_transaction.color_id,
      v_transaction.warehouse_id,
      v_new_quantity
    )
    on conflict (user_id, model_id, size_id, color_id, warehouse_id)
    do update
      set quantity = public.inventory.quantity + excluded.quantity,
          updated_at = timezone('utc', now());
  else
    v_new_type := 'ADJUSTMENT';

    for v_previous in
      select *
      from public.transactions prior
      where prior.user_id = v_user_id
        and prior.model_id = v_transaction.model_id
        and prior.size_id = v_transaction.size_id
        and prior.color_id = v_transaction.color_id
        and prior.warehouse_id = v_transaction.warehouse_id
        and (
          prior.date < v_transaction.date
          or (prior.date = v_transaction.date and prior.created_at < v_transaction.created_at)
          or (
            prior.date = v_transaction.date
            and prior.created_at = v_transaction.created_at
            and prior.id < v_transaction.id
          )
        )
      order by prior.date asc, prior.created_at asc, prior.id asc
    loop
      if v_previous.type = 'INBOUND' then
        v_running_quantity := v_running_quantity + v_previous.quantity;
      elsif v_previous.type = 'OUTBOUND' then
        v_running_quantity := greatest(v_running_quantity - v_previous.quantity, 0);
      else
        v_running_quantity := v_previous.quantity;
      end if;
    end loop;

    v_new_quantity := v_running_quantity;

    insert into public.inventory (
      user_id, model_id, size_id, color_id, warehouse_id, quantity
    )
    values (
      v_user_id,
      v_transaction.model_id,
      v_transaction.size_id,
      v_transaction.color_id,
      v_transaction.warehouse_id,
      v_new_quantity
    )
    on conflict (user_id, model_id, size_id, color_id, warehouse_id)
    do update
      set quantity = excluded.quantity,
          updated_at = timezone('utc', now());
  end if;

  insert into public.transactions (
    user_id,
    date,
    model_id,
    size_id,
    color_id,
    type,
    quantity,
    warehouse_id,
    source_channel,
    reference_type,
    reference_id,
    memo
  )
  values (
    v_user_id,
    current_date,
    v_transaction.model_id,
    v_transaction.size_id,
    v_transaction.color_id,
    v_new_type,
    v_new_quantity,
    v_transaction.warehouse_id,
    'history-revert',
    'transaction_revert',
    v_transaction.id,
    coalesce(v_normalized_memo, '이력 되돌리기')
  )
  returning id into v_new_transaction_id;

  return v_new_transaction_id;
end;
$$;

create or replace function public.receive_factory_arrival(
  p_arrival_id bigint,
  p_warehouse_id bigint,
  p_items jsonb
)
returns void
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_item jsonb;
  v_arrival public.factory_arrivals%rowtype;
  v_arrival_item public.factory_arrival_items%rowtype;
  v_model_id bigint;
  v_size_id bigint;
  v_color_id bigint;
  v_quantity integer;
  v_remaining integer;
  v_total_remaining integer;
begin
  if v_user_id is null then
    raise exception 'Authentication is required.';
  end if;

  select *
  into v_arrival
  from public.factory_arrivals
  where id = p_arrival_id
    and user_id = v_user_id
  for update;

  if not found then
    raise exception 'Factory arrival not found.';
  end if;

  if v_arrival.status = '입고완료' or v_arrival.status = '취소' then
    raise exception 'This arrival cannot be received.';
  end if;

  if jsonb_typeof(p_items) is distinct from 'array' then
    raise exception 'p_items must be a JSON array.';
  end if;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    select *
    into v_arrival_item
    from public.factory_arrival_items
    where id = (v_item ->> 'arrival_item_id')::bigint
      and factory_arrival_id = p_arrival_id
      and user_id = v_user_id
    for update;

    if not found then
      raise exception 'Factory arrival item not found.';
    end if;

    v_quantity := (v_item ->> 'quantity')::integer;
    v_remaining := v_arrival_item.ordered_quantity - v_arrival_item.received_quantity;

    if v_quantity is null or v_quantity <= 0 then
      raise exception 'Receive quantity must be greater than zero.';
    end if;

    if v_quantity > v_remaining then
      raise exception 'Receive quantity exceeds remaining quantity.';
    end if;

    v_model_id := v_arrival_item.model_id;
    v_size_id := v_arrival_item.size_id;
    v_color_id := v_arrival_item.color_id;

    update public.factory_arrival_items
    set received_quantity = received_quantity + v_quantity,
        updated_at = timezone('utc', now())
    where id = v_arrival_item.id
      and user_id = v_user_id;

    insert into public.inventory (
      user_id, model_id, size_id, color_id, warehouse_id, quantity
    )
    values (
      v_user_id, v_model_id, v_size_id, v_color_id, p_warehouse_id, v_quantity
    )
    on conflict (user_id, model_id, size_id, color_id, warehouse_id)
    do update
      set quantity = public.inventory.quantity + excluded.quantity,
          updated_at = timezone('utc', now());

    insert into public.transactions (
      user_id, date, model_id, size_id, color_id, type, quantity, warehouse_id, source_channel, reference_type, reference_id, memo
    )
    values (
      v_user_id,
      current_date,
      v_model_id,
      v_size_id,
      v_color_id,
      'INBOUND',
      v_quantity,
      p_warehouse_id,
      'factory-arrival',
      'factory_arrival',
      p_arrival_id,
      coalesce(v_arrival.memo, '공장 예정 입고 반영')
    );
  end loop;

  select coalesce(sum(ordered_quantity - received_quantity), 0)
  into v_total_remaining
  from public.factory_arrival_items
  where factory_arrival_id = p_arrival_id
    and user_id = v_user_id;

  update public.factory_arrivals
  set status = case
      when v_total_remaining = 0 then '입고완료'
      else '부분입고'
    end,
    updated_at = timezone('utc', now())
  where id = p_arrival_id
    and user_id = v_user_id;
end;
$$;

-- Manual inbound drafts keep supplier references separate from inspected stock.
-- A supplier SKU link is created only after a matched row has been received.
create table if not exists public.inbound_templates (
  id bigint generated by default as identity primary key, user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null, is_active boolean not null default true, created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now()), unique (id, user_id), unique (user_id, name)
);
create table if not exists public.inbound_template_versions (
  id bigint generated by default as identity primary key, user_id uuid not null default auth.uid() references auth.users(id) on delete cascade, template_id bigint not null,
  version_number integer not null check (version_number > 0), sheet_name text not null, header_row_number integer not null check (header_row_number > 0), headers jsonb not null, mappings jsonb not null,
  created_at timestamptz not null default timezone('utc', now()), unique (id, user_id), unique (template_id, version_number), foreign key (template_id, user_id) references public.inbound_templates(id, user_id) on delete restrict
);
create table if not exists public.inbound_drafts (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  supplier_id bigint not null,
  template_id bigint,
  template_version_id bigint,
  source_storage_path text,
  source_filename text,
  source_file_hash text,
  source_sheet_name text,
  source_header_row_number integer,
  source_headers jsonb,
  status text not null default 'draft' check (status in ('draft', 'partial', 'received')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (id, user_id),
  foreign key (supplier_id, user_id) references public.factories (id, user_id) on delete restrict
  , foreign key (template_id, user_id) references public.inbound_templates(id, user_id) on delete restrict
  , foreign key (template_version_id, user_id) references public.inbound_template_versions(id, user_id) on delete restrict
);

create table if not exists public.inbound_draft_rows (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  inbound_draft_id bigint not null,
  template text not null,
  template_id bigint,
  external_sku text not null,
  quantity integer check (quantity > 0),
  received_quantity integer not null default 0 check (received_quantity >= 0 and received_quantity <= quantity),
  warehouse_id bigint not null,
  product_variant_id bigint,
  source_row_number integer,
  source_values jsonb not null default '{}'::jsonb,
  validation_error text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (id, user_id),
  foreign key (inbound_draft_id, user_id) references public.inbound_drafts (id, user_id) on delete cascade,
  foreign key (warehouse_id, user_id) references public.warehouses (id, user_id) on delete restrict,
  foreign key (product_variant_id, user_id) references public.product_variants (id, user_id) on delete set null
  , foreign key (template_id, user_id) references public.inbound_templates(id, user_id) on delete restrict
);

create table if not exists public.supplier_sku_links (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  supplier_id bigint not null,
  template text not null,
  template_id bigint,
  external_sku text not null,
  product_variant_id bigint not null,
  received_at timestamptz not null default timezone('utc', now()),
  unique (user_id, supplier_id, template, external_sku),
  foreign key (supplier_id, user_id) references public.factories (id, user_id) on delete cascade,
  foreign key (product_variant_id, user_id) references public.product_variants (id, user_id) on delete cascade
  , foreign key (template_id, user_id) references public.inbound_templates(id, user_id) on delete restrict
);

create index if not exists inbound_drafts_user_id_idx on public.inbound_drafts (user_id, created_at desc);
create index if not exists inbound_draft_rows_draft_user_id_idx on public.inbound_draft_rows (inbound_draft_id, user_id);
create index if not exists supplier_sku_links_exact_idx on public.supplier_sku_links (user_id, supplier_id, template, external_sku);
alter table public.inbound_drafts enable row level security;
alter table public.inbound_templates enable row level security;
alter table public.inbound_template_versions enable row level security;
alter table public.inbound_draft_rows enable row level security;
alter table public.supplier_sku_links enable row level security;
drop policy if exists "Users manage own inbound_drafts" on public.inbound_drafts;
create policy "Users manage own inbound_drafts" on public.inbound_drafts for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "Users manage own inbound_templates" on public.inbound_templates;
create policy "Users manage own inbound_templates" on public.inbound_templates for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "Users manage own inbound_template_versions" on public.inbound_template_versions;
create policy "Users manage own inbound_template_versions" on public.inbound_template_versions for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "Users manage own inbound_draft_rows" on public.inbound_draft_rows;
create policy "Users manage own inbound_draft_rows" on public.inbound_draft_rows for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "Users manage own supplier_sku_links" on public.supplier_sku_links;
create policy "Users manage own supplier_sku_links" on public.supplier_sku_links for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
insert into storage.buckets (id, name, public) values ('inbound-source-files', 'inbound-source-files', false) on conflict (id) do update set public = false;

create or replace function public.receive_inbound_draft_rows(p_draft_id bigint, p_rows jsonb)
returns void language plpgsql security invoker set search_path = '' as $$
declare
  v_user_id uuid := auth.uid(); v_row jsonb; v_draft public.inbound_drafts%rowtype; v_item public.inbound_draft_rows%rowtype;
  v_variant public.product_variants%rowtype; v_quantity integer; v_remaining integer; v_open integer;
begin
  if v_user_id is null then raise exception 'Authentication is required.'; end if;
  if jsonb_typeof(p_rows) is distinct from 'array' then raise exception 'p_rows must be a JSON array.'; end if;
  select * into v_draft from public.inbound_drafts where id = p_draft_id and user_id = v_user_id for update;
  if not found or v_draft.status = 'received' then raise exception 'Inbound draft cannot be received.'; end if;
  for v_row in select * from jsonb_array_elements(p_rows) loop
    select * into v_item from public.inbound_draft_rows where id = (v_row ->> 'row_id')::bigint and inbound_draft_id = p_draft_id and user_id = v_user_id for update;
    if not found then raise exception 'Inbound draft row not found.'; end if;
    if v_item.product_variant_id is null then raise exception 'Unmatched inbound rows cannot be received.'; end if;
    v_quantity := (v_row ->> 'quantity')::integer; v_remaining := v_item.quantity - v_item.received_quantity;
    if v_quantity is null or v_quantity <= 0 or v_quantity > v_remaining then raise exception 'Receive quantity is invalid.'; end if;
    select * into v_variant from public.product_variants where id = v_item.product_variant_id and user_id = v_user_id;
    if not found then raise exception 'Assigned internal SKU not found.'; end if;
    update public.inbound_draft_rows set received_quantity = received_quantity + v_quantity, updated_at = timezone('utc', now()) where id = v_item.id;
    insert into public.inventory (user_id, model_id, size_id, color_id, warehouse_id, quantity) values (v_user_id, v_variant.model_id, v_variant.size_id, v_variant.color_id, v_item.warehouse_id, v_quantity)
      on conflict (user_id, model_id, size_id, color_id, warehouse_id) do update set quantity = public.inventory.quantity + excluded.quantity, updated_at = timezone('utc', now());
    insert into public.transactions (user_id, date, model_id, size_id, color_id, type, quantity, warehouse_id, source_channel, reference_type, reference_id, memo)
      values (v_user_id, current_date, v_variant.model_id, v_variant.size_id, v_variant.color_id, 'INBOUND', v_quantity, v_item.warehouse_id, 'inbound-draft', 'inbound_draft_row', v_item.id, '검수 입고');
    insert into public.supplier_sku_links (user_id, supplier_id, template, external_sku, product_variant_id, received_at) values (v_user_id, v_draft.supplier_id, v_item.template, v_item.external_sku, v_item.product_variant_id, timezone('utc', now()))
      on conflict (user_id, supplier_id, template, external_sku) do update set product_variant_id = excluded.product_variant_id, received_at = excluded.received_at;
    insert into public.inventory_sync_outbox (user_id, channel_product_ref_id, target_quantity, status, last_error, requested_at, updated_at)
      select v_user_id, ref.id, greatest(coalesce(sum(inv.quantity), 0) - coalesce((select sum(quantity) from public.inventory_reservations where user_id = v_user_id and product_variant_id = v_variant.id and status = 'active'), 0), 0), 'required', '동기화 필요: 현재 provider는 재고 수량 쓰기를 지원하지 않습니다.', timezone('utc', now()), timezone('utc', now())
      from public.channel_product_refs ref left join public.inventory inv on inv.user_id = v_user_id and inv.model_id = v_variant.model_id and inv.size_id = v_variant.size_id and inv.color_id = v_variant.color_id
      where ref.user_id = v_user_id and ref.variant_id = v_variant.id group by ref.id
      on conflict (user_id, channel_product_ref_id) do update set target_quantity = excluded.target_quantity, status = 'required', last_error = excluded.last_error, requested_at = excluded.requested_at, updated_at = excluded.updated_at;
  end loop;
  select count(*) into v_open from public.inbound_draft_rows where inbound_draft_id = p_draft_id and user_id = v_user_id and received_quantity < quantity;
  update public.inbound_drafts set status = case when v_open = 0 then 'received' else 'partial' end, updated_at = timezone('utc', now()) where id = p_draft_id and user_id = v_user_id;
end;
$$;
