create extension if not exists pgcrypto;

create schema if not exists private;

do $$
begin
  create type public.transaction_type_value as enum ('INBOUND', 'OUTBOUND', 'ADJUSTMENT');
exception
  when duplicate_object then null;
end $$;

create table if not exists public.app_users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique,
  full_name text,
  role text not null default 'manager',
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.models (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default timezone('utc', now()),
  unique (id, user_id),
  unique (user_id, name)
);

create table if not exists public.sizes (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  model_id bigint not null,
  name text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  unique (model_id, id, user_id),
  unique (user_id, model_id, name),
  foreign key (model_id, user_id) references public.models (id, user_id) on delete cascade
);

create table if not exists public.colors (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  model_id bigint not null,
  name text not null,
  rgb_code text not null,
  text_white boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  unique (model_id, id, user_id),
  unique (user_id, model_id, name),
  foreign key (model_id, user_id) references public.models (id, user_id) on delete cascade
);

create table if not exists public.warehouses (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default timezone('utc', now()),
  unique (user_id, name)
);

create table if not exists public.inventory (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  model_id bigint not null,
  size_id bigint not null,
  color_id bigint not null,
  warehouse_id bigint not null references public.warehouses (id) on delete cascade,
  quantity integer not null default 0 check (quantity >= 0),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (user_id, model_id, size_id, color_id, warehouse_id),
  foreign key (model_id, user_id) references public.models (id, user_id) on delete cascade,
  foreign key (model_id, size_id, user_id) references public.sizes (model_id, id, user_id) on delete cascade,
  foreign key (model_id, color_id, user_id) references public.colors (model_id, id, user_id) on delete cascade
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  date date not null,
  model_id bigint not null,
  size_id bigint not null,
  color_id bigint not null,
  type public.transaction_type_value not null,
  quantity integer not null check (quantity > 0),
  warehouse_id bigint not null references public.warehouses (id) on delete cascade,
  source_channel text,
  reference_type text,
  reference_id bigint,
  memo text,
  created_at timestamptz not null default timezone('utc', now()),
  foreign key (model_id, user_id) references public.models (id, user_id) on delete cascade,
  foreign key (model_id, size_id, user_id) references public.sizes (model_id, id, user_id) on delete cascade,
  foreign key (model_id, color_id, user_id) references public.colors (model_id, id, user_id) on delete cascade
);

create table if not exists public.shipping_provider_credentials (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  provider text not null check (provider in ('naver', 'coupang')),
  encrypted_payload text not null,
  iv text not null,
  auth_tag text not null,
  key_version smallint not null default 1,
  masked_summary jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (user_id, provider)
);

create table if not exists public.factories (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null,
  contact_name text,
  phone text,
  email text,
  notes text,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (user_id, name),
  unique (id, user_id)
);

create table if not exists public.factory_arrivals (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  factory_id bigint not null,
  reference_code text,
  expected_date date not null,
  status text not null check (status in ('예정', '부분입고', '입고완료', '취소')),
  source_channel text not null check (source_channel in ('manual', 'csv')),
  memo text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (id, user_id),
  foreign key (factory_id, user_id) references public.factories (id, user_id) on delete cascade
);

create table if not exists public.factory_arrival_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  factory_arrival_id bigint not null,
  model_id bigint not null,
  size_id bigint not null,
  color_id bigint not null,
  ordered_quantity integer not null check (ordered_quantity > 0),
  received_quantity integer not null default 0 check (received_quantity >= 0),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  foreign key (factory_arrival_id, user_id) references public.factory_arrivals (id, user_id) on delete cascade,
  foreign key (model_id, user_id) references public.models (id, user_id) on delete cascade,
  foreign key (model_id, size_id, user_id) references public.sizes (model_id, id, user_id) on delete cascade,
  foreign key (model_id, color_id, user_id) references public.colors (model_id, id, user_id) on delete cascade
);

create index if not exists models_user_id_created_at_idx on public.models (user_id, created_at desc);
create index if not exists sizes_model_id_user_id_idx on public.sizes (model_id, user_id);
create index if not exists sizes_user_id_sort_order_model_id_name_idx on public.sizes (user_id, sort_order, model_id, name);
create index if not exists colors_model_id_user_id_idx on public.colors (model_id, user_id);
create index if not exists colors_user_id_sort_order_model_id_name_idx on public.colors (user_id, sort_order, model_id, name);
create index if not exists warehouses_user_id_created_at_idx on public.warehouses (user_id, created_at desc);
create unique index if not exists warehouses_id_user_id_uidx on public.warehouses (id, user_id);
create index if not exists inventory_model_id_user_id_idx on public.inventory (model_id, user_id);
create index if not exists inventory_model_id_size_id_user_id_idx on public.inventory (model_id, size_id, user_id);
create index if not exists inventory_model_id_color_id_user_id_idx on public.inventory (model_id, color_id, user_id);
create index if not exists transactions_model_id_user_id_idx on public.transactions (model_id, user_id);
create index if not exists transactions_model_id_size_id_user_id_idx on public.transactions (model_id, size_id, user_id);
create index if not exists transactions_model_id_color_id_user_id_idx on public.transactions (model_id, color_id, user_id);
create index if not exists transactions_user_date_created_at_idx on public.transactions (user_id, date desc, created_at desc);
create index if not exists transactions_reference_type_reference_id_idx on public.transactions (user_id, reference_type, reference_id);
create index if not exists factories_user_id_created_at_idx on public.factories (user_id, created_at desc);
create index if not exists factory_arrivals_user_expected_date_idx on public.factory_arrivals (user_id, expected_date asc, created_at desc);
create index if not exists factory_arrivals_factory_id_user_id_idx on public.factory_arrivals (factory_id, user_id);
create index if not exists factory_arrival_items_arrival_id_user_id_idx on public.factory_arrival_items (factory_arrival_id, user_id);
create index if not exists factory_arrival_items_model_id_user_id_idx on public.factory_arrival_items (model_id, user_id);

alter table public.app_users enable row level security;
alter table public.models enable row level security;
alter table public.sizes enable row level security;
alter table public.colors enable row level security;
alter table public.warehouses enable row level security;
alter table public.inventory enable row level security;
alter table public.transactions enable row level security;
alter table public.shipping_provider_credentials enable row level security;
alter table public.factories enable row level security;
alter table public.factory_arrivals enable row level security;
alter table public.factory_arrival_items enable row level security;

drop policy if exists "Users can read their own profile" on public.app_users;
create policy "Users can read their own profile"
on public.app_users
for select
to authenticated
using ((select auth.uid()) = id);

drop policy if exists "Users manage own models" on public.models;
create policy "Users manage own models"
on public.models
for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users manage own sizes" on public.sizes;
create policy "Users manage own sizes"
on public.sizes
for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users manage own colors" on public.colors;
create policy "Users manage own colors"
on public.colors
for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users manage own warehouses" on public.warehouses;
create policy "Users manage own warehouses"
on public.warehouses
for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users manage own inventory" on public.inventory;
create policy "Users manage own inventory"
on public.inventory
for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users manage own transactions" on public.transactions;
create policy "Users manage own transactions"
on public.transactions
for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users manage own shipping credentials" on public.shipping_provider_credentials;
create policy "Users manage own shipping credentials"
on public.shipping_provider_credentials
for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users manage own factories" on public.factories;
create policy "Users manage own factories"
on public.factories
for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users manage own factory arrivals" on public.factory_arrivals;
create policy "Users manage own factory arrivals"
on public.factory_arrivals
for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users manage own factory arrival items" on public.factory_arrival_items;
create policy "Users manage own factory arrival items"
on public.factory_arrival_items
for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.app_users (id, email, full_name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name')
  )
  on conflict (id) do update
    set email = excluded.email,
        full_name = coalesce(excluded.full_name, public.app_users.full_name);
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure private.handle_new_user();

create or replace function public.bulk_apply_inventory_transactions(p_items jsonb)
returns void
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  item jsonb;
  v_model_id bigint;
  v_size_id bigint;
  v_color_id bigint;
  v_quantity integer;
  v_date date;
  v_type public.transaction_type_value;
  v_warehouse_id bigint;
  v_inventory_quantity integer;
begin
  if v_user_id is null then
    raise exception 'Authentication is required.';
  end if;

  if jsonb_typeof(p_items) is distinct from 'array' then
    raise exception 'p_items must be a JSON array.';
  end if;

  for item in select * from jsonb_array_elements(p_items)
  loop
    v_model_id := (item ->> 'model_id')::bigint;
    v_size_id := (item ->> 'size_id')::bigint;
    v_color_id := (item ->> 'color_id')::bigint;
    v_quantity := (item ->> 'quantity')::integer;
    v_type := (item ->> 'type')::public.transaction_type_value;
    v_warehouse_id := (item ->> 'warehouse_id')::bigint;

    if (item ->> 'date') ~ '^\d{2}\.\d{2}\.\d{2}$' then
      v_date := to_date(item ->> 'date', 'YY.MM.DD');
    else
      v_date := (item ->> 'date')::date;
    end if;

    if v_quantity is null or v_quantity <= 0 then
      raise exception 'quantity must be greater than zero.';
    end if;

    insert into public.transactions (
      user_id, date, model_id, size_id, color_id, type, quantity, warehouse_id
    )
    values (
      v_user_id, v_date, v_model_id, v_size_id, v_color_id, v_type, v_quantity, v_warehouse_id
    );

    if v_type = 'INBOUND' then
      insert into public.inventory (
        user_id, model_id, size_id, color_id, warehouse_id, quantity
      )
      values (
        v_user_id, v_model_id, v_size_id, v_color_id, v_warehouse_id, v_quantity
      )
      on conflict (user_id, model_id, size_id, color_id, warehouse_id)
      do update
        set quantity = public.inventory.quantity + excluded.quantity,
            updated_at = timezone('utc', now());
    elsif v_type = 'OUTBOUND' then
      select quantity
      into v_inventory_quantity
      from public.inventory
      where user_id = v_user_id
        and model_id = v_model_id
        and size_id = v_size_id
        and color_id = v_color_id
        and warehouse_id = v_warehouse_id
      for update;

      if not found then
        raise exception 'Inventory not found for outbound transaction.';
      end if;

      if v_inventory_quantity < v_quantity then
        raise exception 'Insufficient inventory for outbound transaction.';
      end if;

      update public.inventory
      set quantity = quantity - v_quantity,
          updated_at = timezone('utc', now())
      where user_id = v_user_id
        and model_id = v_model_id
        and size_id = v_size_id
        and color_id = v_color_id
        and warehouse_id = v_warehouse_id;
    else
      insert into public.inventory (
        user_id, model_id, size_id, color_id, warehouse_id, quantity
      )
      values (
        v_user_id, v_model_id, v_size_id, v_color_id, v_warehouse_id, v_quantity
      )
      on conflict (user_id, model_id, size_id, color_id, warehouse_id)
      do update
        set quantity = excluded.quantity,
            updated_at = timezone('utc', now());
    end if;
  end loop;
end;
$$;

create or replace function public.apply_inventory_adjustment(
  p_inventory_id bigint,
  p_new_quantity integer
)
returns void
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_inventory public.inventory%rowtype;
begin
  if v_user_id is null then
    raise exception 'Authentication is required.';
  end if;

  if p_new_quantity < 0 then
    raise exception 'Quantity cannot be negative.';
  end if;

  select *
  into v_inventory
  from public.inventory
  where id = p_inventory_id
    and user_id = v_user_id
  for update;

  if not found then
    raise exception 'Inventory not found.';
  end if;

  update public.inventory
  set quantity = p_new_quantity,
      updated_at = timezone('utc', now())
  where id = p_inventory_id
    and user_id = v_user_id;

  insert into public.transactions (
    user_id, date, model_id, size_id, color_id, type, quantity, warehouse_id
  )
  values (
    v_user_id,
    current_date,
    v_inventory.model_id,
    v_inventory.size_id,
    v_inventory.color_id,
    'ADJUSTMENT',
    p_new_quantity,
    v_inventory.warehouse_id
  );
end;
$$;

create or replace function public.revert_inventory_transaction(
  p_transaction_id bigint,
  p_memo text default null
)
returns bigint
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_transaction public.transactions%rowtype;
  v_previous public.transactions%rowtype;
  v_new_type public.transaction_type_value;
  v_new_quantity integer;
  v_current_quantity integer;
  v_running_quantity integer := 0;
  v_new_transaction_id bigint;
  v_normalized_memo text := nullif(btrim(p_memo), '');
begin
  if v_user_id is null then
    raise exception 'Authentication is required.';
  end if;

  select *
  into v_transaction
  from public.transactions
  where id = p_transaction_id
    and user_id = v_user_id
  for update;

  if not found then
    raise exception 'Transaction not found.';
  end if;

  if v_transaction.type not in ('INBOUND', 'OUTBOUND', 'ADJUSTMENT') then
    raise exception 'Unsupported transaction type.';
  end if;

  if v_transaction.source_channel = 'csv' then
    raise exception 'CSV 반영 이력은 되돌릴 수 없습니다.';
  end if;

  if v_transaction.source_channel = 'factory-arrival' then
    raise exception '예정입고 반영 이력은 되돌릴 수 없습니다.';
  end if;

  if v_transaction.reference_type is not null or v_transaction.reference_id is not null then
    raise exception '이미 시스템 참조가 있는 행은 되돌릴 수 없습니다.';
  end if;

  if v_transaction.source_channel is not null and v_transaction.source_channel <> 'manual' then
    raise exception '수동 등록 이력만 되돌릴 수 있습니다.';
  end if;

  if exists (
    select 1
    from public.transactions newer
    where newer.user_id = v_user_id
      and newer.model_id = v_transaction.model_id
      and newer.size_id = v_transaction.size_id
      and newer.color_id = v_transaction.color_id
      and newer.warehouse_id = v_transaction.warehouse_id
      and (
        newer.date > v_transaction.date
        or (newer.date = v_transaction.date and newer.created_at > v_transaction.created_at)
        or (
          newer.date = v_transaction.date
          and newer.created_at = v_transaction.created_at
          and newer.id > v_transaction.id
        )
      )
  ) then
    raise exception '후속 이력 있음';
  end if;

  if v_transaction.type = 'INBOUND' then
    v_new_type := 'OUTBOUND';
    v_new_quantity := v_transaction.quantity;

    select quantity
    into v_current_quantity
    from public.inventory
    where user_id = v_user_id
      and model_id = v_transaction.model_id
      and size_id = v_transaction.size_id
      and color_id = v_transaction.color_id
      and warehouse_id = v_transaction.warehouse_id
    for update;

    if not found then
      raise exception 'Inventory not found for inbound revert.';
    end if;

    if v_current_quantity < v_new_quantity then
      raise exception 'Insufficient inventory to revert inbound transaction.';
    end if;

    update public.inventory
    set quantity = quantity - v_new_quantity,
        updated_at = timezone('utc', now())
    where user_id = v_user_id
      and model_id = v_transaction.model_id
      and size_id = v_transaction.size_id
      and color_id = v_transaction.color_id
      and warehouse_id = v_transaction.warehouse_id;
  elsif v_transaction.type = 'OUTBOUND' then
    v_new_type := 'INBOUND';
    v_new_quantity := v_transaction.quantity;

    insert into public.inventory (
      user_id, model_id, size_id, color_id, warehouse_id, quantity
    )
    values (
      v_user_id,
      v_transaction.model_id,
      v_transaction.size_id,
      v_transaction.color_id,
      v_transaction.warehouse_id,
      v_new_quantity
    )
    on conflict (user_id, model_id, size_id, color_id, warehouse_id)
    do update
      set quantity = public.inventory.quantity + excluded.quantity,
          updated_at = timezone('utc', now());
  else
    v_new_type := 'ADJUSTMENT';

    for v_previous in
      select *
      from public.transactions prior
      where prior.user_id = v_user_id
        and prior.model_id = v_transaction.model_id
        and prior.size_id = v_transaction.size_id
        and prior.color_id = v_transaction.color_id
        and prior.warehouse_id = v_transaction.warehouse_id
        and (
          prior.date < v_transaction.date
          or (prior.date = v_transaction.date and prior.created_at < v_transaction.created_at)
          or (
            prior.date = v_transaction.date
            and prior.created_at = v_transaction.created_at
            and prior.id < v_transaction.id
          )
        )
      order by prior.date asc, prior.created_at asc, prior.id asc
    loop
      if v_previous.type = 'INBOUND' then
        v_running_quantity := v_running_quantity + v_previous.quantity;
      elsif v_previous.type = 'OUTBOUND' then
        v_running_quantity := greatest(v_running_quantity - v_previous.quantity, 0);
      else
        v_running_quantity := v_previous.quantity;
      end if;
    end loop;

    v_new_quantity := v_running_quantity;

    insert into public.inventory (
      user_id, model_id, size_id, color_id, warehouse_id, quantity
    )
    values (
      v_user_id,
      v_transaction.model_id,
      v_transaction.size_id,
      v_transaction.color_id,
      v_transaction.warehouse_id,
      v_new_quantity
    )
    on conflict (user_id, model_id, size_id, color_id, warehouse_id)
    do update
      set quantity = excluded.quantity,
          updated_at = timezone('utc', now());
  end if;

  insert into public.transactions (
    user_id,
    date,
    model_id,
    size_id,
    color_id,
    type,
    quantity,
    warehouse_id,
    source_channel,
    reference_type,
    reference_id,
    memo
  )
  values (
    v_user_id,
    current_date,
    v_transaction.model_id,
    v_transaction.size_id,
    v_transaction.color_id,
    v_new_type,
    v_new_quantity,
    v_transaction.warehouse_id,
    'history-revert',
    'transaction_revert',
    v_transaction.id,
    coalesce(v_normalized_memo, '이력 되돌리기')
  )
  returning id into v_new_transaction_id;

  return v_new_transaction_id;
end;
$$;

create or replace function public.receive_factory_arrival(
  p_arrival_id bigint,
  p_warehouse_id bigint,
  p_items jsonb
)
returns void
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_item jsonb;
  v_arrival public.factory_arrivals%rowtype;
  v_arrival_item public.factory_arrival_items%rowtype;
  v_model_id bigint;
  v_size_id bigint;
  v_color_id bigint;
  v_quantity integer;
  v_remaining integer;
  v_total_remaining integer;
begin
  if v_user_id is null then
    raise exception 'Authentication is required.';
  end if;

  select *
  into v_arrival
  from public.factory_arrivals
  where id = p_arrival_id
    and user_id = v_user_id
  for update;

  if not found then
    raise exception 'Factory arrival not found.';
  end if;

  if v_arrival.status = '입고완료' or v_arrival.status = '취소' then
    raise exception 'This arrival cannot be received.';
  end if;

  if jsonb_typeof(p_items) is distinct from 'array' then
    raise exception 'p_items must be a JSON array.';
  end if;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    select *
    into v_arrival_item
    from public.factory_arrival_items
    where id = (v_item ->> 'arrival_item_id')::bigint
      and factory_arrival_id = p_arrival_id
      and user_id = v_user_id
    for update;

    if not found then
      raise exception 'Factory arrival item not found.';
    end if;

    v_quantity := (v_item ->> 'quantity')::integer;
    v_remaining := v_arrival_item.ordered_quantity - v_arrival_item.received_quantity;

    if v_quantity is null or v_quantity <= 0 then
      raise exception 'Receive quantity must be greater than zero.';
    end if;

    if v_quantity > v_remaining then
      raise exception 'Receive quantity exceeds remaining quantity.';
    end if;

    v_model_id := v_arrival_item.model_id;
    v_size_id := v_arrival_item.size_id;
    v_color_id := v_arrival_item.color_id;

    update public.factory_arrival_items
    set received_quantity = received_quantity + v_quantity,
        updated_at = timezone('utc', now())
    where id = v_arrival_item.id
      and user_id = v_user_id;

    insert into public.inventory (
      user_id, model_id, size_id, color_id, warehouse_id, quantity
    )
    values (
      v_user_id, v_model_id, v_size_id, v_color_id, p_warehouse_id, v_quantity
    )
    on conflict (user_id, model_id, size_id, color_id, warehouse_id)
    do update
      set quantity = public.inventory.quantity + excluded.quantity,
          updated_at = timezone('utc', now());

    insert into public.transactions (
      user_id, date, model_id, size_id, color_id, type, quantity, warehouse_id, source_channel, reference_type, reference_id, memo
    )
    values (
      v_user_id,
      current_date,
      v_model_id,
      v_size_id,
      v_color_id,
      'INBOUND',
      v_quantity,
      p_warehouse_id,
      'factory-arrival',
      'factory_arrival',
      p_arrival_id,
      coalesce(v_arrival.memo, '공장 예정 입고 반영')
    );
  end loop;

  select coalesce(sum(ordered_quantity - received_quantity), 0)
  into v_total_remaining
  from public.factory_arrival_items
  where factory_arrival_id = p_arrival_id
    and user_id = v_user_id;

  update public.factory_arrivals
  set status = case
      when v_total_remaining = 0 then '입고완료'
      else '부분입고'
    end,
    updated_at = timezone('utc', now())
  where id = p_arrival_id
    and user_id = v_user_id;
end;
$$;
