create table if not exists public.warehouses (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default timezone('utc', now()),
  unique (user_id, name)
);

create index if not exists warehouses_user_id_created_at_idx on public.warehouses (user_id, created_at desc);
create unique index if not exists warehouses_id_user_id_uidx on public.warehouses (id, user_id);

insert into public.warehouses (user_id, name)
select distinct i.user_id, '오금동'
from public.inventory i
where i.warehouse = 'OGEUMDONG'
and not exists (
  select 1 from public.warehouses w
  where w.user_id = i.user_id and w.name = '오금동'
);

insert into public.warehouses (user_id, name)
select distinct i.user_id, '대자동'
from public.inventory i
where i.warehouse = 'DAEJADONG'
and not exists (
  select 1 from public.warehouses w
  where w.user_id = i.user_id and w.name = '대자동'
);

insert into public.warehouses (user_id, name)
select distinct t.user_id, '오금동'
from public.transactions t
where t.warehouse = 'OGEUMDONG'
and not exists (
  select 1 from public.warehouses w
  where w.user_id = t.user_id and w.name = '오금동'
);

insert into public.warehouses (user_id, name)
select distinct t.user_id, '대자동'
from public.transactions t
where t.warehouse = 'DAEJADONG'
and not exists (
  select 1 from public.warehouses w
  where w.user_id = t.user_id and w.name = '대자동'
);

alter table public.inventory add column if not exists warehouse_id bigint;
alter table public.transactions add column if not exists warehouse_id bigint;

update public.inventory i
set warehouse_id = w.id
from public.warehouses w
where i.user_id = w.user_id
  and ((i.warehouse = 'OGEUMDONG' and w.name = '오금동') or (i.warehouse = 'DAEJADONG' and w.name = '대자동'));

update public.transactions t
set warehouse_id = w.id
from public.warehouses w
where t.user_id = w.user_id
  and ((t.warehouse = 'OGEUMDONG' and w.name = '오금동') or (t.warehouse = 'DAEJADONG' and w.name = '대자동'));

create index if not exists inventory_warehouse_id_idx on public.inventory (user_id, warehouse_id);
create index if not exists transactions_warehouse_id_idx on public.transactions (user_id, warehouse_id);

alter table public.inventory
  alter column warehouse_id set not null;

alter table public.transactions
  alter column warehouse_id set not null;

alter table public.inventory
  add constraint inventory_user_id_warehouse_id_fk
  foreign key (warehouse_id, user_id) references public.warehouses (id, user_id) on delete restrict;

alter table public.transactions
  add constraint transactions_user_id_warehouse_id_fk
  foreign key (warehouse_id, user_id) references public.warehouses (id, user_id) on delete restrict;

alter table public.inventory drop column warehouse;
alter table public.transactions drop column warehouse;

drop type if exists public.warehouse_value;

create or replace function public.bulk_apply_inventory_transactions(p_items jsonb)
returns void
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  item jsonb;
  v_model_id bigint;
  v_size_id bigint;
  v_color_id bigint;
  v_quantity integer;
  v_date date;
  v_type public.transaction_type_value;
  v_warehouse_id bigint;
  v_inventory_quantity integer;
  v_warehouse_text text;
begin
  if v_user_id is null then
    raise exception 'Authentication is required.';
  end if;

  if jsonb_typeof(p_items) is distinct from 'array' then
    raise exception 'p_items must be a JSON array.';
  end if;

  for item in select * from jsonb_array_elements(p_items)
  loop
    v_model_id := (item ->> 'model_id')::bigint;
    v_size_id := (item ->> 'size_id')::bigint;
    v_color_id := (item ->> 'color_id')::bigint;
    v_quantity := (item ->> 'quantity')::integer;
    v_type := (item ->> 'type')::public.transaction_type_value;
    v_warehouse_id := nullif((item ->> 'warehouse_id'), '')::bigint;
    v_warehouse_text := item ->> 'warehouse';

    if v_warehouse_id is null and v_warehouse_text is not null then
      select id
      into v_warehouse_id
      from public.warehouses
      where user_id = v_user_id
        and name = case
          when v_warehouse_text = 'OGEUMDONG' then '오금동'
          when v_warehouse_text = 'DAEJADONG' then '대자동'
          when v_warehouse_text = '오금동' then '오금동'
          when v_warehouse_text = '대자동' then '대자동'
          else null
        end
      limit 1;
    end if;

    if (item ->> 'date') ~ '^\d{2}\.\d{2}\.\d{2}$' then
      v_date := to_date(item ->> 'date', 'YY.MM.DD');
    else
      v_date := (item ->> 'date')::date;
    end if;

    if v_quantity is null or v_quantity <= 0 then
      raise exception 'quantity must be greater than zero.';
    end if;

    if v_warehouse_id is null then
      raise exception 'warehouse_id is required.';
    end if;

    insert into public.transactions (
      user_id, date, model_id, size_id, color_id, type, quantity, warehouse_id
    )
    values (
      v_user_id, v_date, v_model_id, v_size_id, v_color_id, v_type, v_quantity, v_warehouse_id
    );

    if v_type = 'INBOUND' then
      insert into public.inventory (
        user_id, model_id, size_id, color_id, warehouse_id, quantity
      )
      values (
        v_user_id, v_model_id, v_size_id, v_color_id, v_warehouse_id, v_quantity
      )
      on conflict (user_id, model_id, size_id, color_id, warehouse_id)
      do update
        set quantity = public.inventory.quantity + excluded.quantity,
            updated_at = timezone('utc', now());
    elsif v_type = 'OUTBOUND' then
      select quantity
      into v_inventory_quantity
      from public.inventory
      where user_id = v_user_id
        and model_id = v_model_id
        and size_id = v_size_id
        and color_id = v_color_id
        and warehouse_id = v_warehouse_id
      for update;

      if not found then
        raise exception 'Inventory not found for outbound transaction.';
      end if;

      if v_inventory_quantity < v_quantity then
        raise exception 'Insufficient inventory for outbound transaction.';
      end if;

      update public.inventory
      set quantity = quantity - v_quantity,
          updated_at = timezone('utc', now())
      where user_id = v_user_id
        and model_id = v_model_id
        and size_id = v_size_id
        and color_id = v_color_id
        and warehouse_id = v_warehouse_id;
    else
      insert into public.inventory (
        user_id, model_id, size_id, color_id, warehouse_id, quantity
      )
      values (
        v_user_id, v_model_id, v_size_id, v_color_id, v_warehouse_id, v_quantity
      )
      on conflict (user_id, model_id, size_id, color_id, warehouse_id)
      do update
        set quantity = excluded.quantity,
            updated_at = timezone('utc', now());
    end if;
  end loop;
end;
$$;

create or replace function public.apply_inventory_adjustment(
  p_inventory_id bigint,
  p_new_quantity integer
)
returns void
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_inventory public.inventory%rowtype;
begin
  if v_user_id is null then
    raise exception 'Authentication is required.';
  end if;

  if p_new_quantity < 0 then
    raise exception 'Quantity cannot be negative.';
  end if;

  select *
  into v_inventory
  from public.inventory
  where id = p_inventory_id
    and user_id = v_user_id
  for update;

  if not found then
    raise exception 'Inventory not found.';
  end if;

  update public.inventory
  set quantity = p_new_quantity,
      updated_at = timezone('utc', now())
  where id = p_inventory_id
    and user_id = v_user_id;

  insert into public.transactions (
    user_id, date, model_id, size_id, color_id, type, quantity, warehouse_id
  )
  values (
    v_user_id,
    current_date,
    v_inventory.model_id,
    v_inventory.size_id,
    v_inventory.color_id,
    'ADJUSTMENT',
    p_new_quantity,
    v_inventory.warehouse_id
  );
end;
$$;

alter table public.warehouses enable row level security;

drop policy if exists "Users manage own warehouses" on public.warehouses;
create policy "Users manage own warehouses"
on public.warehouses
for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);
