create table if not exists public.factories (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null,
  contact_name text,
  phone text,
  email text,
  notes text,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (user_id, name),
  unique (id, user_id)
);

create table if not exists public.factory_arrivals (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  factory_id bigint not null,
  reference_code text,
  expected_date date not null,
  status text not null check (status in ('예정', '부분입고', '입고완료', '취소')),
  source_channel text not null check (source_channel in ('manual', 'csv')),
  memo text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (id, user_id),
  foreign key (factory_id, user_id) references public.factories (id, user_id) on delete cascade
);

create table if not exists public.factory_arrival_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  factory_arrival_id bigint not null,
  model_id bigint not null,
  size_id bigint not null,
  color_id bigint not null,
  ordered_quantity integer not null check (ordered_quantity > 0),
  received_quantity integer not null default 0 check (received_quantity >= 0),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  foreign key (factory_arrival_id, user_id) references public.factory_arrivals (id, user_id) on delete cascade,
  foreign key (model_id, user_id) references public.models (id, user_id) on delete cascade,
  foreign key (model_id, size_id, user_id) references public.sizes (model_id, id, user_id) on delete cascade,
  foreign key (model_id, color_id, user_id) references public.colors (model_id, id, user_id) on delete cascade
);

create index if not exists factories_user_id_created_at_idx on public.factories (user_id, created_at desc);
create index if not exists factory_arrivals_user_expected_date_idx on public.factory_arrivals (user_id, expected_date asc, created_at desc);
create index if not exists factory_arrivals_factory_id_user_id_idx on public.factory_arrivals (factory_id, user_id);
create index if not exists factory_arrival_items_arrival_id_user_id_idx on public.factory_arrival_items (factory_arrival_id, user_id);
create index if not exists factory_arrival_items_model_id_user_id_idx on public.factory_arrival_items (model_id, user_id);

alter table public.factories enable row level security;
alter table public.factory_arrivals enable row level security;
alter table public.factory_arrival_items enable row level security;

drop policy if exists "Users manage own factories" on public.factories;
create policy "Users manage own factories"
on public.factories
for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users manage own factory arrivals" on public.factory_arrivals;
create policy "Users manage own factory arrivals"
on public.factory_arrivals
for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists "Users manage own factory arrival items" on public.factory_arrival_items;
create policy "Users manage own factory arrival items"
on public.factory_arrival_items
for all
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);
