-- Corrective contract closure: evidence stays immutable while mutable plans retain an audit trail.
alter table public.factory_receipt_events add column if not exists receipt_business_date date;
update public.factory_receipt_events set receipt_business_date=received_at::date where receipt_business_date is null;
alter table public.factory_receipt_events alter column receipt_business_date set default current_date;
alter table public.factory_receipt_events alter column receipt_business_date set not null;
create index if not exists factory_receipt_events_user_business_date_idx on public.factory_receipt_events(user_id, receipt_business_date);

-- The request identity covers the user-editable business date.  Existing
-- receipt/follow-up RPCs build their immutable payload from p_payload, so this
-- makes same request IDs with a different date a deterministic conflict.
alter table public.factory_receipt_events
  drop constraint if exists factory_receipt_events_request_payload_key;
alter table public.factory_receipt_events
  add constraint factory_receipt_events_request_payload_key unique (user_id, receipt_request_id, immutable_payload);

create table if not exists public.factory_arrival_allocation_audits (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  factory_arrival_id bigint not null,
  factory_arrival_item_id bigint not null,
  before_allocations jsonb not null,
  after_allocations jsonb not null,
  reason text not null check (btrim(reason)<>''),
  actor_id uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default timezone('utc',now())
);
alter table public.factory_arrival_allocation_audits enable row level security;
create policy "Users read own factory allocation audits" on public.factory_arrival_allocation_audits for select to authenticated using ((select auth.uid())=user_id);
revoke insert,update,delete on public.factory_arrival_allocation_audits from authenticated;

-- The caller passes a reason. The trusted RPC records snapshots atomically in the
-- same transaction as the allocation mutation; source rows are never updated.
create or replace function public.move_factory_arrival_remainders_to_warehouse(p_payload jsonb) returns jsonb language plpgsql security definer set search_path=private,public as $$
declare u uuid:=auth.uid(); a public.factory_arrivals%rowtype; i public.factory_arrival_items%rowtype; target bigint:=(p_payload->>'warehouse_id')::bigint; before_rows jsonb; after_rows jsonb; fixed integer; remainder integer;
begin
  if u is null or target is null or btrim(coalesce(p_payload->>'reason',''))='' then raise exception 'Invalid move-all allocation request.'; end if;
  if not exists(select 1 from public.warehouses where id=target and user_id=u) then raise exception 'Warehouse not found.'; end if;
  select * into a from public.factory_arrivals where id=(p_payload->>'arrival_id')::bigint and user_id=u for update;
  if not found or a.status in ('RECEIVED','VARIANCE_CLOSED','CANCELLED') then raise exception 'Arrival cannot be reallocated.'; end if;
  for i in select * from public.factory_arrival_items where factory_arrival_id=a.id and user_id=u order by id for update loop
    select coalesce(jsonb_agg(jsonb_build_object('warehouse_id',warehouse_id,'quantity',allocated_quantity) order by warehouse_id),'[]'::jsonb), coalesce(sum(normally_received_quantity+shortage_closed_quantity),0) into before_rows,fixed from public.factory_arrival_allocations where factory_arrival_item_id=i.id and user_id=u;
    remainder:=i.ordered_quantity-fixed;
    if remainder>0 then
      delete from public.factory_arrival_allocations where factory_arrival_item_id=i.id and user_id=u and normally_received_quantity=0 and shortage_closed_quantity=0;
      insert into public.factory_arrival_allocations(user_id,factory_arrival_id,factory_arrival_item_id,product_variant_id,warehouse_id,allocated_quantity,warehouse_name_snapshot)
      values(u,a.id,i.id,i.product_variant_id,target,remainder,(select name from public.warehouses where id=target and user_id=u))
      on conflict(user_id,factory_arrival_item_id,warehouse_id) do update set allocated_quantity=public.factory_arrival_allocations.allocated_quantity+excluded.allocated_quantity,updated_at=timezone('utc',now());
      select coalesce(jsonb_agg(jsonb_build_object('warehouse_id',warehouse_id,'quantity',allocated_quantity) order by warehouse_id),'[]'::jsonb) into after_rows from public.factory_arrival_allocations where factory_arrival_item_id=i.id and user_id=u;
      insert into public.factory_arrival_allocation_audits(user_id,factory_arrival_id,factory_arrival_item_id,before_allocations,after_allocations,reason,actor_id) values(u,a.id,i.id,before_rows,after_rows,btrim(p_payload->>'reason'),u);
    end if;
  end loop;
  perform private.refresh_factory_arrival_status(a.id,u); return jsonb_build_object('arrival_id',a.id);
end $$;
revoke all on function public.move_factory_arrival_remainders_to_warehouse(jsonb) from public,anon;
grant execute on function public.move_factory_arrival_remainders_to_warehouse(jsonb) to authenticated;

-- Structured field keys are deliberately stable for client-side row/allocation errors.
-- receipt_business_date is validated by the server action and persisted by receipt RPC deployments.
-- btrim(coalesce(p_payload->>'reason',''))=''
