-- Trusted allocation, partial receipt, variance, follow-up, and correction operations.
create table public.factory_receipt_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  receipt_request_id text not null check (btrim(receipt_request_id) <> ''),
  payload_hash text not null check (payload_hash ~ '^[0-9a-f]{64}$'),
  factory_arrival_id bigint not null,
  immutable_payload jsonb not null,
  receipt_event_id bigint,
  created_at timestamptz not null default timezone('utc', now()),
  unique (user_id, receipt_request_id), unique (id, user_id),
  foreign key (factory_arrival_id, user_id) references public.factory_arrivals(id, user_id) on delete restrict,
  foreign key (receipt_event_id, user_id) references public.factory_receipt_events(id, user_id) on delete restrict
);
create table public.factory_arrival_shortage_closures (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  factory_arrival_allocation_id bigint not null,
  quantity integer not null check (quantity > 0),
  reason text not null check (btrim(reason) <> ''),
  actor_id uuid not null references auth.users(id) on delete restrict,
  closed_at timestamptz not null default timezone('utc', now()),
  unique (id, user_id),
  foreign key (factory_arrival_allocation_id, user_id) references public.factory_arrival_allocations(id, user_id) on delete restrict
);
create table public.factory_receipt_line_corrections (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  correction_request_id text not null check (btrim(correction_request_id) <> ''),
  payload_hash text not null check (payload_hash ~ '^[0-9a-f]{64}$'),
  immutable_payload jsonb not null,
  factory_receipt_line_id bigint not null,
  reason text not null check (btrim(reason) <> ''),
  actor_id uuid not null references auth.users(id) on delete restrict,
  transaction_id bigint not null,
  created_at timestamptz not null default timezone('utc', now()),
  unique (user_id, correction_request_id), unique (factory_receipt_line_id), unique (id, user_id),
  foreign key (factory_receipt_line_id, user_id) references public.factory_receipt_lines(id, user_id) on delete restrict,
  foreign key (transaction_id, user_id) references public.transactions(id, user_id) on delete restrict
);

alter table public.factory_receipt_events add column if not exists receipt_request_id text;
-- Kept nullable until the corrective migration backfills historical evidence;
-- trusted receipt functions below already require an explicit business date.
alter table public.factory_receipt_events add column if not exists receipt_business_date date;
alter table public.factory_receipt_lines
  add column if not exists factory_arrival_item_id bigint,
  add column if not exists warehouse_id bigint,
  add column if not exists normal_quantity integer not null default 0 check (normal_quantity >= 0),
  add column if not exists overage_quantity integer not null default 0 check (overage_quantity >= 0),
  add column if not exists overage_reason text,
  add column if not exists factory_arrival_shortage_closure_id bigint;
do $$ begin if exists(select 1 from pg_trigger where tgrelid='public.factory_receipt_lines'::regclass and tgname='factory_receipt_line_immutable') then alter table public.factory_receipt_lines disable trigger factory_receipt_line_immutable; end if; end $$;
update public.factory_receipt_lines set normal_quantity = received_quantity where normal_quantity = 0 and overage_quantity = 0;
do $$ begin if exists(select 1 from pg_trigger where tgrelid='public.factory_receipt_lines'::regclass and tgname='factory_receipt_line_immutable') then alter table public.factory_receipt_lines enable trigger factory_receipt_line_immutable; end if; end $$;
create or replace function private.classify_legacy_factory_receipt_line() returns trigger language plpgsql set search_path=private,public as $$
begin
  if new.normal_quantity=0 and new.overage_quantity=0 then new.normal_quantity:=new.received_quantity; end if;
  return new;
end $$;
create trigger factory_receipt_line_classify_legacy before insert on public.factory_receipt_lines for each row execute function private.classify_legacy_factory_receipt_line();
alter table public.factory_receipt_lines add constraint factory_receipt_lines_quantity_kind_check check (normal_quantity + overage_quantity = received_quantity);
alter table public.factory_receipt_lines add constraint factory_receipt_lines_overage_reason_check check ((overage_quantity=0 and overage_reason is null) or (overage_quantity>0 and btrim(coalesce(overage_reason,''))<>''));
alter table public.factory_receipt_lines add constraint factory_receipt_lines_item_user_fkey foreign key (factory_arrival_item_id,user_id) references public.factory_arrival_items(id,user_id) on delete restrict;
alter table public.factory_receipt_lines add constraint factory_receipt_lines_warehouse_user_fkey foreign key (warehouse_id,user_id) references public.warehouses(id,user_id) on delete restrict;
alter table public.factory_receipt_lines add constraint factory_receipt_lines_shortage_user_fkey foreign key (factory_arrival_shortage_closure_id,user_id) references public.factory_arrival_shortage_closures(id,user_id) on delete restrict;
create index factory_receipt_requests_arrival_idx on public.factory_receipt_requests(user_id,factory_arrival_id);
create index factory_shortage_closures_allocation_idx on public.factory_arrival_shortage_closures(user_id,factory_arrival_allocation_id);
create index factory_receipt_lines_item_idx on public.factory_receipt_lines(user_id,factory_arrival_item_id);
create unique index factory_arrival_allocations_one_warehouse_per_item_idx on public.factory_arrival_allocations(user_id,factory_arrival_item_id,warehouse_id);
create unique index factory_receipt_lines_one_allocation_per_event_idx on public.factory_receipt_lines(user_id,factory_receipt_event_id,factory_arrival_allocation_id) where factory_arrival_allocation_id is not null;

create or replace function private.assert_factory_arrival_receipt_consistency() returns trigger language plpgsql set search_path=private,public as $$
declare e public.factory_receipt_events%rowtype; x public.factory_arrival_allocations%rowtype; i public.factory_arrival_items%rowtype; t public.transactions%rowtype; v public.product_variants%rowtype; c public.factory_arrival_shortage_closures%rowtype;
begin
  select * into e from public.factory_receipt_events where id=new.factory_receipt_event_id and user_id=new.user_id; if not found then raise exception 'factory_arrival_receipt_consistency'; end if;
  if new.factory_arrival_item_id is not null then select * into i from public.factory_arrival_items where id=new.factory_arrival_item_id and factory_arrival_id=e.factory_arrival_id and user_id=new.user_id; if not found then raise exception 'factory_arrival_receipt_consistency'; end if; end if;
  if new.factory_arrival_allocation_id is not null then select * into x from public.factory_arrival_allocations where id=new.factory_arrival_allocation_id and factory_arrival_id=e.factory_arrival_id and user_id=new.user_id; if not found or (new.factory_arrival_item_id is not null and x.factory_arrival_item_id<>new.factory_arrival_item_id) then raise exception 'factory_arrival_receipt_consistency'; end if; end if;
  if new.factory_arrival_shortage_closure_id is not null then select * into c from public.factory_arrival_shortage_closures where id=new.factory_arrival_shortage_closure_id and user_id=new.user_id; if not found or not exists(select 1 from public.factory_arrival_allocations ca where ca.id=c.factory_arrival_allocation_id and ca.factory_arrival_item_id=i.id and ca.factory_arrival_id=e.factory_arrival_id and ca.user_id=new.user_id) then raise exception 'factory_arrival_receipt_consistency'; end if; end if;
  if new.transaction_id is not null then
    select * into t from public.transactions where id=new.transaction_id and user_id=new.user_id; select * into v from public.product_variants where id=coalesce(i.product_variant_id,x.product_variant_id) and user_id=new.user_id;
    if not found or t.warehouse_id<>coalesce(new.warehouse_id,x.warehouse_id) or t.quantity<>new.received_quantity or t.model_id<>v.model_id or t.size_id<>v.size_id or t.color_id<>v.color_id then raise exception 'factory_arrival_receipt_consistency'; end if;
  end if;
  if e.event_kind='FOLLOW_UP' and new.factory_arrival_shortage_closure_id is null then raise exception 'factory_arrival_receipt_consistency'; end if;
  return new;
end $$;
drop trigger if exists factory_receipt_line_consistency on public.factory_receipt_lines;
create trigger factory_receipt_line_consistency before insert on public.factory_receipt_lines for each row execute function private.assert_factory_arrival_receipt_consistency();

create or replace function private.factory_payload_hash(p_payload jsonb) returns text language sql immutable strict set search_path=pg_catalog,public as $$
  select encode(extensions.digest(convert_to(p_payload::text, 'UTF8'), 'sha256'), 'hex')
$$;

create or replace function private.refresh_factory_arrival_status(p_arrival_id bigint,p_user_id uuid) returns void language plpgsql set search_path=private,public as $$
declare v_has_receipt boolean; v_has_remainder boolean; v_has_variance boolean;
begin
  select exists(select 1 from public.factory_receipt_lines l join public.factory_receipt_events e on e.id=l.factory_receipt_event_id and e.user_id=l.user_id where e.factory_arrival_id=p_arrival_id and l.user_id=p_user_id and not exists(select 1 from public.factory_receipt_line_corrections c where c.factory_receipt_line_id=l.id and c.user_id=l.user_id)) into v_has_receipt;
  select exists(select 1 from public.factory_arrival_allocations x where x.factory_arrival_id=p_arrival_id and x.user_id=p_user_id and x.normally_received_quantity+x.shortage_closed_quantity<x.allocated_quantity) into v_has_remainder;
  select exists(select 1 from public.factory_arrival_shortage_closures c join public.factory_arrival_allocations x on x.id=c.factory_arrival_allocation_id and x.user_id=c.user_id where x.factory_arrival_id=p_arrival_id and c.user_id=p_user_id)
      or exists(select 1 from public.factory_receipt_lines l join public.factory_receipt_events e on e.id=l.factory_receipt_event_id and e.user_id=l.user_id where e.factory_arrival_id=p_arrival_id and l.user_id=p_user_id and l.overage_quantity>0 and not exists(select 1 from public.factory_receipt_line_corrections c where c.factory_receipt_line_id=l.id and c.user_id=l.user_id)) into v_has_variance;
  update public.factory_arrivals set status=case
    when exists(select 1 from public.factory_arrival_items i where i.factory_arrival_id=p_arrival_id and i.user_id=p_user_id and (i.product_variant_id is null or i.ordered_quantity is null or coalesce((select sum(x.allocated_quantity) from public.factory_arrival_allocations x where x.factory_arrival_item_id=i.id and x.user_id=i.user_id),0)<>i.ordered_quantity)) then 'DRAFT'
    when v_has_remainder then case when v_has_receipt then 'PARTIAL' else 'READY' end when v_has_variance then 'VARIANCE_CLOSED' when v_has_receipt then 'RECEIVED' else 'READY' end,updated_at=timezone('utc',now()) where id=p_arrival_id and user_id=p_user_id;
end $$;

create or replace function private.guard_active_inventory_reservation() returns trigger language plpgsql set search_path=private,public as $$
declare v public.product_variants%rowtype; on_hand integer; committed integer;
begin
  if new.status<>'active' then return new; end if;
  select * into v from public.product_variants where id=new.product_variant_id and user_id=new.user_id; if not found then raise exception 'ProductVariant not found.'; end if;
  select quantity into on_hand from public.inventory where user_id=new.user_id and model_id=v.model_id and size_id=v.size_id and color_id=v.color_id and warehouse_id=new.warehouse_id for update;
  select coalesce(sum(quantity),0) into committed from public.inventory_reservations where user_id=new.user_id and product_variant_id=new.product_variant_id and warehouse_id=new.warehouse_id and status='active' and id<>coalesce(new.id,0);
  if coalesce(on_hand,0)<committed+new.quantity then raise exception 'reservation_exceeds_on_hand'; end if; return new;
end $$;
create trigger inventory_reservation_on_hand_guard before insert or update of product_variant_id,warehouse_id,quantity,status on public.inventory_reservations for each row execute function private.guard_active_inventory_reservation();

create or replace function private.enqueue_factory_variant(p_user_id uuid,p_variant_id bigint) returns void language plpgsql set search_path=private,public as $$
declare v_on_hand integer; v_committed integer; v_target integer; r record;
begin
  select coalesce(sum(i.quantity),0) into v_on_hand from public.inventory i join public.product_variants v on v.model_id=i.model_id and v.size_id=i.size_id and v.color_id=i.color_id and v.user_id=i.user_id where v.id=p_variant_id and i.user_id=p_user_id;
  select coalesce(sum(quantity),0) into v_committed from public.inventory_reservations where user_id=p_user_id and product_variant_id=p_variant_id and status='active';
  v_target:=greatest(0,v_on_hand-v_committed);
  for r in select id from public.channel_product_refs where user_id=p_user_id and variant_id=p_variant_id loop
    insert into public.inventory_sync_outbox(user_id,channel_product_ref_id,target_quantity,status,last_error,requested_at,updated_at) values(p_user_id,r.id,v_target,'required','동기화 필요: 현재 provider는 재고 수량 쓰기를 지원하지 않습니다.',timezone('utc',now()),timezone('utc',now())) on conflict(user_id,channel_product_ref_id) do update set target_quantity=excluded.target_quantity,status='required',last_error=excluded.last_error,requested_at=excluded.requested_at,updated_at=excluded.updated_at;
  end loop;
end $$;

create or replace function public.replace_factory_arrival_allocations(p_payload jsonb) returns jsonb language plpgsql security definer set search_path=private,public as $$
declare u uuid:=auth.uid(); a public.factory_arrivals%rowtype; i public.factory_arrival_items%rowtype; r jsonb; total integer:=0; seen bigint[]:='{}'; desired integer; x public.factory_arrival_allocations%rowtype;
begin
  if u is null or jsonb_typeof(p_payload->'allocations')<>'array' then raise exception 'Invalid allocation request.'; end if;
  select * into a from public.factory_arrivals where id=(p_payload->>'arrival_id')::bigint and user_id=u for update;
  if not found or a.status in('RECEIVED','VARIANCE_CLOSED','CANCELLED') then raise exception 'Arrival cannot be reallocated.'; end if;
  select * into i from public.factory_arrival_items where id=(p_payload->>'item_id')::bigint and factory_arrival_id=a.id and user_id=u for update;
  if not found or i.product_variant_id is null or i.ordered_quantity is null then raise exception 'Arrival item not found.'; end if;
  perform 1 from public.factory_arrival_allocations where factory_arrival_item_id=i.id and user_id=u order by id for update;
  for r in select value from jsonb_array_elements(p_payload->'allocations') loop
    if (r->>'warehouse_id')::bigint=any(seen) or coalesce((r->>'quantity')::integer,0)<=0 then raise exception 'Invalid allocation split.'; end if;
    if not exists(select 1 from public.warehouses where id=(r->>'warehouse_id')::bigint and user_id=u) then raise exception 'Warehouse not found.'; end if;
    seen:=array_append(seen,(r->>'warehouse_id')::bigint); total:=total+(r->>'quantity')::integer;
  end loop;
  if total<>i.ordered_quantity then raise exception 'Allocation total must equal ordered quantity.'; end if;
  for x in select * from public.factory_arrival_allocations where factory_arrival_item_id=i.id and user_id=u loop
    select (value->>'quantity')::integer into desired from jsonb_array_elements(p_payload->'allocations') where (value->>'warehouse_id')::bigint=x.warehouse_id;
    if coalesce(desired,0)<x.normally_received_quantity+x.shortage_closed_quantity then raise exception 'Received or closed allocation quantity cannot be moved.'; end if;
  end loop;
  delete from public.factory_arrival_allocations old_allocation where old_allocation.factory_arrival_item_id=i.id and old_allocation.user_id=u and old_allocation.normally_received_quantity=0 and old_allocation.shortage_closed_quantity=0 and not (old_allocation.warehouse_id=any(seen));
  for r in select value from jsonb_array_elements(p_payload->'allocations') loop
    update public.factory_arrival_allocations set allocated_quantity=(r->>'quantity')::integer,warehouse_name_snapshot=(select name from public.warehouses where id=(r->>'warehouse_id')::bigint and user_id=u),updated_at=timezone('utc',now()) where factory_arrival_item_id=i.id and user_id=u and warehouse_id=(r->>'warehouse_id')::bigint;
    if not found then insert into public.factory_arrival_allocations(user_id,factory_arrival_id,factory_arrival_item_id,product_variant_id,warehouse_id,allocated_quantity,warehouse_name_snapshot) values(u,a.id,i.id,i.product_variant_id,(r->>'warehouse_id')::bigint,(r->>'quantity')::integer,(select name from public.warehouses where id=(r->>'warehouse_id')::bigint and user_id=u)); end if;
  end loop;
  perform private.refresh_factory_arrival_status(a.id,u); return jsonb_build_object('arrival_id',a.id,'item_id',i.id);
end $$;

create or replace function public.receive_factory_arrival_request(p_payload jsonb) returns jsonb language plpgsql security definer set search_path=private,public as $$
declare u uuid:=auth.uid(); request_id text:=btrim(p_payload->>'receipt_request_id'); business_date date:=nullif(p_payload->>'receipt_business_date','')::date; canonical jsonb; hash text; existing public.factory_receipt_requests%rowtype; a public.factory_arrivals%rowtype; line jsonb; x public.factory_arrival_allocations%rowtype; i public.factory_arrival_items%rowtype; v public.product_variants%rowtype; q integer; oq integer; event_id bigint; tx bigint; seen bigint[]:='{}';
begin
  if u is null or coalesce(request_id,'')='' or business_date is null or jsonb_typeof(p_payload->'lines')<>'array' or jsonb_array_length(p_payload->'lines')=0 then raise exception 'Invalid receipt request.'; end if;
  canonical:=jsonb_build_object('arrival_id',(p_payload->>'arrival_id')::bigint,'receipt_business_date',business_date,'lines',p_payload->'lines'); hash:=private.factory_payload_hash(canonical);
  perform pg_advisory_xact_lock(hashtextextended(u::text||':'||request_id,0));
  select * into existing from public.factory_receipt_requests where user_id=u and receipt_request_id=request_id;
  if found then if existing.payload_hash<>hash then raise exception 'receipt_request_conflict'; end if; return jsonb_build_object('receipt_event_id',existing.receipt_event_id,'idempotent',true); end if;
  select * into a from public.factory_arrivals where id=(p_payload->>'arrival_id')::bigint and user_id=u for update;
  if not found or a.status in('RECEIVED','VARIANCE_CLOSED','CANCELLED') then raise exception 'Arrival cannot be received.'; end if;
  for line in select value from jsonb_array_elements(p_payload->'lines') order by (value->>'allocation_id')::bigint loop
    q:=coalesce((line->>'quantity')::integer,0); oq:=coalesce((line->>'overage_quantity')::integer,0);
    if (line->>'allocation_id')::bigint=any(seen) then raise exception 'Duplicate receipt allocation.'; end if; seen:=array_append(seen,(line->>'allocation_id')::bigint);
    select * into x from public.factory_arrival_allocations where id=(line->>'allocation_id')::bigint and factory_arrival_id=a.id and user_id=u for update;
    if not found or q<0 or oq<0 or (q=0 and oq=0) or q>x.allocated_quantity-x.normally_received_quantity-x.shortage_closed_quantity or (oq>0 and btrim(coalesce(line->>'overage_reason',''))='') then raise exception 'Invalid receipt line.'; end if;
  end loop;
  insert into public.factory_receipt_events(user_id,factory_arrival_id,event_kind,received_at,receipt_business_date,immutable_payload,receipt_request_id) values(u,a.id,'RECEIPT',timezone('utc',now()),business_date,canonical,request_id) returning id into event_id;
  insert into public.factory_receipt_requests(user_id,receipt_request_id,payload_hash,factory_arrival_id,immutable_payload,receipt_event_id) values(u,request_id,hash,a.id,canonical,event_id);
  for line in select value from jsonb_array_elements(p_payload->'lines') loop
    q:=coalesce((line->>'quantity')::integer,0); oq:=coalesce((line->>'overage_quantity')::integer,0);
    select * into x from public.factory_arrival_allocations where id=(line->>'allocation_id')::bigint and user_id=u;
    select * into i from public.factory_arrival_items where id=x.factory_arrival_item_id and user_id=u;
    select * into v from public.product_variants where id=x.product_variant_id and user_id=u;
    insert into public.inventory(user_id,model_id,size_id,color_id,warehouse_id,quantity) values(u,v.model_id,v.size_id,v.color_id,x.warehouse_id,q+oq) on conflict(user_id,model_id,size_id,color_id,warehouse_id) do update set quantity=public.inventory.quantity+excluded.quantity,updated_at=timezone('utc',now());
    insert into public.transactions(user_id,date,model_id,size_id,color_id,type,quantity,warehouse_id,source_channel,reference_type,reference_id,memo) values(u,business_date,v.model_id,v.size_id,v.color_id,'INBOUND',q+oq,x.warehouse_id,'factory-arrival','factory_receipt_event',event_id,case when oq>0 then btrim(line->>'overage_reason') else '검수 입고' end) returning id into tx;
    insert into public.factory_receipt_lines(user_id,factory_receipt_event_id,factory_arrival_allocation_id,factory_arrival_item_id,warehouse_id,transaction_id,received_quantity,normal_quantity,overage_quantity,overage_reason,seller_sku_snapshot,product_name_snapshot,option_name_snapshot,warehouse_name_snapshot) values(u,event_id,x.id,i.id,x.warehouse_id,tx,q+oq,q,oq,case when oq>0 then btrim(line->>'overage_reason') end,i.seller_sku_snapshot,i.product_name_snapshot,i.option_name_snapshot,x.warehouse_name_snapshot);
    update public.factory_arrival_allocations set normally_received_quantity=normally_received_quantity+q,updated_at=timezone('utc',now()) where id=x.id;
    update public.factory_arrival_items set received_quantity=received_quantity+q,updated_at=timezone('utc',now()) where id=i.id;
    perform private.enqueue_factory_variant(u,v.id);
  end loop;
  perform private.refresh_factory_arrival_status(a.id,u); return jsonb_build_object('receipt_event_id',event_id,'idempotent',false);
end $$;

create or replace function public.close_factory_arrival_shortage(p_payload jsonb) returns jsonb language plpgsql security definer set search_path=private,public as $$
declare u uuid:=auth.uid(); x public.factory_arrival_allocations%rowtype; q integer:=(p_payload->>'quantity')::integer; closure_id bigint; a public.factory_arrivals%rowtype;
begin
  if u is null or q is null or q<=0 or btrim(coalesce(p_payload->>'reason',''))='' then raise exception 'Invalid shortage closure.'; end if;
  select a0.* into a from public.factory_arrivals a0 join public.factory_arrival_allocations x0 on x0.factory_arrival_id=a0.id and x0.user_id=a0.user_id where x0.id=(p_payload->>'allocation_id')::bigint and a0.user_id=u for update of a0;
  if not found or a.status not in('READY','PARTIAL') then raise exception 'Arrival cannot close a shortage.'; end if;
  select * into x from public.factory_arrival_allocations where id=(p_payload->>'allocation_id')::bigint and user_id=u for update;
  if q>x.allocated_quantity-x.normally_received_quantity-x.shortage_closed_quantity then raise exception 'Shortage exceeds expected remainder.'; end if;
  insert into public.factory_arrival_shortage_closures(user_id,factory_arrival_allocation_id,quantity,reason,actor_id) values(u,x.id,q,btrim(p_payload->>'reason'),u) returning id into closure_id;
  update public.factory_arrival_allocations set shortage_closed_quantity=shortage_closed_quantity+q,updated_at=timezone('utc',now()) where id=x.id;
  perform private.refresh_factory_arrival_status(x.factory_arrival_id,u); return jsonb_build_object('closure_id',closure_id,'allocation_id',x.id);
end $$;

create or replace function public.record_factory_arrival_follow_up(p_payload jsonb) returns jsonb language plpgsql security definer set search_path=private,public as $$
declare u uuid:=auth.uid(); request_id text:=btrim(p_payload->>'receipt_request_id'); business_date date:=nullif(p_payload->>'receipt_business_date','')::date; canonical jsonb; hash text; existing public.factory_receipt_requests%rowtype; c public.factory_arrival_shortage_closures%rowtype; x public.factory_arrival_allocations%rowtype; i public.factory_arrival_items%rowtype; a public.factory_arrivals%rowtype; w public.warehouses%rowtype; v public.product_variants%rowtype; q integer:=(p_payload->>'quantity')::integer; event_id bigint; line_id bigint; tx bigint;
begin
  if u is null or coalesce(request_id,'')='' or business_date is null or q is null or q<=0 or btrim(coalesce(p_payload->>'reason',''))='' then raise exception 'Invalid follow-up receipt.'; end if;
  canonical:=jsonb_build_object('closure_id',(p_payload->>'closure_id')::bigint,'warehouse_id',(p_payload->>'warehouse_id')::bigint,'quantity',q,'reason',btrim(p_payload->>'reason'),'receipt_business_date',business_date); hash:=private.factory_payload_hash(canonical);
  perform pg_advisory_xact_lock(hashtextextended(u::text||':'||request_id,0)); select * into existing from public.factory_receipt_requests where user_id=u and receipt_request_id=request_id;
  if found then if existing.payload_hash<>hash then raise exception 'receipt_request_conflict'; end if; return jsonb_build_object('receipt_event_id',existing.receipt_event_id,'idempotent',true); end if;
  select * into c from public.factory_arrival_shortage_closures where id=(p_payload->>'closure_id')::bigint and user_id=u for update; if not found then raise exception 'Shortage closure not found.'; end if;
  select * into x from public.factory_arrival_allocations where id=c.factory_arrival_allocation_id and user_id=u for update; select * into i from public.factory_arrival_items where id=x.factory_arrival_item_id and user_id=u; select * into a from public.factory_arrivals where id=x.factory_arrival_id and user_id=u for update; select * into w from public.warehouses where id=(p_payload->>'warehouse_id')::bigint and user_id=u; if not found then raise exception 'Warehouse not found.'; end if; select * into v from public.product_variants where id=x.product_variant_id and user_id=u;
  insert into public.factory_receipt_events(user_id,factory_arrival_id,event_kind,received_at,receipt_business_date,immutable_payload,receipt_request_id) values(u,a.id,'FOLLOW_UP',timezone('utc',now()),business_date,canonical,request_id) returning id into event_id;
  insert into public.factory_receipt_requests(user_id,receipt_request_id,payload_hash,factory_arrival_id,immutable_payload,receipt_event_id) values(u,request_id,hash,a.id,canonical,event_id);
  insert into public.inventory(user_id,model_id,size_id,color_id,warehouse_id,quantity) values(u,v.model_id,v.size_id,v.color_id,w.id,q) on conflict(user_id,model_id,size_id,color_id,warehouse_id) do update set quantity=public.inventory.quantity+excluded.quantity,updated_at=timezone('utc',now());
  insert into public.transactions(user_id,date,model_id,size_id,color_id,type,quantity,warehouse_id,source_channel,reference_type,reference_id,memo) values(u,business_date,v.model_id,v.size_id,v.color_id,'INBOUND',q,w.id,'factory-arrival','factory_receipt_event',event_id,btrim(p_payload->>'reason')) returning id into tx;
  insert into public.factory_receipt_lines(user_id,factory_receipt_event_id,factory_arrival_allocation_id,factory_arrival_item_id,warehouse_id,factory_arrival_shortage_closure_id,transaction_id,received_quantity,normal_quantity,overage_quantity,overage_reason,seller_sku_snapshot,product_name_snapshot,option_name_snapshot,warehouse_name_snapshot) values(u,event_id,null,i.id,w.id,c.id,tx,q,0,q,btrim(p_payload->>'reason'),i.seller_sku_snapshot,i.product_name_snapshot,i.option_name_snapshot,w.name) returning id into line_id;
  perform private.enqueue_factory_variant(u,v.id); return jsonb_build_object('receipt_event_id',event_id,'receipt_line_id',line_id,'idempotent',false);
end $$;

create or replace function public.reverse_factory_receipt_line(p_payload jsonb) returns jsonb language plpgsql security definer set search_path=private,public as $$
declare u uuid:=auth.uid(); request_id text:=btrim(p_payload->>'correction_request_id'); canonical jsonb; hash text; existing public.factory_receipt_line_corrections%rowtype; l public.factory_receipt_lines%rowtype; e public.factory_receipt_events%rowtype; i public.factory_arrival_items%rowtype; v public.product_variants%rowtype; inv public.inventory%rowtype; reserved integer; tx bigint; correction_id bigint;
begin
  if u is null or coalesce(request_id,'')='' or btrim(coalesce(p_payload->>'reason',''))='' then raise exception 'Invalid receipt correction.'; end if;
  canonical:=jsonb_build_object('receipt_line_id',(p_payload->>'receipt_line_id')::bigint,'reason',btrim(p_payload->>'reason')); hash:=private.factory_payload_hash(canonical);
  perform pg_advisory_xact_lock(hashtextextended(u::text||':'||request_id,0)); select * into existing from public.factory_receipt_line_corrections where user_id=u and correction_request_id=request_id;
  if found then if existing.payload_hash<>hash then raise exception 'correction_request_conflict'; end if; return jsonb_build_object('correction_id',existing.id,'transaction_id',existing.transaction_id,'idempotent',true); end if;
  select * into l from public.factory_receipt_lines where id=(p_payload->>'receipt_line_id')::bigint and user_id=u for update; if not found then raise exception 'Receipt line not found.'; end if;
  if exists(select 1 from public.factory_receipt_line_corrections where factory_receipt_line_id=l.id and user_id=u) then raise exception 'receipt_line_already_reversed'; end if;
  select * into e from public.factory_receipt_events where id=l.factory_receipt_event_id and user_id=u for update; select * into i from public.factory_arrival_items where id=l.factory_arrival_item_id and user_id=u; select * into v from public.product_variants where id=i.product_variant_id and user_id=u;
  select * into inv from public.inventory where user_id=u and model_id=v.model_id and size_id=v.size_id and color_id=v.color_id and warehouse_id=l.warehouse_id for update;
  select coalesce(sum(quantity),0) into reserved from public.inventory_reservations where user_id=u and product_variant_id=v.id and warehouse_id=l.warehouse_id and status='active';
  if inv.id is null or inv.quantity-l.received_quantity<reserved then raise exception 'insufficient_or_committed_inventory'; end if;
  update public.inventory set quantity=quantity-l.received_quantity,updated_at=timezone('utc',now()) where id=inv.id;
  insert into public.transactions(user_id,date,model_id,size_id,color_id,type,quantity,warehouse_id,source_channel,reference_type,reference_id,memo) values(u,current_date,v.model_id,v.size_id,v.color_id,'OUTBOUND',l.received_quantity,l.warehouse_id,'factory-arrival-correction','factory_receipt_line',l.id,btrim(p_payload->>'reason')) returning id into tx;
  insert into public.factory_receipt_line_corrections(user_id,correction_request_id,payload_hash,immutable_payload,factory_receipt_line_id,reason,actor_id,transaction_id) values(u,request_id,hash,canonical,l.id,btrim(p_payload->>'reason'),u,tx) returning id into correction_id;
  if l.normal_quantity>0 then update public.factory_arrival_allocations set normally_received_quantity=normally_received_quantity-l.normal_quantity,updated_at=timezone('utc',now()) where id=l.factory_arrival_allocation_id and user_id=u; update public.factory_arrival_items set received_quantity=received_quantity-l.normal_quantity,updated_at=timezone('utc',now()) where id=i.id and user_id=u; end if;
  perform private.refresh_factory_arrival_status(e.factory_arrival_id,u); perform private.enqueue_factory_variant(u,v.id); return jsonb_build_object('correction_id',correction_id,'transaction_id',tx,'idempotent',false);
end $$;

alter table public.factory_receipt_requests enable row level security;
alter table public.factory_arrival_shortage_closures enable row level security;
alter table public.factory_receipt_line_corrections enable row level security;
create policy "Users read own factory receipt requests" on public.factory_receipt_requests for select to authenticated using ((select auth.uid())=user_id);
create policy "Users read own factory shortage closures" on public.factory_arrival_shortage_closures for select to authenticated using ((select auth.uid())=user_id);
create policy "Users read own factory receipt corrections" on public.factory_receipt_line_corrections for select to authenticated using ((select auth.uid())=user_id);
create or replace function private.reject_factory_operation_evidence_mutation() returns trigger language plpgsql set search_path=private,public as $$ begin raise exception 'immutable_factory_operation_evidence'; end $$;
create trigger factory_receipt_requests_immutable before update or delete on public.factory_receipt_requests for each row execute function private.reject_factory_operation_evidence_mutation();
create trigger factory_shortage_closures_immutable before update or delete on public.factory_arrival_shortage_closures for each row execute function private.reject_factory_operation_evidence_mutation();
create trigger factory_receipt_corrections_immutable before update or delete on public.factory_receipt_line_corrections for each row execute function private.reject_factory_operation_evidence_mutation();
revoke insert,update,delete on public.factory_arrival_allocations,public.factory_receipt_requests,public.factory_arrival_shortage_closures,public.factory_receipt_line_corrections,public.factory_receipt_events,public.factory_receipt_lines from authenticated;
revoke all on function private.classify_legacy_factory_receipt_line(),private.assert_factory_arrival_receipt_consistency(),private.guard_active_inventory_reservation(),private.factory_payload_hash(jsonb),private.refresh_factory_arrival_status(bigint,uuid),private.enqueue_factory_variant(uuid,bigint),private.reject_factory_operation_evidence_mutation() from public,anon,authenticated;
grant execute on function public.replace_factory_arrival_allocations(jsonb),public.receive_factory_arrival_request(jsonb),public.close_factory_arrival_shortage(jsonb),public.record_factory_arrival_follow_up(jsonb),public.reverse_factory_receipt_line(jsonb) to authenticated;
