create table public.inbound_templates (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (id, user_id), unique (user_id, name)
);
create table public.inbound_template_versions (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  template_id bigint not null,
  version_number integer not null check (version_number > 0),
  sheet_name text not null,
  header_row_number integer not null check (header_row_number > 0),
  headers jsonb not null,
  mappings jsonb not null,
  created_at timestamptz not null default timezone('utc', now()),
  unique (id, user_id), unique (template_id, version_number),
  foreign key (template_id, user_id) references public.inbound_templates(id, user_id) on delete restrict
);
alter table public.inbound_drafts add column template_id bigint, add column template_version_id bigint;
alter table public.inbound_draft_rows add column template_id bigint;
alter table public.supplier_sku_links add column template_id bigint;
alter table public.inbound_drafts add foreign key (template_id, user_id) references public.inbound_templates(id, user_id) on delete restrict;
alter table public.inbound_drafts add foreign key (template_version_id, user_id) references public.inbound_template_versions(id, user_id) on delete restrict;
alter table public.inbound_draft_rows add foreign key (template_id, user_id) references public.inbound_templates(id, user_id) on delete restrict;
alter table public.supplier_sku_links add foreign key (template_id, user_id) references public.inbound_templates(id, user_id) on delete restrict;
create unique index supplier_sku_links_exact_template_idx on public.supplier_sku_links(user_id, supplier_id, template_id, external_sku) where template_id is not null;
create index inbound_templates_active_user_idx on public.inbound_templates(user_id, is_active, name);
create index inbound_template_versions_template_idx on public.inbound_template_versions(template_id, version_number desc);
alter table public.inbound_templates enable row level security;
alter table public.inbound_template_versions enable row level security;
create policy "Users manage own inbound_templates" on public.inbound_templates for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Users manage own inbound_template_versions" on public.inbound_template_versions for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
