-- Keep the canonical schema and migration aligned. See supabase/schema.sql.
create table if not exists public.inbound_drafts (
  id bigint generated by default as identity primary key, user_id uuid not null default auth.uid() references auth.users(id) on delete cascade, supplier_id bigint not null, status text not null default 'draft' check (status in ('draft','partial','received')), created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now()), unique (id,user_id), foreign key (supplier_id,user_id) references public.factories(id,user_id) on delete restrict
);
create table if not exists public.inbound_draft_rows (
  id bigint generated by default as identity primary key, user_id uuid not null default auth.uid() references auth.users(id) on delete cascade, inbound_draft_id bigint not null, template text not null, external_sku text not null, quantity integer not null check (quantity > 0), received_quantity integer not null default 0 check (received_quantity >= 0 and received_quantity <= quantity), warehouse_id bigint not null, product_variant_id bigint, created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now()), unique (id,user_id), foreign key (inbound_draft_id,user_id) references public.inbound_drafts(id,user_id) on delete cascade, foreign key (warehouse_id,user_id) references public.warehouses(id,user_id) on delete restrict, foreign key (product_variant_id,user_id) references public.product_variants(id,user_id) on delete set null
);
create table if not exists public.supplier_sku_links (
 id bigint generated by default as identity primary key, user_id uuid not null default auth.uid() references auth.users(id) on delete cascade, supplier_id bigint not null, template text not null, external_sku text not null, product_variant_id bigint not null, received_at timestamptz not null default timezone('utc',now()), unique(user_id,supplier_id,template,external_sku), foreign key(supplier_id,user_id) references public.factories(id,user_id) on delete cascade, foreign key(product_variant_id,user_id) references public.product_variants(id,user_id) on delete cascade
);
create index if not exists inbound_drafts_user_id_idx on public.inbound_drafts(user_id,created_at desc); create index if not exists inbound_draft_rows_draft_user_id_idx on public.inbound_draft_rows(inbound_draft_id,user_id); create index if not exists supplier_sku_links_exact_idx on public.supplier_sku_links(user_id,supplier_id,template,external_sku);
alter table public.inbound_drafts enable row level security; alter table public.inbound_draft_rows enable row level security; alter table public.supplier_sku_links enable row level security;
create policy "Users manage own inbound_drafts" on public.inbound_drafts for all to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id); create policy "Users manage own inbound_draft_rows" on public.inbound_draft_rows for all to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id); create policy "Users manage own supplier_sku_links" on public.supplier_sku_links for all to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);

create or replace function public.receive_inbound_draft_rows(p_draft_id bigint, p_rows jsonb)
returns void language plpgsql security invoker set search_path = '' as $$
declare v_user_id uuid := auth.uid(); v_input jsonb; v_draft public.inbound_drafts%rowtype; v_row public.inbound_draft_rows%rowtype; v_variant public.product_variants%rowtype; v_quantity integer; v_open integer;
begin
 if v_user_id is null then raise exception 'Authentication is required.'; end if;
 if jsonb_typeof(p_rows) is distinct from 'array' then raise exception 'p_rows must be a JSON array.'; end if;
 select * into v_draft from public.inbound_drafts where id=p_draft_id and user_id=v_user_id for update;
 if not found or v_draft.status='received' then raise exception 'Inbound draft cannot be received.'; end if;
 for v_input in select * from jsonb_array_elements(p_rows) loop
  select * into v_row from public.inbound_draft_rows where id=(v_input->>'row_id')::bigint and inbound_draft_id=p_draft_id and user_id=v_user_id for update;
  if not found then raise exception 'Inbound draft row not found.'; end if;
  if v_row.product_variant_id is null then raise exception 'Unmatched inbound rows cannot be received.'; end if;
  v_quantity := (v_input->>'quantity')::integer;
  if v_quantity is null or v_quantity<=0 or v_quantity > v_row.quantity-v_row.received_quantity then raise exception 'Receive quantity is invalid.'; end if;
  select * into v_variant from public.product_variants where id=v_row.product_variant_id and user_id=v_user_id;
  if not found then raise exception 'Assigned internal SKU not found.'; end if;
  update public.inbound_draft_rows set received_quantity=received_quantity+v_quantity, updated_at=timezone('utc',now()) where id=v_row.id;
  insert into public.inventory(user_id,model_id,size_id,color_id,warehouse_id,quantity) values(v_user_id,v_variant.model_id,v_variant.size_id,v_variant.color_id,v_row.warehouse_id,v_quantity) on conflict(user_id,model_id,size_id,color_id,warehouse_id) do update set quantity=public.inventory.quantity+excluded.quantity,updated_at=timezone('utc',now());
  insert into public.transactions(user_id,date,model_id,size_id,color_id,type,quantity,warehouse_id,source_channel,reference_type,reference_id,memo) values(v_user_id,current_date,v_variant.model_id,v_variant.size_id,v_variant.color_id,'INBOUND',v_quantity,v_row.warehouse_id,'inbound-draft','inbound_draft_row',v_row.id,'검수 입고');
  insert into public.supplier_sku_links(user_id,supplier_id,template,external_sku,product_variant_id) values(v_user_id,v_draft.supplier_id,v_row.template,v_row.external_sku,v_row.product_variant_id) on conflict(user_id,supplier_id,template,external_sku) do update set product_variant_id=excluded.product_variant_id,received_at=timezone('utc',now());
  insert into public.inventory_sync_outbox(user_id,channel_product_ref_id,target_quantity,status,last_error,requested_at,updated_at) select v_user_id,ref.id,greatest(coalesce(sum(inv.quantity),0)-coalesce((select sum(quantity) from public.inventory_reservations where user_id=v_user_id and product_variant_id=v_variant.id and status='active'),0),0),'required','동기화 필요: 현재 provider는 재고 수량 쓰기를 지원하지 않습니다.',timezone('utc',now()),timezone('utc',now()) from public.channel_product_refs ref left join public.inventory inv on inv.user_id=v_user_id and inv.model_id=v_variant.model_id and inv.size_id=v_variant.size_id and inv.color_id=v_variant.color_id where ref.user_id=v_user_id and ref.variant_id=v_variant.id group by ref.id on conflict(user_id,channel_product_ref_id) do update set target_quantity=excluded.target_quantity,status='required',last_error=excluded.last_error,requested_at=excluded.requested_at,updated_at=excluded.updated_at;
 end loop;
 select count(*) into v_open from public.inbound_draft_rows where inbound_draft_id=p_draft_id and user_id=v_user_id and received_quantity<quantity;
 update public.inbound_drafts set status=case when v_open=0 then 'received' else 'partial' end,updated_at=timezone('utc',now()) where id=p_draft_id and user_id=v_user_id;
end;
$$;
