alter table public.channel_product_refs
  add column if not exists sync_target_quantity integer,
  add column if not exists sync_status text not null default 'idle'
    check (sync_status in ('idle', 'required', 'failed', 'succeeded'));

create table if not exists public.inventory_sync_outbox (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  channel_product_ref_id bigint not null,
  target_quantity integer not null check (target_quantity >= 0),
  status text not null check (status in ('required', 'failed', 'succeeded')),
  attempts integer not null default 0 check (attempts >= 0),
  last_error text,
  requested_at timestamptz not null default timezone('utc', now()),
  completed_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (id, user_id),
  unique (user_id, channel_product_ref_id),
  foreign key (channel_product_ref_id, user_id) references public.channel_product_refs (id, user_id) on delete cascade
);

create index if not exists inventory_sync_outbox_user_id_idx on public.inventory_sync_outbox (user_id);
alter table public.inventory_sync_outbox enable row level security;
drop policy if exists "Users manage own inventory_sync_outbox" on public.inventory_sync_outbox;
create policy "Users manage own inventory_sync_outbox" on public.inventory_sync_outbox for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
