create table if not exists public.product_variants (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  model_id bigint not null,
  size_id bigint not null,
  color_id bigint not null,
  seller_sku text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (id, user_id),
  unique (user_id, seller_sku),
  unique (user_id, model_id, size_id, color_id),
  foreign key (model_id, user_id) references public.models (id, user_id) on delete cascade,
  foreign key (model_id, size_id, user_id) references public.sizes (model_id, id, user_id) on delete cascade,
  foreign key (model_id, color_id, user_id) references public.colors (model_id, id, user_id) on delete cascade
);

create table if not exists public.channel_product_refs (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  channel text not null check (channel in ('naver', 'coupang')),
  external_product_id text not null,
  external_variant_id text not null,
  variant_id bigint,
  product_name text,
  option_name text,
  seller_sku text,
  listing_status text not null default 'active',
  channel_attributes jsonb not null default '{}'::jsonb,
  channel_reported integer,
  last_synced_at timestamptz,
  last_sync_error text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (id, user_id),
  unique (user_id, channel, external_product_id, external_variant_id),
  foreign key (variant_id, user_id) references public.product_variants (id, user_id) on delete set null (variant_id)
);

create table if not exists public.channel_orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  channel text not null check (channel in ('naver', 'coupang')),
  external_order_id text not null,
  order_status text not null,
  ordered_at timestamptz,
  customer_name text,
  shipping_address text,
  raw_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (id, user_id),
  unique (user_id, channel, external_order_id)
);

create table if not exists public.channel_order_lines (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  channel_order_id bigint not null,
  channel text not null check (channel in ('naver', 'coupang')),
  external_line_id text not null,
  channel_product_ref_id bigint,
  variant_id bigint,
  quantity integer not null check (quantity > 0),
  line_status text not null,
  raw_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (id, user_id),
  unique (user_id, channel, external_line_id),
  foreign key (channel_order_id, user_id) references public.channel_orders (id, user_id) on delete cascade,
  foreign key (channel_product_ref_id, user_id) references public.channel_product_refs (id, user_id) on delete set null (channel_product_ref_id),
  foreign key (variant_id, user_id) references public.product_variants (id, user_id) on delete set null (variant_id)
);

create table if not exists public.inventory_reservations (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  channel_order_line_id bigint not null,
  product_variant_id bigint not null,
  warehouse_id bigint not null,
  quantity integer not null check (quantity > 0),
  status text not null default 'active' check (status in ('active', 'released', 'cancelled')),
  created_at timestamptz not null default timezone('utc', now()),
  released_at timestamptz,
  unique (id, user_id),
  foreign key (channel_order_line_id, user_id) references public.channel_order_lines (id, user_id) on delete cascade,
  foreign key (product_variant_id, user_id) references public.product_variants (id, user_id) on delete cascade,
  foreign key (warehouse_id, user_id) references public.warehouses (id, user_id) on delete cascade
);

create table if not exists public.tracking_import_templates (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  channel text check (channel in ('naver', 'coupang')),
  name text not null,
  column_mapping jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (id, user_id),
  unique (user_id, channel, name)
);

create table if not exists public.tracking_import_batches (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  tracking_import_template_id bigint,
  source_filename text not null,
  status text not null default 'pending',
  row_count integer not null default 0 check (row_count >= 0),
  result_summary jsonb not null default '{}'::jsonb,
  error text,
  created_at timestamptz not null default timezone('utc', now()),
  completed_at timestamptz,
  unique (id, user_id),
  foreign key (tracking_import_template_id, user_id) references public.tracking_import_templates (id, user_id) on delete set null (tracking_import_template_id)
);

create table if not exists public.order_fulfillments (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  channel_order_line_id bigint not null,
  inventory_reservation_id bigint not null,
  tracking_import_batch_id bigint,
  idempotency_key text not null,
  external_status text not null default 'pending',
  local_status text not null default 'pending' check (local_status in ('pending', 'fulfilled', 'failed')),
  tracking_number text,
  carrier_code text,
  external_reference text,
  error text,
  fulfilled_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (id, user_id),
  unique (user_id, idempotency_key),
  foreign key (channel_order_line_id, user_id) references public.channel_order_lines (id, user_id) on delete cascade,
  foreign key (inventory_reservation_id, user_id) references public.inventory_reservations (id, user_id) on delete cascade,
  foreign key (tracking_import_batch_id, user_id) references public.tracking_import_batches (id, user_id) on delete set null (tracking_import_batch_id)
);

create index if not exists product_variants_user_id_idx on public.product_variants (user_id);
create index if not exists channel_product_refs_user_id_idx on public.channel_product_refs (user_id);
create index if not exists channel_orders_user_id_idx on public.channel_orders (user_id);
create index if not exists channel_order_lines_user_id_idx on public.channel_order_lines (user_id);
create index if not exists inventory_reservations_user_id_idx on public.inventory_reservations (user_id);
create index if not exists order_fulfillments_user_id_idx on public.order_fulfillments (user_id);
create index if not exists tracking_import_templates_user_id_idx on public.tracking_import_templates (user_id);
create index if not exists tracking_import_batches_user_id_idx on public.tracking_import_batches (user_id);

alter table public.product_variants enable row level security;
alter table public.channel_product_refs enable row level security;
alter table public.channel_orders enable row level security;
alter table public.channel_order_lines enable row level security;
alter table public.inventory_reservations enable row level security;
alter table public.order_fulfillments enable row level security;
alter table public.tracking_import_templates enable row level security;
alter table public.tracking_import_batches enable row level security;

drop policy if exists "Users manage own product_variants" on public.product_variants;
create policy "Users manage own product_variants" on public.product_variants for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "Users manage own channel_product_refs" on public.channel_product_refs;
create policy "Users manage own channel_product_refs" on public.channel_product_refs for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "Users manage own channel_orders" on public.channel_orders;
create policy "Users manage own channel_orders" on public.channel_orders for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "Users manage own channel_order_lines" on public.channel_order_lines;
create policy "Users manage own channel_order_lines" on public.channel_order_lines for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "Users manage own inventory_reservations" on public.inventory_reservations;
create policy "Users manage own inventory_reservations" on public.inventory_reservations for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "Users manage own order_fulfillments" on public.order_fulfillments;
create policy "Users manage own order_fulfillments" on public.order_fulfillments for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "Users manage own tracking_import_templates" on public.tracking_import_templates;
create policy "Users manage own tracking_import_templates" on public.tracking_import_templates for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "Users manage own tracking_import_batches" on public.tracking_import_batches;
create policy "Users manage own tracking_import_batches" on public.tracking_import_batches for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

create or replace function public.finalize_order_fulfillment(p_fulfillment_id bigint)
returns boolean
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_fulfillment public.order_fulfillments%rowtype;
  v_reservation public.inventory_reservations%rowtype;
  v_variant public.product_variants%rowtype;
  v_inventory_quantity integer;
begin
  if v_user_id is null then
    raise exception 'Authentication is required.';
  end if;

  select * into v_fulfillment
  from public.order_fulfillments
  where id = p_fulfillment_id and user_id = v_user_id
  for update;

  if not found then
    raise exception 'Order fulfillment not found.';
  end if;

  if v_fulfillment.local_status = 'fulfilled' then
    return true;
  end if;

  if v_fulfillment.external_status <> 'success' then
    raise exception 'External fulfillment has not succeeded.';
  end if;

  select * into v_reservation
  from public.inventory_reservations
  where id = v_fulfillment.inventory_reservation_id
    and user_id = v_user_id
  for update;

  if not found or v_reservation.status <> 'active' then
    raise exception 'Active inventory reservation not found.';
  end if;

  select * into v_variant
  from public.product_variants
  where id = v_reservation.product_variant_id and user_id = v_user_id;

  if not found then
    raise exception 'Product variant not found.';
  end if;

  select quantity into v_inventory_quantity
  from public.inventory
  where user_id = v_user_id
    and model_id = v_variant.model_id
    and size_id = v_variant.size_id
    and color_id = v_variant.color_id
    and warehouse_id = v_reservation.warehouse_id
  for update;

  if not found or v_inventory_quantity < v_reservation.quantity then
    raise exception 'Insufficient on-hand inventory.';
  end if;

  update public.inventory
  set quantity = quantity - v_reservation.quantity,
      updated_at = timezone('utc', now())
  where user_id = v_user_id
    and model_id = v_variant.model_id
    and size_id = v_variant.size_id
    and color_id = v_variant.color_id
    and warehouse_id = v_reservation.warehouse_id;

  update public.inventory_reservations
  set status = 'released', released_at = timezone('utc', now())
  where id = v_reservation.id and user_id = v_user_id;

  insert into public.transactions (
    user_id, date, model_id, size_id, color_id, type, quantity, warehouse_id, source_channel, reference_type, reference_id, memo
  ) values (
    v_user_id, current_date, v_variant.model_id, v_variant.size_id, v_variant.color_id,
    'OUTBOUND', v_reservation.quantity, v_reservation.warehouse_id, 'channel-fulfillment',
    'order_fulfillment', v_fulfillment.id, coalesce(v_fulfillment.tracking_number, '채널 주문 출고')
  );

  update public.order_fulfillments
  set local_status = 'fulfilled', fulfilled_at = timezone('utc', now()), updated_at = timezone('utc', now()), error = null
  where id = v_fulfillment.id and user_id = v_user_id;

  return true;
end;
$$;

revoke execute on function public.finalize_order_fulfillment(bigint) from public, anon;
grant execute on function public.finalize_order_fulfillment(bigint) to authenticated;
