-- Generalize the audited inbound template records without changing existing ids,
-- version numbers, draft references, supplier links, or source-file paths.
alter table public.inbound_templates add column if not exists business_type text not null default 'inbound'
  check (business_type in ('inbound', 'order', 'purchase_order'));
alter table public.inbound_template_versions add column if not exists business_type text not null default 'inbound'
  check (business_type in ('inbound', 'order', 'purchase_order'));
alter table public.inbound_templates drop constraint if exists inbound_templates_user_id_name_key;
create unique index if not exists template_definitions_user_type_name_idx
  on public.inbound_templates(user_id, business_type, name);
create index if not exists template_definitions_active_type_idx
  on public.inbound_templates(user_id, business_type, is_active, name);

create table if not exists public.template_custom_fields (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  business_type text not null check (business_type in ('inbound', 'order', 'purchase_order')),
  name text not null,
  normalized_name text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (user_id, business_type, normalized_name)
);
create index if not exists template_custom_fields_active_lookup_idx
  on public.template_custom_fields(user_id, business_type, is_active, normalized_name);

alter table public.template_custom_fields enable row level security;
drop policy if exists "Users manage own template custom fields" on public.template_custom_fields;
create policy "Users read own template custom fields" on public.template_custom_fields for select to authenticated using ((select auth.uid()) = user_id);
create policy "Users create own template custom fields" on public.template_custom_fields for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Users update own template custom fields" on public.template_custom_fields for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
