-- Supplier SKU identity is independent of import templates.  Raw SKU remains
-- evidence; normalized SKU is only the exact lookup key.
create schema if not exists private;
create or replace function private.normalize_supplier_external_sku(p_value text)
returns text language sql immutable strict set search_path = pg_catalog as $$
  select btrim(p_value, E' \t\n\r\f\v' || U&'\\0085\\00A0\\1680\\2000\\2001\\2002\\2003\\2004\\2005\\2006\\2007\\2008\\2009\\200A\\2028\\2029\\202F\\205F\\3000')
$$;

alter table public.supplier_sku_links add column if not exists normalized_external_sku text;
alter table public.supplier_sku_links add column if not exists is_active boolean not null default true;
alter table public.supplier_sku_links add column if not exists deactivated_at timestamptz;
alter table public.supplier_sku_links add column if not exists deactivation_reason text;
update public.supplier_sku_links set normalized_external_sku=private.normalize_supplier_external_sku(external_sku) where normalized_external_sku is null;
alter table public.supplier_sku_links alter column normalized_external_sku set not null;
alter table public.supplier_sku_links drop constraint if exists supplier_sku_links_user_id_supplier_id_template_external_sku_key;
drop index if exists public.supplier_sku_links_exact_idx;
drop index if exists public.supplier_sku_links_exact_template_idx;

create table public.supplier_sku_mapping_audits (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  actor_id uuid not null references auth.users(id) on delete restrict,
  supplier_id bigint not null, supplier_name_snapshot text,
  raw_external_sku text not null, normalized_external_sku text not null,
  action text not null check (action in ('CONFIRMED','REASSIGNED','DEACTIVATED','LEGACY_CONFLICT')),
  previous_product_variant_id bigint, previous_seller_sku_snapshot text,
  new_product_variant_id bigint, new_seller_sku_snapshot text,
  reason text, created_at timestamptz not null default timezone('utc',now()),
  foreign key (supplier_id,user_id) references public.factories(id,user_id) on delete restrict
);
create index supplier_sku_links_active_exact_idx on public.supplier_sku_links(user_id,supplier_id,normalized_external_sku) where is_active;
create unique index supplier_sku_links_one_active_exact_idx on public.supplier_sku_links(user_id,supplier_id,normalized_external_sku) where is_active;
create index supplier_sku_mapping_audits_owner_supplier_created_idx on public.supplier_sku_mapping_audits(user_id,supplier_id,created_at desc);

-- A collapsed legacy key is retained only when every old mapping agrees.
with conflicts as (
  select user_id,supplier_id,normalized_external_sku
  from public.supplier_sku_links where is_active group by 1,2,3 having count(distinct product_variant_id) > 1
), deactivated as (
  update public.supplier_sku_links l set is_active=false,deactivated_at=timezone('utc',now()),deactivation_reason='Legacy template mappings conflict; explicit resolution required.'
  from conflicts c where l.user_id=c.user_id and l.supplier_id=c.supplier_id and l.normalized_external_sku=c.normalized_external_sku and l.is_active
  returning l.*
)
insert into public.supplier_sku_mapping_audits(user_id,actor_id,supplier_id,supplier_name_snapshot,raw_external_sku,normalized_external_sku,action,reason)
select d.user_id,d.user_id,d.supplier_id,f.name,d.external_sku,d.normalized_external_sku,'LEGACY_CONFLICT','Legacy template mappings conflict; explicit resolution required.'
from deactivated d join public.factories f on f.id=d.supplier_id and f.user_id=d.user_id;

-- Same-target legacy duplicates collapse to one active row without guessing.
with ranked as (
  select id,row_number() over(partition by user_id,supplier_id,normalized_external_sku order by received_at desc,id desc) as position
  from public.supplier_sku_links where is_active
)
update public.supplier_sku_links l set is_active=false,deactivated_at=timezone('utc',now()),deactivation_reason='Superseded duplicate legacy mapping.'
from ranked r where l.id=r.id and r.position>1;

alter table public.supplier_sku_links enable row level security;
alter table public.supplier_sku_mapping_audits enable row level security;
drop policy if exists "Users manage own supplier_sku_links" on public.supplier_sku_links;
create policy "Users read own supplier_sku_links" on public.supplier_sku_links for select to authenticated using ((select auth.uid())=user_id);
create policy "Users read own supplier_sku_mapping_audits" on public.supplier_sku_mapping_audits for select to authenticated using ((select auth.uid())=user_id);
revoke insert,update,delete on public.supplier_sku_links from authenticated;
revoke insert,update,delete on public.supplier_sku_mapping_audits from authenticated;
grant select on public.supplier_sku_links,public.supplier_sku_mapping_audits to authenticated;
grant usage,select on sequence public.supplier_sku_mapping_audits_id_seq to authenticated;

create or replace function public.reject_supplier_sku_mapping_audit_mutation() returns trigger language plpgsql set search_path=public as $$ begin raise exception 'immutable_supplier_sku_mapping_audit'; end; $$;
create trigger supplier_sku_mapping_audits_immutable before update or delete on public.supplier_sku_mapping_audits for each row execute function public.reject_supplier_sku_mapping_audit_mutation();

create or replace function private.write_supplier_sku_mapping_audit(p_action text,p_supplier_id bigint,p_raw text,p_normalized text,p_previous bigint,p_new bigint,p_reason text)
returns void language plpgsql security definer set search_path=private,public as $$
declare v_user uuid:=auth.uid(); v_supplier text; v_old text; v_new text;
begin
 select name into v_supplier from public.factories where id=p_supplier_id and user_id=v_user;
 select seller_sku into v_old from public.product_variants where id=p_previous and user_id=v_user;
 select seller_sku into v_new from public.product_variants where id=p_new and user_id=v_user;
 insert into public.supplier_sku_mapping_audits(user_id,actor_id,supplier_id,supplier_name_snapshot,raw_external_sku,normalized_external_sku,action,previous_product_variant_id,previous_seller_sku_snapshot,new_product_variant_id,new_seller_sku_snapshot,reason)
 values(v_user,v_user,p_supplier_id,v_supplier,p_raw,p_normalized,p_action,p_previous,v_old,p_new,v_new,nullif(btrim(p_reason),''));
end; $$;

create or replace function public.confirm_supplier_sku_mapping(p_supplier_id bigint,p_external_sku text,p_product_variant_id bigint,p_source_row_ids bigint[] default '{}')
returns bigint language plpgsql security definer set search_path=private,public as $$
declare v_user uuid:=auth.uid(); v_normalized text:=private.normalize_supplier_external_sku(p_external_sku); v_existing public.supplier_sku_links%rowtype; v_id bigint;
begin
 if v_user is null then raise exception 'Authentication is required.'; end if;
 if v_normalized='' then raise exception 'External SKU is required.'; end if;
 if not exists(select 1 from public.factories where id=p_supplier_id and user_id=v_user) then raise exception 'Supplier not found.'; end if;
 if not exists(select 1 from public.product_variants where id=p_product_variant_id and user_id=v_user) then raise exception 'Product variant not found.'; end if;
 select * into v_existing from public.supplier_sku_links where user_id=v_user and supplier_id=p_supplier_id and normalized_external_sku=v_normalized and is_active for update;
 if found then
   if v_existing.product_variant_id=p_product_variant_id then raise exception 'Duplicate active supplier SKU mapping.'; end if;
   raise exception 'Active supplier SKU mapping conflicts; reassign it explicitly.';
 end if;
 insert into public.supplier_sku_links(user_id,supplier_id,template,template_id,external_sku,normalized_external_sku,product_variant_id,received_at,is_active) values(v_user,p_supplier_id,'',null,p_external_sku,v_normalized,p_product_variant_id,timezone('utc',now()),true) returning id into v_id;
 perform private.write_supplier_sku_mapping_audit('CONFIRMED',p_supplier_id,p_external_sku,v_normalized,null,p_product_variant_id,null);
 if cardinality(p_source_row_ids)>0 then
   perform set_config('app.supplier_mapping_write','on',true);
   update public.inbound_import_source_rows sr set product_variant_id=p_product_variant_id,seller_sku_snapshot=pv.seller_sku,product_name_snapshot=m.name,option_name_snapshot=concat_ws(' / ',c.name,s.name)
   from public.product_variants pv join public.models m on m.id=pv.model_id and m.user_id=pv.user_id join public.sizes s on s.id=pv.size_id and s.user_id=pv.user_id join public.colors c on c.id=pv.color_id and c.user_id=pv.user_id
   where sr.id=any(p_source_row_ids) and sr.user_id=v_user and pv.id=p_product_variant_id and pv.user_id=v_user;
 end if;
 return v_id;
end; $$;

create or replace function public.reassign_supplier_sku_mapping(p_supplier_id bigint,p_external_sku text,p_product_variant_id bigint,p_reason text)
returns bigint language plpgsql security definer set search_path=private,public as $$
declare v_user uuid:=auth.uid(); v_normalized text:=private.normalize_supplier_external_sku(p_external_sku); v_old public.supplier_sku_links%rowtype; v_id bigint;
begin
 if nullif(btrim(p_reason),'') is null then raise exception 'A reassign reason is required.'; end if;
 select * into v_old from public.supplier_sku_links where user_id=v_user and supplier_id=p_supplier_id and normalized_external_sku=v_normalized and is_active for update;
 if not found then raise exception 'Active supplier SKU mapping not found.'; end if;
 if not exists(select 1 from public.product_variants where id=p_product_variant_id and user_id=v_user) then raise exception 'Product variant not found.'; end if;
 if v_old.product_variant_id=p_product_variant_id then raise exception 'Supplier SKU already maps to this ProductVariant.'; end if;
 update public.supplier_sku_links set is_active=false,deactivated_at=timezone('utc',now()),deactivation_reason=p_reason where id=v_old.id;
 insert into public.supplier_sku_links(user_id,supplier_id,template,external_sku,normalized_external_sku,product_variant_id,received_at,is_active) values(v_user,p_supplier_id,'',p_external_sku,v_normalized,p_product_variant_id,timezone('utc',now()),true) returning id into v_id;
 perform private.write_supplier_sku_mapping_audit('REASSIGNED',p_supplier_id,p_external_sku,v_normalized,v_old.product_variant_id,p_product_variant_id,p_reason); return v_id;
end; $$;

create or replace function public.deactivate_supplier_sku_mapping(p_supplier_id bigint,p_external_sku text,p_reason text)
returns void language plpgsql security definer set search_path=private,public as $$
declare v_user uuid:=auth.uid(); v_normalized text:=private.normalize_supplier_external_sku(p_external_sku); v_old public.supplier_sku_links%rowtype;
begin
 if nullif(btrim(p_reason),'') is null then raise exception 'A deactivation reason is required.'; end if;
 select * into v_old from public.supplier_sku_links where user_id=v_user and supplier_id=p_supplier_id and normalized_external_sku=v_normalized and is_active for update;
 if not found then raise exception 'Active supplier SKU mapping not found.'; end if;
 update public.supplier_sku_links set is_active=false,deactivated_at=timezone('utc',now()),deactivation_reason=p_reason where id=v_old.id;
 perform private.write_supplier_sku_mapping_audit('DEACTIVATED',p_supplier_id,p_external_sku,v_normalized,v_old.product_variant_id,null,p_reason);
end; $$;
grant execute on function public.confirm_supplier_sku_mapping(bigint,text,bigint,bigint[]),public.reassign_supplier_sku_mapping(bigint,text,bigint,text),public.deactivate_supplier_sku_mapping(bigint,text,text) to authenticated;
revoke all on function private.normalize_supplier_external_sku(text),private.write_supplier_sku_mapping_audit(text,bigint,text,text,bigint,bigint,text) from public,anon,authenticated;

-- Keep canonical source evidence immutable outside the narrowly scoped confirm RPC.
create or replace function public.reject_canonical_evidence_mutation() returns trigger language plpgsql set search_path=public as $$ begin if current_setting('app.supplier_mapping_write',true)='on' and tg_table_name='inbound_import_source_rows' then return new; end if; raise exception 'immutable_canonical_evidence'; end; $$;
