-- Supplier SKU identity is independent of templates.  This migration runs after
-- the canonical arrival migration, so it also replaces the legacy receipt RPC.
create schema if not exists private;
create or replace function private.normalize_supplier_external_sku(p_value text)
returns text language sql immutable strict set search_path=pg_catalog as $$
  select btrim(p_value, E' \t\n\r\f\v' || U&'\\0085\\00A0\\1680\\2000\\2001\\2002\\2003\\2004\\2005\\2006\\2007\\2008\\2009\\200A\\2028\\2029\\202F\\205F\\3000')
$$;

alter table public.supplier_sku_links add column if not exists normalized_external_sku text;
alter table public.supplier_sku_links add column if not exists is_active boolean not null default true;
alter table public.supplier_sku_links add column if not exists deactivated_at timestamptz;
alter table public.supplier_sku_links add column if not exists deactivation_reason text;
update public.supplier_sku_links set normalized_external_sku=private.normalize_supplier_external_sku(external_sku) where normalized_external_sku is null;
alter table public.supplier_sku_links alter column normalized_external_sku set not null;

-- PostgreSQL truncates the old generated constraint name on some installations.
-- Find it by definition rather than relying on an incomplete identifier.
do $$ declare v_name text;
begin
  for v_name in select c.conname from pg_constraint c
    where c.conrelid='public.supplier_sku_links'::regclass and c.contype='u'
      and pg_get_constraintdef(c.oid) = 'UNIQUE (user_id, supplier_id, template, external_sku)'
  loop execute format('alter table public.supplier_sku_links drop constraint %I', v_name); end loop;
end $$;
drop index if exists public.supplier_sku_links_exact_idx;
drop index if exists public.supplier_sku_links_exact_template_idx;
drop index if exists public.supplier_sku_links_active_exact_idx;
drop index if exists public.supplier_sku_links_one_active_exact_idx;

alter table public.supplier_sku_links drop constraint if exists supplier_sku_links_supplier_id_user_id_fkey;
alter table public.supplier_sku_links drop constraint if exists supplier_sku_links_product_variant_id_user_id_fkey;
alter table public.supplier_sku_links drop constraint if exists supplier_sku_links_supplier_id_fkey;
alter table public.supplier_sku_links drop constraint if exists supplier_sku_links_product_variant_id_fkey;
alter table public.supplier_sku_links add constraint supplier_sku_links_supplier_id_user_id_fkey foreign key (supplier_id,user_id) references public.factories(id,user_id) on delete restrict;
alter table public.supplier_sku_links add constraint supplier_sku_links_product_variant_id_user_id_fkey foreign key (product_variant_id,user_id) references public.product_variants(id,user_id) on delete restrict;

create table if not exists public.supplier_sku_mapping_audits (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  actor_id uuid not null references auth.users(id) on delete restrict,
  supplier_id bigint not null, supplier_name_snapshot text,
  raw_external_sku text not null, normalized_external_sku text not null,
  action text not null check (action in ('CONFIRMED','REASSIGNED','DEACTIVATED','LEGACY_CONFLICT','LEGACY_DUPLICATE_DEACTIVATED')),
  previous_product_variant_id bigint, previous_seller_sku_snapshot text,
  new_product_variant_id bigint, new_seller_sku_snapshot text, reason text,
  created_at timestamptz not null default timezone('utc',now()),
  foreign key (supplier_id,user_id) references public.factories(id,user_id) on delete restrict
);
create index if not exists supplier_sku_mapping_audits_owner_supplier_created_idx on public.supplier_sku_mapping_audits(user_id,supplier_id,created_at desc);

-- Collapse before creating the partial unique index.  Conflicts deactivate all
-- active records; same-target duplicates retain the newest record only.
with conflicts as (
  select user_id,supplier_id,normalized_external_sku from public.supplier_sku_links
  where is_active group by 1,2,3 having count(distinct product_variant_id)>1
), changed as (
  update public.supplier_sku_links l set is_active=false,deactivated_at=timezone('utc',now()),deactivation_reason='Legacy template mappings conflict; explicit resolution required.'
  from conflicts c where l.is_active and (l.user_id,l.supplier_id,l.normalized_external_sku)=(c.user_id,c.supplier_id,c.normalized_external_sku) returning l.*
)
insert into public.supplier_sku_mapping_audits(user_id,actor_id,supplier_id,supplier_name_snapshot,raw_external_sku,normalized_external_sku,action,previous_product_variant_id,reason)
select c.user_id,c.user_id,c.supplier_id,f.name,c.external_sku,c.normalized_external_sku,'LEGACY_CONFLICT',c.product_variant_id,c.deactivation_reason from changed c join public.factories f on f.id=c.supplier_id and f.user_id=c.user_id;
with ranked as (
  select id,row_number() over(partition by user_id,supplier_id,normalized_external_sku order by received_at desc,id desc) position from public.supplier_sku_links where is_active
), changed as (
  update public.supplier_sku_links l set is_active=false,deactivated_at=timezone('utc',now()),deactivation_reason='Superseded duplicate legacy mapping.' from ranked r where l.id=r.id and r.position>1 returning l.*
)
insert into public.supplier_sku_mapping_audits(user_id,actor_id,supplier_id,supplier_name_snapshot,raw_external_sku,normalized_external_sku,action,previous_product_variant_id,reason)
select c.user_id,c.user_id,c.supplier_id,f.name,c.external_sku,c.normalized_external_sku,'LEGACY_DUPLICATE_DEACTIVATED',c.product_variant_id,c.deactivation_reason from changed c join public.factories f on f.id=c.supplier_id and f.user_id=c.user_id;
create index supplier_sku_links_active_exact_idx on public.supplier_sku_links(user_id,supplier_id,normalized_external_sku) where is_active;
create unique index supplier_sku_links_one_active_exact_idx on public.supplier_sku_links(user_id,supplier_id,normalized_external_sku) where is_active;

alter table public.supplier_sku_links enable row level security;
alter table public.supplier_sku_mapping_audits enable row level security;
drop policy if exists "Users manage own supplier_sku_links" on public.supplier_sku_links;
drop policy if exists "Users read own supplier_sku_links" on public.supplier_sku_links;
drop policy if exists "Users read own supplier_sku_mapping_audits" on public.supplier_sku_mapping_audits;
create policy "Users read own supplier_sku_links" on public.supplier_sku_links for select to authenticated using ((select auth.uid())=user_id);
create policy "Users read own supplier_sku_mapping_audits" on public.supplier_sku_mapping_audits for select to authenticated using ((select auth.uid())=user_id);
revoke all on public.supplier_sku_links,public.supplier_sku_mapping_audits from public,anon;
revoke insert,update,delete on public.supplier_sku_links,public.supplier_sku_mapping_audits from authenticated;
grant select on public.supplier_sku_links,public.supplier_sku_mapping_audits to authenticated;

create or replace function public.reject_supplier_sku_mapping_audit_mutation() returns trigger language plpgsql set search_path=public as $$ begin raise exception 'immutable_supplier_sku_mapping_audit'; end; $$;
drop trigger if exists supplier_sku_mapping_audits_immutable on public.supplier_sku_mapping_audits;
create trigger supplier_sku_mapping_audits_immutable before update or delete on public.supplier_sku_mapping_audits for each row execute function public.reject_supplier_sku_mapping_audit_mutation();

create or replace function private.write_supplier_sku_mapping_audit(p_action text,p_supplier_id bigint,p_raw text,p_normalized text,p_previous bigint,p_new bigint,p_reason text)
returns void language plpgsql security definer set search_path=private,public as $$
declare v_user uuid:=auth.uid();
begin
 insert into public.supplier_sku_mapping_audits(user_id,actor_id,supplier_id,supplier_name_snapshot,raw_external_sku,normalized_external_sku,action,previous_product_variant_id,previous_seller_sku_snapshot,new_product_variant_id,new_seller_sku_snapshot,reason)
 select v_user,v_user,p_supplier_id,f.name,p_raw,p_normalized,p_action,p_previous,old.seller_sku,p_new,new.seller_sku,nullif(btrim(p_reason),'')
 from public.factories f left join public.product_variants old on old.id=p_previous and old.user_id=v_user left join public.product_variants new on new.id=p_new and new.user_id=v_user where f.id=p_supplier_id and f.user_id=v_user;
end $$;

create or replace function public.confirm_supplier_sku_mapping(p_supplier_id bigint,p_external_sku text,p_product_variant_id bigint,p_source_row_ids bigint[] default '{}') returns bigint language plpgsql security definer set search_path=private,public as $$
declare v_user uuid:=auth.uid(); v_normalized text:=private.normalize_supplier_external_sku(p_external_sku); v_existing public.supplier_sku_links%rowtype; v_id bigint; v_requested integer; v_locked integer;
begin
 if v_user is null then raise exception 'Authentication is required.'; end if;
 if coalesce(v_normalized,'')='' then raise exception 'External SKU is required.'; end if;
 if not exists(select 1 from public.factories where id=p_supplier_id and user_id=v_user) then raise exception 'Supplier not found.'; end if;
 if not exists(select 1 from public.product_variants where id=p_product_variant_id and user_id=v_user) then raise exception 'Product variant not found.'; end if;
 v_requested:=coalesce(cardinality(p_source_row_ids),0);
 if v_requested <> coalesce((select count(distinct x) from unnest(p_source_row_ids) x),0) then raise exception 'duplicate source row IDs'; end if;
 if v_requested>0 then
   perform 1 from public.inbound_import_source_rows where id=any(p_source_row_ids) and user_id=v_user for update; get diagnostics v_locked=row_count;
   if v_locked<>v_requested then raise exception 'Source rows are missing or not owned by the current user.'; end if;
   if exists(select 1 from public.inbound_import_source_rows sr join public.inbound_import_revisions r on r.id=sr.inbound_import_revision_id and r.user_id=sr.user_id join public.inbound_imports i on i.id=r.inbound_import_id and i.user_id=r.user_id where sr.id=any(p_source_row_ids) and (i.supplier_id<>p_supplier_id or private.normalize_supplier_external_sku(sr.external_sku)<>v_normalized or (sr.product_variant_id is not null and sr.product_variant_id<>p_product_variant_id) or exists(select 1 from public.factory_arrival_items ai join public.factory_receipt_lines rl on rl.factory_arrival_allocation_id in (select al.id from public.factory_arrival_allocations al where al.factory_arrival_item_id=ai.id and al.user_id=ai.user_id) where ai.inbound_import_source_row_id=sr.id and ai.user_id=sr.user_id) or exists(select 1 from public.factory_arrival_items ai where ai.inbound_import_source_row_id=sr.id and ai.user_id=sr.user_id and ai.received_quantity>0))) then raise exception 'Source rows do not match this exact supplier SKU mapping'; end if;
 end if;
 select * into v_existing from public.supplier_sku_links where user_id=v_user and supplier_id=p_supplier_id and normalized_external_sku=v_normalized and is_active for update;
 if found then if v_existing.product_variant_id=p_product_variant_id then raise exception 'Duplicate active supplier SKU mapping.'; else raise exception 'Active supplier SKU mapping conflicts; reassign it explicitly.'; end if; end if;
 insert into public.supplier_sku_links(user_id,supplier_id,template,template_id,external_sku,normalized_external_sku,product_variant_id,received_at,is_active) values(v_user,p_supplier_id,'',null,p_external_sku,v_normalized,p_product_variant_id,timezone('utc',now()),true) returning id into v_id;
 perform private.write_supplier_sku_mapping_audit('CONFIRMED',p_supplier_id,p_external_sku,v_normalized,null,p_product_variant_id,null);
 if v_requested>0 then perform set_config('app.supplier_mapping_write','on',true); update public.inbound_import_source_rows sr set product_variant_id=p_product_variant_id,seller_sku_snapshot=pv.seller_sku,product_name_snapshot=m.name,option_name_snapshot=concat_ws(' / ',c.name,s.name) from public.product_variants pv join public.models m on m.id=pv.model_id and m.user_id=pv.user_id join public.sizes s on s.id=pv.size_id and s.user_id=pv.user_id join public.colors c on c.id=pv.color_id and c.user_id=pv.user_id where sr.id=any(p_source_row_ids) and sr.user_id=v_user and pv.id=p_product_variant_id and pv.user_id=v_user; get diagnostics v_locked=row_count; if v_locked<>v_requested then raise exception 'Source-row update cardinality mismatch.'; end if; end if;
 return v_id;
end $$;

create or replace function public.reassign_supplier_sku_mapping(p_supplier_id bigint,p_external_sku text,p_product_variant_id bigint,p_reason text) returns bigint language plpgsql security definer set search_path=private,public as $$
declare v_user uuid:=auth.uid(); v_normalized text:=private.normalize_supplier_external_sku(p_external_sku); v_old public.supplier_sku_links%rowtype; v_id bigint;
begin
 if v_user is null then raise exception 'Authentication is required.'; end if; if nullif(btrim(p_reason),'') is null then raise exception 'A reassign reason is required.'; end if;
 select * into v_old from public.supplier_sku_links where user_id=v_user and supplier_id=p_supplier_id and normalized_external_sku=v_normalized and is_active for update; if not found then raise exception 'Active supplier SKU mapping not found.'; end if;
 if not exists(select 1 from public.product_variants where id=p_product_variant_id and user_id=v_user) then raise exception 'Product variant not found.'; end if; if v_old.product_variant_id=p_product_variant_id then raise exception 'Supplier SKU already maps to this ProductVariant.'; end if;
 update public.supplier_sku_links set is_active=false,deactivated_at=timezone('utc',now()),deactivation_reason=p_reason where id=v_old.id;
 insert into public.supplier_sku_links(user_id,supplier_id,template,external_sku,normalized_external_sku,product_variant_id,received_at,is_active) values(v_user,p_supplier_id,'',p_external_sku,v_normalized,p_product_variant_id,timezone('utc',now()),true) returning id into v_id;
 perform private.write_supplier_sku_mapping_audit('REASSIGNED',p_supplier_id,p_external_sku,v_normalized,v_old.product_variant_id,p_product_variant_id,p_reason); return v_id;
end $$;
create or replace function public.deactivate_supplier_sku_mapping(p_supplier_id bigint,p_external_sku text,p_reason text) returns void language plpgsql security definer set search_path=private,public as $$
declare v_user uuid:=auth.uid(); v_normalized text:=private.normalize_supplier_external_sku(p_external_sku); v_old public.supplier_sku_links%rowtype;
begin
 if v_user is null then raise exception 'Authentication is required.'; end if; if nullif(btrim(p_reason),'') is null then raise exception 'A deactivation reason is required.'; end if;
 select * into v_old from public.supplier_sku_links where user_id=v_user and supplier_id=p_supplier_id and normalized_external_sku=v_normalized and is_active for update; if not found then raise exception 'Active supplier SKU mapping not found.'; end if;
 update public.supplier_sku_links set is_active=false,deactivated_at=timezone('utc',now()),deactivation_reason=p_reason where id=v_old.id; perform private.write_supplier_sku_mapping_audit('DEACTIVATED',p_supplier_id,p_external_sku,v_normalized,v_old.product_variant_id,null,p_reason);
end $$;
revoke all on function public.confirm_supplier_sku_mapping(bigint,text,bigint,bigint[]),public.reassign_supplier_sku_mapping(bigint,text,bigint,text),public.deactivate_supplier_sku_mapping(bigint,text,text) from public,anon;
grant execute on function public.confirm_supplier_sku_mapping(bigint,text,bigint,bigint[]),public.reassign_supplier_sku_mapping(bigint,text,bigint,text),public.deactivate_supplier_sku_mapping(bigint,text,text) to authenticated;
revoke all on function private.normalize_supplier_external_sku(text),private.write_supplier_sku_mapping_audit(text,bigint,text,text,bigint,bigint,text) from public,anon,authenticated;

-- The legacy compatibility endpoint remains atomic and deliberately mapping-free.
create or replace function public.receive_inbound_draft_rows(p_draft_id bigint,p_rows jsonb) returns void language plpgsql security definer set search_path=public as $$
declare v_user_id uuid:=auth.uid(); v_input jsonb; v_draft public.inbound_drafts%rowtype; v_row public.inbound_draft_rows%rowtype; v_variant public.product_variants%rowtype; v_quantity integer; v_open integer;
begin
 if v_user_id is null then raise exception 'Authentication is required.'; end if; if jsonb_typeof(p_rows) is distinct from 'array' then raise exception 'p_rows must be a JSON array.'; end if;
 select * into v_draft from public.inbound_drafts where id=p_draft_id and user_id=v_user_id for update; if not found or v_draft.status='received' then raise exception 'Inbound draft cannot be received.'; end if;
 for v_input in select * from jsonb_array_elements(p_rows) loop
  select * into v_row from public.inbound_draft_rows where id=(v_input->>'row_id')::bigint and inbound_draft_id=p_draft_id and user_id=v_user_id for update; if not found then raise exception 'Inbound draft row not found.'; end if; if v_row.product_variant_id is null then raise exception 'Unmatched inbound rows cannot be received.'; end if;
  v_quantity:=(v_input->>'quantity')::integer; if v_quantity is null or v_quantity<=0 or v_quantity>v_row.quantity-v_row.received_quantity then raise exception 'Receive quantity is invalid.'; end if;
  select * into v_variant from public.product_variants where id=v_row.product_variant_id and user_id=v_user_id; if not found then raise exception 'Assigned internal SKU not found.'; end if;
  update public.inbound_draft_rows set received_quantity=received_quantity+v_quantity,updated_at=timezone('utc',now()) where id=v_row.id;
  insert into public.inventory(user_id,model_id,size_id,color_id,warehouse_id,quantity) values(v_user_id,v_variant.model_id,v_variant.size_id,v_variant.color_id,v_row.warehouse_id,v_quantity) on conflict(user_id,model_id,size_id,color_id,warehouse_id) do update set quantity=public.inventory.quantity+excluded.quantity,updated_at=timezone('utc',now());
  insert into public.transactions(user_id,date,model_id,size_id,color_id,type,quantity,warehouse_id,source_channel,reference_type,reference_id,memo) values(v_user_id,current_date,v_variant.model_id,v_variant.size_id,v_variant.color_id,'INBOUND',v_quantity,v_row.warehouse_id,'inbound-draft','inbound_draft_row',v_row.id,'검수 입고');
  insert into public.inventory_sync_outbox(user_id,channel_product_ref_id,target_quantity,status,last_error,requested_at,updated_at) select v_user_id,ref.id,greatest(coalesce(sum(inv.quantity),0)-coalesce((select sum(quantity) from public.inventory_reservations where user_id=v_user_id and product_variant_id=v_variant.id and status='active'),0),0),'required','동기화 필요: 현재 provider는 재고 수량 쓰기를 지원하지 않습니다.',timezone('utc',now()),timezone('utc',now()) from public.channel_product_refs ref left join public.inventory inv on inv.user_id=v_user_id and inv.model_id=v_variant.model_id and inv.size_id=v_variant.size_id and inv.color_id=v_variant.color_id where ref.user_id=v_user_id and ref.variant_id=v_variant.id group by ref.id on conflict(user_id,channel_product_ref_id) do update set target_quantity=excluded.target_quantity,status='required',last_error=excluded.last_error,requested_at=excluded.requested_at,updated_at=excluded.updated_at;
 end loop;
 select count(*) into v_open from public.inbound_draft_rows where inbound_draft_id=p_draft_id and user_id=v_user_id and received_quantity<quantity; update public.inbound_drafts set status=case when v_open=0 then 'received' else 'partial' end,updated_at=timezone('utc',now()) where id=p_draft_id and user_id=v_user_id;
end $$;
revoke all on function public.receive_inbound_draft_rows(bigint,jsonb) from public,anon;
grant execute on function public.receive_inbound_draft_rows(bigint,jsonb) to authenticated;

create or replace function public.reject_canonical_evidence_mutation() returns trigger language plpgsql set search_path=public as $$ begin if current_setting('app.supplier_mapping_write',true)='on' and tg_table_name='inbound_import_source_rows' then return new; end if; raise exception 'immutable_canonical_evidence'; end $$;
