-- Canonical boundary: InboundImport -> FactoryArrival -> receipt evidence -> Inventory/Transaction.
-- This migration deliberately does not call a receipt RPC, does not insert transactions,
-- and does not update public.inventory. Existing ledger evidence is linked, never replayed.

create table public.inbound_imports (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  legacy_inbound_draft_id bigint unique,
  supplier_id bigint references public.factories(id) on delete restrict,
  source_type text not null check (source_type in ('FILE', 'MANUAL')),
  created_at timestamptz not null default timezone('utc', now()),
  unique (id, user_id)
);
create table public.inbound_import_revisions (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  inbound_import_id bigint not null,
  revision_number integer not null check (revision_number > 0),
  source_storage_path text, source_filename text, source_file_hash text, source_sheet_name text,
  source_header_row_number integer, source_headers jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  unique (id, user_id), unique (inbound_import_id, revision_number),
  foreign key (inbound_import_id, user_id) references public.inbound_imports(id, user_id) on delete restrict
);
create table public.inbound_import_source_rows (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  inbound_import_revision_id bigint not null,
  legacy_inbound_draft_row_id bigint unique,
  source_row_number integer, external_sku text, quantity integer, source_values jsonb not null default '{}'::jsonb,
  validation_error text, product_variant_id bigint,
  seller_sku_snapshot text, product_name_snapshot text, option_name_snapshot text, supplier_name_snapshot text,
  created_at timestamptz not null default timezone('utc', now()),
  unique (id, user_id),
  foreign key (inbound_import_revision_id, user_id) references public.inbound_import_revisions(id, user_id) on delete restrict,
  foreign key (product_variant_id, user_id) references public.product_variants(id, user_id) on delete restrict
);

alter table public.factory_arrivals drop constraint if exists factory_arrivals_status_check;
alter table public.factory_arrivals drop constraint if exists factory_arrivals_factory_id_user_id_fkey;
alter table public.factory_arrivals add constraint factory_arrivals_factory_id_user_id_fkey foreign key (factory_id, user_id) references public.factories(id, user_id) on delete restrict;
alter table public.factory_arrivals add column if not exists import_revision_id bigint;
alter table public.factory_arrivals add column if not exists follow_up_parent_arrival_id bigint;
alter table public.factory_arrivals add column if not exists source_type text;
alter table public.factory_arrivals add column if not exists external_shipment_reference text;
alter table public.factory_arrivals add column if not exists supplier_name_snapshot text;
update public.factory_arrivals set status = case status when '예정' then 'READY' when '부분입고' then 'PARTIAL' when '입고완료' then 'RECEIVED' when '취소' then 'CANCELLED' else upper(status) end;
update public.factory_arrivals set source_type = case when source_channel = 'csv' then 'FILE' else 'MANUAL' end where source_type is null;
update public.factory_arrivals set supplier_name_snapshot = factories.name from public.factories where factories.id = factory_arrivals.factory_id and factories.user_id = factory_arrivals.user_id and supplier_name_snapshot is null;
alter table public.factory_arrivals alter column source_type set not null;
alter table public.factory_arrivals add constraint factory_arrivals_status_check check (status in ('DRAFT', 'READY', 'PARTIAL', 'RECEIVED', 'VARIANCE_CLOSED', 'CANCELLED'));
alter table public.factory_arrivals add constraint factory_arrivals_import_revision_id_user_id_fkey foreign key (import_revision_id, user_id) references public.inbound_import_revisions(id, user_id) on delete restrict;
alter table public.factory_arrivals add constraint factory_arrivals_follow_up_parent_id_user_id_fkey foreign key (follow_up_parent_arrival_id, user_id) references public.factory_arrivals(id, user_id) on delete restrict;

alter table public.factory_arrival_items add column if not exists product_variant_id bigint;
alter table public.factory_arrival_items add column if not exists inbound_import_source_row_id bigint;
alter table public.factory_arrival_items add column if not exists external_sku_snapshot text;
alter table public.factory_arrival_items add column if not exists seller_sku_snapshot text;
alter table public.factory_arrival_items add column if not exists product_name_snapshot text;
alter table public.factory_arrival_items add column if not exists option_name_snapshot text;
alter table public.factory_arrival_items alter column model_id drop not null;
alter table public.factory_arrival_items alter column size_id drop not null;
alter table public.factory_arrival_items alter column color_id drop not null;
alter table public.factory_arrival_items alter column ordered_quantity drop not null;
-- Composite references below must be backed by a matching unique key; the
-- identity primary key alone is not sufficient for (id, user_id) FKs.
alter table public.factory_arrival_items add constraint factory_arrival_items_id_user_id_key unique (id, user_id);
alter table public.transactions add constraint transactions_id_user_id_key unique (id, user_id);
alter table public.factory_arrival_items drop constraint if exists factory_arrival_items_factory_arrival_id_user_id_fkey;
alter table public.factory_arrival_items add constraint factory_arrival_items_factory_arrival_id_user_id_fkey foreign key (factory_arrival_id, user_id) references public.factory_arrivals(id, user_id) on delete restrict;
alter table public.factory_arrival_items add constraint factory_arrival_items_product_variant_id_user_id_fkey foreign key (product_variant_id, user_id) references public.product_variants(id, user_id) on delete restrict;
alter table public.factory_arrival_items add constraint factory_arrival_items_source_row_id_user_id_fkey foreign key (inbound_import_source_row_id, user_id) references public.inbound_import_source_rows(id, user_id) on delete restrict;
alter table public.factory_arrival_items add constraint factory_arrival_items_one_source_row_key unique (inbound_import_source_row_id);
update public.factory_arrival_items i set product_variant_id = pv.id, seller_sku_snapshot = pv.seller_sku
from public.product_variants pv where pv.user_id = i.user_id and pv.model_id = i.model_id and pv.size_id = i.size_id and pv.color_id = i.color_id and i.product_variant_id is null;

create table public.factory_arrival_allocations (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  factory_arrival_id bigint not null, factory_arrival_item_id bigint not null, product_variant_id bigint not null, warehouse_id bigint not null,
  allocated_quantity integer not null check (allocated_quantity > 0),
  normally_received_quantity integer not null default 0 check (normally_received_quantity >= 0),
  shortage_closed_quantity integer not null default 0 check (shortage_closed_quantity >= 0),
  warehouse_name_snapshot text, created_at timestamptz not null default timezone('utc', now()), updated_at timestamptz not null default timezone('utc', now()),
  unique (id, user_id),
  foreign key (factory_arrival_id, user_id) references public.factory_arrivals(id, user_id) on delete restrict,
  foreign key (factory_arrival_item_id, user_id) references public.factory_arrival_items(id, user_id) on delete restrict,
  foreign key (product_variant_id, user_id) references public.product_variants(id, user_id) on delete restrict,
  foreign key (warehouse_id, user_id) references public.warehouses(id, user_id) on delete restrict,
  check (normally_received_quantity + shortage_closed_quantity <= allocated_quantity)
);
create table public.factory_receipt_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  factory_arrival_id bigint not null, event_kind text not null default 'MIGRATED_LEGACY_RECEIPT', received_at timestamptz not null,
  immutable_payload jsonb not null default '{}'::jsonb, created_at timestamptz not null default timezone('utc', now()),
  unique (id, user_id), foreign key (factory_arrival_id, user_id) references public.factory_arrivals(id, user_id) on delete restrict
);
create table public.factory_receipt_lines (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  factory_receipt_event_id bigint not null, factory_arrival_allocation_id bigint, transaction_id bigint,
  received_quantity integer not null check (received_quantity > 0), seller_sku_snapshot text, product_name_snapshot text, option_name_snapshot text, warehouse_name_snapshot text,
  created_at timestamptz not null default timezone('utc', now()), unique (id, user_id),
  foreign key (factory_receipt_event_id, user_id) references public.factory_receipt_events(id, user_id) on delete restrict,
  foreign key (factory_arrival_allocation_id, user_id) references public.factory_arrival_allocations(id, user_id) on delete restrict,
  foreign key (transaction_id, user_id) references public.transactions(id, user_id) on delete restrict
);
create table public.inbound_migration_exceptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  inbound_import_source_row_id bigint, exception_type text not null, details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  unique (id, user_id), foreign key (inbound_import_source_row_id, user_id) references public.inbound_import_source_rows(id, user_id) on delete restrict
);

-- An allocation cannot cross an arrival, item, variant, or owner boundary.
create or replace function public.assert_factory_arrival_allocation_consistency()
returns trigger language plpgsql set search_path = public as $$
begin
  if not exists (
    select 1 from public.factory_arrival_items i
    where i.id = new.factory_arrival_item_id
      and i.user_id = new.user_id
      and i.factory_arrival_id = new.factory_arrival_id
      and i.product_variant_id = new.product_variant_id
  ) then
    raise exception 'factory_arrival_allocation_matches_item';
  end if;
  return new;
end;
$$;
create trigger factory_arrival_allocation_consistency
before insert or update on public.factory_arrival_allocations
for each row execute function public.assert_factory_arrival_allocation_consistency();

create index inbound_imports_user_id_idx on public.inbound_imports(user_id);
create index inbound_import_revisions_user_import_idx on public.inbound_import_revisions(user_id, inbound_import_id);
create index inbound_import_source_rows_user_revision_idx on public.inbound_import_source_rows(user_id, inbound_import_revision_id);
create index factory_arrival_allocations_user_arrival_idx on public.factory_arrival_allocations(user_id, factory_arrival_id);
create index factory_arrival_allocations_user_variant_warehouse_idx on public.factory_arrival_allocations(user_id, product_variant_id, warehouse_id);
create index factory_receipt_events_user_arrival_idx on public.factory_receipt_events(user_id, factory_arrival_id);
create index factory_receipt_lines_user_event_transaction_idx on public.factory_receipt_lines(user_id, factory_receipt_event_id, transaction_id);
create index inbound_migration_exceptions_user_row_idx on public.inbound_migration_exceptions(user_id, inbound_import_source_row_id);

alter table public.inbound_imports enable row level security;
alter table public.inbound_import_revisions enable row level security;
alter table public.inbound_import_source_rows enable row level security;
alter table public.factory_arrival_allocations enable row level security;
alter table public.factory_receipt_events enable row level security;
alter table public.factory_receipt_lines enable row level security;
alter table public.inbound_migration_exceptions enable row level security;
create policy "Users manage own inbound_imports" on public.inbound_imports for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Users read own inbound_import_revisions" on public.inbound_import_revisions for select to authenticated using ((select auth.uid()) = user_id);
create policy "Users insert own inbound_import_revisions" on public.inbound_import_revisions for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Users read own inbound_import_source_rows" on public.inbound_import_source_rows for select to authenticated using ((select auth.uid()) = user_id);
create policy "Users insert own inbound_import_source_rows" on public.inbound_import_source_rows for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Users manage own factory_arrival_allocations" on public.factory_arrival_allocations for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Users read own factory_receipt_events" on public.factory_receipt_events for select to authenticated using ((select auth.uid()) = user_id);
create policy "Users insert own factory_receipt_events" on public.factory_receipt_events for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Users read own factory_receipt_lines" on public.factory_receipt_lines for select to authenticated using ((select auth.uid()) = user_id);
create policy "Users insert own factory_receipt_lines" on public.factory_receipt_lines for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Users read own inbound_migration_exceptions" on public.inbound_migration_exceptions for select to authenticated using ((select auth.uid()) = user_id);
create policy "Users insert own inbound_migration_exceptions" on public.inbound_migration_exceptions for insert to authenticated with check ((select auth.uid()) = user_id);

create or replace function public.reject_canonical_evidence_mutation()
returns trigger language plpgsql set search_path = public as $$
begin
  raise exception 'immutable_canonical_evidence';
end;
$$;
create trigger inbound_import_revision_immutable before update or delete on public.inbound_import_revisions for each row execute function public.reject_canonical_evidence_mutation();
create trigger inbound_import_source_row_immutable before update or delete on public.inbound_import_source_rows for each row execute function public.reject_canonical_evidence_mutation();
create trigger factory_receipt_event_immutable before update or delete on public.factory_receipt_events for each row execute function public.reject_canonical_evidence_mutation();
create trigger factory_receipt_line_immutable before update or delete on public.factory_receipt_lines for each row execute function public.reject_canonical_evidence_mutation();

insert into public.inbound_imports (user_id, legacy_inbound_draft_id, supplier_id, source_type, created_at)
select user_id, id, supplier_id, case when source_filename is null then 'MANUAL' else 'FILE' end, created_at from public.inbound_drafts;
insert into public.inbound_import_revisions (user_id, inbound_import_id, revision_number, source_storage_path, source_filename, source_file_hash, source_sheet_name, source_header_row_number, source_headers, created_at)
select i.user_id, i.id, 1, d.source_storage_path, d.source_filename, d.source_file_hash, d.source_sheet_name, d.source_header_row_number, coalesce(d.source_headers, '{}'::jsonb), d.created_at from public.inbound_imports i join public.inbound_drafts d on d.id = i.legacy_inbound_draft_id;
insert into public.inbound_import_source_rows (user_id, inbound_import_revision_id, legacy_inbound_draft_row_id, source_row_number, external_sku, quantity, source_values, validation_error, product_variant_id, seller_sku_snapshot, product_name_snapshot, option_name_snapshot, supplier_name_snapshot, created_at)
select r.user_id, r.id, dr.id, dr.source_row_number, dr.external_sku, dr.quantity, dr.source_values, dr.validation_error, coalesce(dr.product_variant_id, pv.id), pv.seller_sku, m.name, concat_ws(' / ', s.name, c.name), f.name, dr.created_at
from public.inbound_import_revisions r join public.inbound_imports i on i.id=r.inbound_import_id join public.inbound_drafts d on d.id=i.legacy_inbound_draft_id join public.inbound_draft_rows dr on dr.inbound_draft_id=d.id
left join public.product_variants pv on pv.user_id=dr.user_id and pv.id=dr.product_variant_id left join public.models m on m.id=pv.model_id and m.user_id=pv.user_id left join public.sizes s on s.id=pv.size_id and s.user_id=pv.user_id left join public.colors c on c.id=pv.color_id and c.user_id=pv.user_id join public.factories f on f.id=d.supplier_id and f.user_id=d.user_id;
insert into public.factory_arrivals (user_id, factory_id, reference_code, expected_date, status, source_channel, source_type, import_revision_id, supplier_name_snapshot, created_at, updated_at)
select d.user_id, d.supplier_id, coalesce(d.source_filename, 'legacy-draft-' || d.id), d.created_at::date, case d.status when 'received' then 'RECEIVED' when 'partial' then 'PARTIAL' else 'DRAFT' end, 'manual', i.source_type, r.id, f.name, d.created_at, d.updated_at from public.inbound_drafts d join public.inbound_imports i on i.legacy_inbound_draft_id=d.id join public.inbound_import_revisions r on r.inbound_import_id=i.id join public.factories f on f.id=d.supplier_id and f.user_id=d.user_id;
insert into public.factory_arrival_items (user_id, factory_arrival_id, model_id, size_id, color_id, product_variant_id, inbound_import_source_row_id, external_sku_snapshot, seller_sku_snapshot, product_name_snapshot, option_name_snapshot, ordered_quantity, received_quantity, created_at, updated_at)
select sr.user_id, a.id, pv.model_id, pv.size_id, pv.color_id, sr.product_variant_id, sr.id, sr.external_sku, sr.seller_sku_snapshot, sr.product_name_snapshot, sr.option_name_snapshot, sr.quantity, coalesce(dr.received_quantity,0), sr.created_at, sr.created_at from public.inbound_import_source_rows sr join public.inbound_import_revisions r on r.id=sr.inbound_import_revision_id join public.factory_arrivals a on a.import_revision_id=r.id left join public.inbound_draft_rows dr on dr.id=sr.legacy_inbound_draft_row_id left join public.product_variants pv on pv.id=sr.product_variant_id and pv.user_id=sr.user_id;
insert into public.factory_arrival_allocations (user_id, factory_arrival_id, factory_arrival_item_id, product_variant_id, warehouse_id, allocated_quantity, normally_received_quantity, warehouse_name_snapshot, created_at, updated_at)
select i.user_id, i.factory_arrival_id, i.id, i.product_variant_id, dr.warehouse_id, i.ordered_quantity, least(i.received_quantity, i.ordered_quantity), w.name, i.created_at, i.updated_at from public.factory_arrival_items i join public.inbound_import_source_rows sr on sr.id=i.inbound_import_source_row_id join public.inbound_draft_rows dr on dr.id=sr.legacy_inbound_draft_row_id join public.warehouses w on w.id=dr.warehouse_id and w.user_id=i.user_id where i.product_variant_id is not null and i.ordered_quantity is not null;
-- Pre-canonical arrivals did not retain an allocation. Preserve their incoming
-- value only when the owner has exactly one warehouse; otherwise record the
-- missing evidence instead of assigning stock to an arbitrary warehouse.
insert into public.factory_arrival_allocations (user_id, factory_arrival_id, factory_arrival_item_id, product_variant_id, warehouse_id, allocated_quantity, normally_received_quantity, warehouse_name_snapshot)
select i.user_id, i.factory_arrival_id, i.id, i.product_variant_id, w.id, i.ordered_quantity, coalesce(i.received_quantity, 0), w.name
from public.factory_arrival_items i
join public.factory_arrivals a on a.id = i.factory_arrival_id and a.user_id = i.user_id
join public.warehouses w on w.user_id = i.user_id
where i.inbound_import_source_row_id is null and i.product_variant_id is not null and i.ordered_quantity is not null
  and (select count(*) from public.warehouses only_one where only_one.user_id = i.user_id) = 1;
insert into public.inbound_migration_exceptions (user_id, inbound_import_source_row_id, exception_type, details)
select i.user_id, i.inbound_import_source_row_id, 'unallocated_legacy_arrival', jsonb_build_object('factory_arrival_item_id', i.id)
from public.factory_arrival_items i
left join public.factory_arrival_allocations al on al.factory_arrival_item_id = i.id and al.user_id = i.user_id
where i.product_variant_id is not null and i.ordered_quantity is not null and al.id is null;
insert into public.inbound_migration_exceptions (user_id, inbound_import_source_row_id, exception_type, details)
select sr.user_id, sr.id, 'unmapped_or_invalid_source_row', jsonb_build_object('validation_error', sr.validation_error, 'product_variant_id', sr.product_variant_id)
from public.inbound_import_source_rows sr
where sr.validation_error is not null or sr.product_variant_id is null;
update public.factory_arrivals a set status = 'READY'
where a.status = 'DRAFT' and a.import_revision_id is not null
  and exists (select 1 from public.factory_arrival_items i where i.factory_arrival_id = a.id and i.user_id = a.user_id)
  and not exists (
    select 1 from public.factory_arrival_items i
    left join public.inbound_import_source_rows sr on sr.id = i.inbound_import_source_row_id and sr.user_id = i.user_id
    left join public.factory_arrival_allocations al on al.factory_arrival_item_id = i.id and al.user_id = i.user_id
    where i.factory_arrival_id = a.id and i.user_id = a.user_id
      and (i.product_variant_id is null or i.ordered_quantity is null or sr.validation_error is not null or al.id is null)
  );
insert into public.factory_receipt_events (user_id, factory_arrival_id, received_at, immutable_payload)
select t.user_id, a.id, t.created_at, jsonb_build_object('migration', 'legacy_inbound_draft_transaction', 'transaction_id', t.id) from public.transactions t join public.inbound_import_source_rows sr on sr.legacy_inbound_draft_row_id=t.reference_id and sr.user_id=t.user_id join public.inbound_import_revisions r on r.id=sr.inbound_import_revision_id join public.factory_arrivals a on a.import_revision_id=r.id where t.source_channel='inbound-draft' and t.reference_type='inbound_draft_row';
insert into public.factory_receipt_lines (user_id, factory_receipt_event_id, factory_arrival_allocation_id, transaction_id, received_quantity, seller_sku_snapshot, product_name_snapshot, option_name_snapshot, warehouse_name_snapshot)
select e.user_id, e.id, al.id, (e.immutable_payload->>'transaction_id')::bigint, t.quantity, i.seller_sku_snapshot, i.product_name_snapshot, i.option_name_snapshot, al.warehouse_name_snapshot from public.factory_receipt_events e join public.transactions t on t.id=(e.immutable_payload->>'transaction_id')::bigint and t.user_id=e.user_id join public.inbound_import_source_rows sr on sr.legacy_inbound_draft_row_id=t.reference_id and sr.user_id=t.user_id join public.factory_arrival_items i on i.inbound_import_source_row_id=sr.id join public.factory_arrival_allocations al on al.factory_arrival_item_id=i.id;
insert into public.inbound_migration_exceptions (user_id, inbound_import_source_row_id, exception_type, details)
select sr.user_id, sr.id, 'ambiguous_transaction_evidence', jsonb_build_object('legacy_received_quantity', dr.received_quantity, 'linked_transaction_quantity', coalesce(sum(t.quantity),0)) from public.inbound_import_source_rows sr join public.inbound_draft_rows dr on dr.id=sr.legacy_inbound_draft_row_id left join public.transactions t on t.user_id=sr.user_id and t.source_channel='inbound-draft' and t.reference_type='inbound_draft_row' and t.reference_id=dr.id group by sr.user_id, sr.id, dr.received_quantity having dr.received_quantity > 0 and coalesce(sum(t.quantity),0) <> dr.received_quantity;

-- Compatibility window: the old RPC remains callable, but its row update and
-- transaction write update the canonical aggregate in the same transaction.
create or replace function public.sync_legacy_inbound_draft_receipt()
returns trigger language plpgsql set search_path = public as $$
declare v_arrival_id bigint;
begin
  if new.received_quantity = old.received_quantity then return new; end if;
  update public.factory_arrival_allocations al
  set normally_received_quantity = new.received_quantity, updated_at = timezone('utc', now())
  from public.inbound_import_source_rows sr, public.factory_arrival_items i
  where sr.legacy_inbound_draft_row_id = new.id and sr.user_id = new.user_id
    and i.inbound_import_source_row_id = sr.id and i.user_id = new.user_id
    and al.factory_arrival_item_id = i.id and al.user_id = new.user_id
  returning al.factory_arrival_id into v_arrival_id;
  if v_arrival_id is not null then
    update public.factory_arrival_items i set received_quantity = new.received_quantity, updated_at = timezone('utc', now())
    from public.inbound_import_source_rows sr where sr.legacy_inbound_draft_row_id = new.id and sr.user_id = new.user_id and i.inbound_import_source_row_id = sr.id and i.user_id = new.user_id;
    update public.factory_arrivals a set status = case when exists (select 1 from public.factory_arrival_allocations al where al.factory_arrival_id = a.id and al.user_id = a.user_id and al.normally_received_quantity + al.shortage_closed_quantity < al.allocated_quantity) then 'PARTIAL' else 'RECEIVED' end, updated_at = timezone('utc', now()) where a.id = v_arrival_id and a.user_id = new.user_id;
  end if;
  return new;
end;
$$;
create trigger inbound_draft_row_canonical_receipt after update of received_quantity on public.inbound_draft_rows for each row execute function public.sync_legacy_inbound_draft_receipt();

-- Audit correction: all composite ownership references are real database
-- constraints, rather than application conventions.
alter table public.inbound_imports drop constraint if exists inbound_imports_supplier_id_fkey;
alter table public.inbound_imports add constraint inbound_imports_supplier_id_user_id_fkey
  foreign key (supplier_id, user_id) references public.factories(id, user_id) on delete restrict;
alter table public.factory_arrivals add constraint factory_arrivals_one_import_revision_key unique (import_revision_id);

-- Historical factory arrivals predate allocations.  Transaction warehouse
-- evidence is safe to use; if it is absent or split ambiguously we preserve an
-- exception instead of inventing a destination warehouse.
insert into public.factory_arrival_allocations
  (user_id, factory_arrival_id, factory_arrival_item_id, product_variant_id, warehouse_id,
   allocated_quantity, normally_received_quantity, warehouse_name_snapshot)
select i.user_id, i.factory_arrival_id, i.id, i.product_variant_id, t.warehouse_id,
       greatest(i.ordered_quantity, coalesce(sum(t.quantity), 0)), coalesce(sum(t.quantity), 0), w.name
from public.factory_arrival_items i
join public.factory_arrivals a on a.id = i.factory_arrival_id and a.user_id = i.user_id
join public.transactions t on t.user_id = i.user_id and t.source_channel = 'factory-arrival'
  and t.reference_type = 'factory_arrival' and t.reference_id = a.id
  and t.model_id = i.model_id and t.size_id = i.size_id and t.color_id = i.color_id
join public.warehouses w on w.id = t.warehouse_id and w.user_id = t.user_id
left join public.factory_arrival_allocations al on al.factory_arrival_item_id = i.id and al.user_id = i.user_id
where al.id is null and i.product_variant_id is not null
group by i.user_id, i.factory_arrival_id, i.id, i.product_variant_id, i.ordered_quantity, t.warehouse_id, w.name
having (select count(distinct t2.warehouse_id) from public.transactions t2 where t2.user_id=i.user_id and t2.source_channel='factory-arrival' and t2.reference_type='factory_arrival' and t2.reference_id=i.factory_arrival_id and t2.model_id=i.model_id and t2.size_id=i.size_id and t2.color_id=i.color_id) = 1;
insert into public.inbound_migration_exceptions (user_id, exception_type, details)
select i.user_id, 'over_received_legacy_arrival', jsonb_build_object('factory_arrival_item_id', i.id, 'ordered_quantity', i.ordered_quantity, 'received_quantity', i.received_quantity)
from public.factory_arrival_items i
where i.received_quantity > i.ordered_quantity;
insert into public.inbound_migration_exceptions (user_id, exception_type, details)
select i.user_id, 'ambiguous_legacy_factory_arrival_warehouse', jsonb_build_object('factory_arrival_item_id', i.id)
from public.factory_arrival_items i
left join public.factory_arrival_allocations al on al.factory_arrival_item_id = i.id and al.user_id = i.user_id
where i.inbound_import_source_row_id is null and i.product_variant_id is not null and al.id is null;
-- legacy_factory_arrival_transaction evidence is linked, never replayed.
insert into public.factory_receipt_events (user_id, factory_arrival_id, event_kind, received_at, immutable_payload)
select t.user_id, a.id, 'MIGRATED_LEGACY_RECEIPT', t.created_at,
       jsonb_build_object('migration', 'legacy_factory_arrival_transaction', 'transaction_id', t.id)
from public.transactions t
join public.factory_arrivals a on a.id = t.reference_id and a.user_id = t.user_id
where t.source_channel = 'factory-arrival' and t.reference_type = 'factory_arrival';
insert into public.factory_receipt_lines (user_id, factory_receipt_event_id, factory_arrival_allocation_id, transaction_id, received_quantity, warehouse_name_snapshot)
select e.user_id, e.id, al.id, t.id, t.quantity, al.warehouse_name_snapshot
from public.factory_receipt_events e
join public.transactions t on t.id = (e.immutable_payload->>'transaction_id')::bigint and t.user_id = e.user_id
join public.factory_arrival_allocations al on al.factory_arrival_id = e.factory_arrival_id and al.user_id = e.user_id and al.warehouse_id = t.warehouse_id
where e.immutable_payload->>'migration' = 'legacy_factory_arrival_transaction';

-- Direct PostgREST writes cannot alter receipt counters or fabricate receipt
-- evidence.  Only the audited RPCs below retain the narrowly scoped rights.
drop policy if exists "Users manage own factory_arrival_allocations" on public.factory_arrival_allocations;
drop policy if exists "Users insert own factory_receipt_events" on public.factory_receipt_events;
drop policy if exists "Users insert own factory_receipt_lines" on public.factory_receipt_lines;
create policy "Users read own factory_arrival_allocations" on public.factory_arrival_allocations for select to authenticated using ((select auth.uid()) = user_id);
revoke insert, update, delete on table public.factory_arrival_allocations from authenticated;
revoke insert, update, delete on table public.factory_receipt_events from authenticated;
revoke insert, update, delete on table public.factory_receipt_lines from authenticated;

create or replace function public.sync_legacy_inbound_draft_receipt_evidence()
returns trigger language plpgsql security definer set search_path = public as $$
declare v_event_id bigint; v_allocation public.factory_arrival_allocations%rowtype; v_arrival_id bigint;
begin
  if new.source_channel <> 'inbound-draft' or new.reference_type <> 'inbound_draft_row' then return new; end if;
  select al.* into v_allocation
  from public.inbound_import_source_rows sr join public.factory_arrival_items i on i.inbound_import_source_row_id=sr.id and i.user_id=sr.user_id
  join public.factory_arrival_allocations al on al.factory_arrival_item_id=i.id and al.user_id=i.user_id and al.warehouse_id=new.warehouse_id
  where sr.legacy_inbound_draft_row_id=new.reference_id and sr.user_id=new.user_id;
  if not found then return new; end if;
  v_arrival_id := v_allocation.factory_arrival_id;
  insert into public.factory_receipt_events(user_id,factory_arrival_id,event_kind,received_at,immutable_payload)
  values(new.user_id,v_arrival_id,'MIGRATED_LEGACY_RECEIPT',new.created_at,jsonb_build_object('migration','legacy_inbound_draft_transaction','transaction_id',new.id)) returning id into v_event_id;
  insert into public.factory_receipt_lines(user_id,factory_receipt_event_id,factory_arrival_allocation_id,transaction_id,received_quantity,warehouse_name_snapshot)
  values(new.user_id,v_event_id,v_allocation.id,new.id,new.quantity,v_allocation.warehouse_name_snapshot);
  return new;
end;
$$;
create trigger inbound_draft_transaction_canonical_evidence after insert on public.transactions
for each row execute function public.sync_legacy_inbound_draft_receipt_evidence();

create or replace function public.assert_factory_arrival_receipt_consistency()
returns trigger language plpgsql set search_path = public as $$
declare v_event public.factory_receipt_events%rowtype;
declare v_allocation public.factory_arrival_allocations%rowtype;
declare v_transaction public.transactions%rowtype;
begin
  select * into v_event from public.factory_receipt_events where id = new.factory_receipt_event_id and user_id = new.user_id;
  if not found then raise exception 'factory_arrival_receipt_consistency'; end if;
  if new.factory_arrival_allocation_id is not null then
    select * into v_allocation from public.factory_arrival_allocations where id = new.factory_arrival_allocation_id and user_id = new.user_id;
    if not found or v_allocation.factory_arrival_id <> v_event.factory_arrival_id then raise exception 'factory_arrival_receipt_consistency'; end if;
  end if;
  if new.transaction_id is not null then
    select * into v_transaction from public.transactions where id = new.transaction_id and user_id = new.user_id;
    if not found or v_transaction.warehouse_id <> v_allocation.warehouse_id or v_transaction.quantity <> new.received_quantity then raise exception 'factory_arrival_receipt_consistency'; end if;
  end if;
  return new;
end;
$$;
create trigger factory_receipt_line_consistency before insert on public.factory_receipt_lines
for each row execute function public.assert_factory_arrival_receipt_consistency();

-- Manual/CSV compatibility writes the complete canonical aggregate in one
-- transaction. A warehouse must be explicit when the account has multiple
-- warehouses; silently picking one would make incoming misleading.
create or replace function public.create_factory_arrival_with_allocations(
  p_factory_id bigint, p_expected_date date, p_memo text, p_source_channel text,
  p_warehouse_id bigint, p_items jsonb
) returns bigint language plpgsql security definer set search_path = public as $$
declare v_user_id uuid := auth.uid(); v_arrival_id bigint; v_item jsonb; v_variant public.product_variants%rowtype; v_warehouse_name text; v_item_id bigint;
begin
  if v_user_id is null then raise exception 'Authentication is required.'; end if;
  if p_source_channel not in ('manual', 'csv') then raise exception 'Invalid arrival source.'; end if;
  if not exists (select 1 from public.factories where id=p_factory_id and user_id=v_user_id) then raise exception 'Factory not found.'; end if;
  if p_warehouse_id is null then
    select id into p_warehouse_id from public.warehouses where user_id=v_user_id limit 2;
    if (select count(*) from public.warehouses where user_id=v_user_id) <> 1 then raise exception 'Warehouse must be selected.'; end if;
  end if;
  select name into v_warehouse_name from public.warehouses where id=p_warehouse_id and user_id=v_user_id;
  if not found then raise exception 'Warehouse not found.'; end if;
  insert into public.factory_arrivals(user_id,factory_id,expected_date,status,source_channel,source_type,memo)
  values(v_user_id,p_factory_id,p_expected_date,'READY',p_source_channel,case when p_source_channel='csv' then 'FILE' else 'MANUAL' end,p_memo) returning id into v_arrival_id;
  for v_item in select * from jsonb_array_elements(p_items) loop
    select * into v_variant from public.product_variants where user_id=v_user_id and model_id=(v_item->>'model_id')::bigint and size_id=(v_item->>'size_id')::bigint and color_id=(v_item->>'color_id')::bigint;
    if not found then raise exception 'ProductVariant not found.'; end if;
    insert into public.factory_arrival_items(user_id,factory_arrival_id,model_id,size_id,color_id,product_variant_id,ordered_quantity,received_quantity,seller_sku_snapshot)
    values(v_user_id,v_arrival_id,v_variant.model_id,v_variant.size_id,v_variant.color_id,v_variant.id,(v_item->>'ordered_quantity')::integer,0,v_variant.seller_sku) returning id into v_item_id;
    insert into public.factory_arrival_allocations(user_id,factory_arrival_id,factory_arrival_item_id,product_variant_id,warehouse_id,allocated_quantity,warehouse_name_snapshot)
    values(v_user_id,v_arrival_id,v_item_id,v_variant.id,p_warehouse_id,(v_item->>'ordered_quantity')::integer,v_warehouse_name);
  end loop;
  return v_arrival_id;
end;
$$;
revoke all on function public.create_factory_arrival_with_allocations(bigint,date,text,text,bigint,jsonb) from public, anon;
grant execute on function public.create_factory_arrival_with_allocations(bigint,date,text,text,bigint,jsonb) to authenticated;

-- The receipt RPC posts stock and canonical receipt evidence atomically. It
-- requires the allocation's warehouse, so a receipt can never drift from the
-- expected receipt aggregate.
create or replace function public.receive_factory_arrival(p_arrival_id bigint, p_warehouse_id bigint, p_items jsonb)
returns void language plpgsql security definer set search_path = public as $$
declare v_user_id uuid := auth.uid(); v_item jsonb; v_arrival public.factory_arrivals%rowtype; v_arrival_item public.factory_arrival_items%rowtype; v_allocation public.factory_arrival_allocations%rowtype; v_quantity integer; v_transaction_id bigint; v_event_id bigint;
begin
  if v_user_id is null then raise exception 'Authentication is required.'; end if;
  select * into v_arrival from public.factory_arrivals where id=p_arrival_id and user_id=v_user_id for update;
  if not found or v_arrival.status in ('RECEIVED','VARIANCE_CLOSED','CANCELLED') then raise exception 'This arrival cannot be received.'; end if;
  for v_item in select * from jsonb_array_elements(p_items) loop
    v_quantity := (v_item->>'quantity')::integer;
    select * into v_arrival_item from public.factory_arrival_items where id=(v_item->>'arrival_item_id')::bigint and factory_arrival_id=p_arrival_id and user_id=v_user_id for update;
    select * into v_allocation from public.factory_arrival_allocations where factory_arrival_item_id=v_arrival_item.id and warehouse_id=p_warehouse_id and user_id=v_user_id for update;
    if not found or v_quantity is null or v_quantity <= 0 or v_quantity > v_allocation.allocated_quantity-v_allocation.normally_received_quantity-v_allocation.shortage_closed_quantity then raise exception 'Receive quantity exceeds allocated remaining quantity.'; end if;
    update public.factory_arrival_allocations set normally_received_quantity = normally_received_quantity + v_quantity, updated_at=timezone('utc',now()) where id=v_allocation.id;
    update public.factory_arrival_items set received_quantity=received_quantity+v_quantity, updated_at=timezone('utc',now()) where id=v_arrival_item.id;
    insert into public.inventory(user_id,model_id,size_id,color_id,warehouse_id,quantity) values(v_user_id,v_arrival_item.model_id,v_arrival_item.size_id,v_arrival_item.color_id,p_warehouse_id,v_quantity) on conflict(user_id,model_id,size_id,color_id,warehouse_id) do update set quantity=public.inventory.quantity+excluded.quantity,updated_at=timezone('utc',now());
    insert into public.transactions(user_id,date,model_id,size_id,color_id,type,quantity,warehouse_id,source_channel,reference_type,reference_id,memo) values(v_user_id,current_date,v_arrival_item.model_id,v_arrival_item.size_id,v_arrival_item.color_id,'INBOUND',v_quantity,p_warehouse_id,'factory-arrival','factory_arrival',p_arrival_id,coalesce(v_arrival.memo,'공장 예정 입고 반영')) returning id into v_transaction_id;
    insert into public.factory_receipt_events(user_id,factory_arrival_id,event_kind,received_at,immutable_payload) values(v_user_id,p_arrival_id,'RECEIPT',timezone('utc',now()),jsonb_build_object('transaction_id',v_transaction_id)) returning id into v_event_id;
    insert into public.factory_receipt_lines(user_id,factory_receipt_event_id,factory_arrival_allocation_id,transaction_id,received_quantity,seller_sku_snapshot,product_name_snapshot,option_name_snapshot,warehouse_name_snapshot) values(v_user_id,v_event_id,v_allocation.id,v_transaction_id,v_quantity,v_arrival_item.seller_sku_snapshot,v_arrival_item.product_name_snapshot,v_arrival_item.option_name_snapshot,v_allocation.warehouse_name_snapshot);
  end loop;
  update public.factory_arrivals a set status=case when exists(select 1 from public.factory_arrival_items i left join public.factory_arrival_allocations al on al.factory_arrival_item_id=i.id and al.user_id=i.user_id where i.factory_arrival_id=a.id and i.user_id=a.user_id and (i.product_variant_id is null or al.id is null or al.normally_received_quantity+al.shortage_closed_quantity<al.allocated_quantity)) then 'PARTIAL' else 'RECEIVED' end,updated_at=timezone('utc',now()) where id=p_arrival_id and user_id=v_user_id;
end;
$$;
revoke all on function public.receive_factory_arrival(bigint,bigint,jsonb) from public, anon;
grant execute on function public.receive_factory_arrival(bigint,bigint,jsonb) to authenticated;
